MSAA improvements basing on xdk-3911 behaviour
Cxbx-Reloaded/Cxbx-Reloaded pull request #1978
Opened 2020-10-08 20:02 UTC by CookiePLMonster

Introduces those changes to MSAA scaling:

* Scaling should be performed on `Clear` calls too.
* Scaling factors should be recalculated when binding a render target, and should be derived from multisampling type only when binding the back buffer.

The code contains a code path checking for `X_D3DMULTISAMPLE_SAMPLING_MULTI` sampling type and divides scaling by 2 if that is the case. **This is how xdk-3911 runtime does it**, but it seems to result in half-width rendering at the moment (possibly due to something else assuming that multisampling and supersampling are the same), so I left it commented out. It can be re-enabled once that issue is identified.

2020-10-09 20:25 UTC, CookiePLMonster commented
Rebased on the latest master to fix a "regression", which was an unrelated bug uncovered by this PR. Should avoid some potential other false positives when testing the relevant changes.

2020-10-11 19:55 UTC, PatrickvL requested changes

2020-10-11 19:55 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	HostViewPort.Width *= (DWORD)g_Xbox_MultiSampleXScale;
Review note, also discussed in discord: Since the scales are floating point, all multiplications over ordinal values should done by casting to floating point first and cast back to ordinal after the multiplication

2020-10-11 19:55 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        rect.x1 = static_cast<LONG>(pRects->x1 * g_Xbox_MultiSampleXScale * g_RenderScaleFactor);
Ditto

2020-10-11 19:55 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
> +const int X_D3DMULTISAMPLE_YSCALE_MASK                             = 0x000F;
Could you please add a rationally in comments on why these masks are now set to 0xF, because as far as I remember, the maximum scale Xbox supports uses 2 bits maximum?

2020-10-11 20:09 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        rect.x1 = static_cast<LONG>(pRects->x1 * g_Xbox_MultiSampleXScale * g_RenderScaleFactor);
This one is fine, since `g_Xbox_MultiSampleXScale` is a float everything will be promoted to a float - hence the cast :)

2020-10-11 20:10 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbD3D8Types.h
> +const int X_D3DMULTISAMPLE_YSCALE_MASK                             = 0x000F;
The MSAA scale computation from xdk-3911 as well as whatever XDK KoToR uses have this as their baseline for scaling:
```cpp
    v3 = (double)((unsigned __int8)g_Xbox_MultiSampleType >> 4);
    v1 = (double)(g_Xbox_MultiSampleType & 0xF);
```

2020-10-11 21:54 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
> +const int X_D3DMULTISAMPLE_YSCALE_MASK                             = 0x000F;
With all due respect, that code doesn't necessary imply all 4 bits are meant to be used. From what I remember, 3 was the maximum. But if we can find a test case that exceeds 2 bits, and your wider mask produces better results than the old 2 bits mask, then we'd have proof. So, maybe a test case could be added for scales above 3?

2020-10-11 21:55 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        rect.x1 = static_cast<LONG>(pRects->x1 * g_Xbox_MultiSampleXScale * g_RenderScaleFactor);
Ah, implicit behaviour - those are the best ;)

2020-10-12 07:48 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbD3D8Types.h
> +const int X_D3DMULTISAMPLE_YSCALE_MASK                             = 0x000F;
Test case sounds good! Will add a `scaleX > 3.0f || scaleY > 3.0f` test case.

2020-10-12 18:26 UTC, CookiePLMonster commented
Test case added, made scaling calculated on floats where applicable. As far as I can tell all instances of scaling are now covered.

2020-10-13 06:32 UTC, PatrickvL approved these changes
Nicely done, thanks!

2020-10-14 20:49 UTC, merged