Make RDTSC and ACPI timers stateful to fix overflows
Cxbx-Reloaded/Cxbx-Reloaded pull request #1985
Opened 2020-10-11 16:01 UTC by CookiePLMonster

**This PR needs some testing. Pay close attention to games running too slow or too fast with those changes.**

Stateless RDTSC and ACPI timers were ticking relative to the host QPC and multiplied to nanoseconds. This resulted in values so huge they would overflow since 20-30 minutes.

Introducing state allows to multiply to nanoseconds only over a delta value, which should be reasonably small in almost call cases.

I also proofed these calculations against data races by putting them under a mutex, but I only lock it if "Run Xbox threads on all cores" is enabled. Without this hack it **should** not be required.

2020-10-11 17:04 UTC, PatrickvL requested changes

2020-10-11 17:04 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlKe.cpp
> +static uint64_t NativeToXbox_FactorForRdtsc;
Since these are checked against zero, and there's currently only one function that does an assignment, it's probably best to initialise these variables to zero.

2020-10-11 17:16 UTC, CookiePLMonster commented on src/core/kernel/exports/EmuKrnlKe.cpp
> +static uint64_t NativeToXbox_FactorForRdtsc;
Done!

2020-10-11 19:46 UTC, PatrickvL submitted a review, later dismissed
LGTM, thanks.

Once enough testing has been done and no regressions (and possibly some improvements) have been reported in here, it's good to merge.

2020-10-12 05:57 UTC, literalmente-game commented
Tested (with no changes):
- Arctic Thunder
- Castlevania - Curse Of Darkness
- Constantine
- Darkwatch
- Dino Crisis 3
- Doom 3
- Fatal Frame
- Lotus Challenge
- Silent Hill 2
- Teen Titans

Not tested yet (but could be probably fixed by this PR):
- Total Overdose (needs to be tested 1+ hour to be sure anything actually improved)

2020-10-12 10:52 UTC, CookiePLMonster commented on src/core/kernel/exports/EmuKrnlKe.cpp
> +		auto lock = LockIfNeeded(RdtscLock);
Note to self, it needs to lock even when the hack is disabled because a context switch can happen here. Consider doing it lock-free.

2020-10-12 16:28 UTC, CookiePLMonster commented
As discussed on Discord, made the mutex lock at all times, since even without the multicore hack context switch could happen in the middle of the function.

2020-10-12 22:14 UTC, literalmente-game commented
Retested:
- Arctic Thunder: no changes
- Castlevania - Curse Of Darkness: no changes
- Constantine: no changes
- Darkwatch: no changes
- Dino Crisis 3: no changes
- Doom 3: no changes
- Fatal Frame: no changes
- Lotus Challenge: no changes
- Silent Hill 2: no changes
- Teen Titans: didn't changed, crashed at the same point

Newly tested:
- GTA 3: improved. Latest known behavior was some visual issues covering the entire screen after being in-game between 20 and 40 minutes. Game was just tested for 2 hours without being able to repro said issue. Bad news: game crashed ("Sofware stopped working") anyway, but now probably related to something else.

Not tested yet (but could be probably fixed by this PR):
- Aliens vs Predator Extinction (always freezes after some time)
- Mafia (reportedly it freezes after some time)
- Total Overdose (needs to be tested 1+ hour to be sure anything actually improved)
- GTA Vice City (reportedly it freezes after some time)

2020-10-13 06:34 UTC, PatrickvL approved these changes

2020-10-13 10:24 UTC, CookiePLMonster commented
Idea - calculations could be reduced to further reduce the likelihood of overflow by dividing the factors by `GCD(1000000000, NativeToXbox_FactorForRdtsc);` and `GCD(1000000000, NativeToXbox_FactorForAcpi);`. In my test it yields 1 for rdtsc and 2 for acpi, but I don't see any reason not to go for it anyway - thoughts?

2020-10-13 11:00 UTC, PatrickvL commented
Adding more complexity for just one more bit looks not really worth the effort. Creative thinking though.

2020-10-13 18:16 UTC, merged