Miscellaneous Direct3D LTCG fixes
Cxbx-Reloaded/Cxbx-Reloaded pull request #2022
Opened 2020-10-30 22:26 UTC by CookiePLMonster

**This PR needs testing with LTCG games, mainly those having a `Direct3D_CreateDevice_16` symbol!**

Marking as draft for now because this PR depends on https://github.com/Cxbx-Reloaded/XbSymbolDatabase/pull/121 and https://github.com/Zeex/subhook/pull/50. Once both are merged, I'll fixup this PR to point at the actual merge commits and un-draft.

A next batch of Direct3D fixes targeted at LTCG games:
* Patches `D3DDevice_SetRenderTarget_0` properly and accounts for a "CreateDevice did not call SetRenderTarget" test case - now this case only calls an internal implementation function, rather than trampolining to (sometimes non-existant) guest function.
* Patches `D3D_CommonSetRenderTarget` as a possibly recursive patch (called by `SetRenderTarget`). Even though it's an internal D3D function, some games (my test case: **Midtown Madness 3**) call it directly, presumably due to code inlining.
* Fixes `D3DDevice_SetPixelShader_0` corrupting the stack pointer. This is likely the reason which made **Metal Wolf Chaos** crash when using a Debug version of the emulator.
* Refactors all LTCG variations of `Direct3D_CreateDevice` - using naked functions where applicable and splitting `CreateDevice_16` into two separate functions, as OOVPAs matched the same symbol to functions with different calling conventions; we now properly preserve and pass arguments those functions, which may improve games using this symbol. For the sake of readable logs (and because naked functions cannot contain objects on their stack), I have created private overloaded functions with same names as the patch functions and placed the logging functions there. The end result are logs indistinguishable from the case where logging functions reside straight in the patch function.
* Implements `D3DDevice_DeleteVertexShader_0`. This untested function was forwarding to a non-LTCG function and thus promptly crashing, because a non-LTCG trampoline of course does not exist. Now it calls the internal function followed by its own trampoline.
* Bonus nitpick: `D3DDevice_Swap` was leaking a backbuffer handle. It's unlikely to change anything (it's a backbuffer after all), but it's also an one-line fix.

2020-10-30 22:31 UTC, RadWolfie commented on src/core/hle/Patches.cpp
> +	PATCH_ENTRY("D3D_CommonSetRenderTarget", xbox::EMUPATCH(D3D_CommonSetRenderTarget), PATCH_HLE_D3D),
This line should be move above D3D_BlockOnTime's patch entry. We're using alphabet order by the way.

2020-10-30 23:13 UTC, ESPPIRAL commented
Improved

![image](https://user-images.githubusercontent.com/29869781/97764117-de1e8900-1b0d-11eb-876f-b712c2515cc8.png)

2020-10-31 10:49 UTC, CookiePLMonster commented
subbook PR has been merged to upstream and I updated the PR to point at the merge commit.

2020-10-31 12:50 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +		LOG_FUNC_ARG(ppReturnedDeviceInterface)
Note to self: Turn those into `LOG_FUNC_ARG_OUT`.

2020-10-31 13:49 UTC, CookiePLMonster commented
Fixed rebase errors and slightly improved logging.

2020-11-01 05:05 UTC, gandalfthewhite19890404 commented
World Series Baseball 2k3 now able get to menus, with flickering screen so if you have epilepsy - be careful:
<details>

![image](https://user-images.githubusercontent.com/24764335/97795561-48741e00-1c21-11eb-9eb5-6b8c7b7086b3.png)
</details>

2020-11-01 07:40 UTC, gandalfthewhite19890404 commented
I have found another title: **Pro Race Driver**.
Master recognized Direct3D_CreateDevice_16 = 0x1f9200
and it will crash with this
`Received Exception Code 0xC0000005 @ EIP := 0x001F92A0(=Direct3D_CreateDevice_16+0xa0)`

PR2022 recognized Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface = 0x1f9200
and it will crash with this
`Received Exception Code 0xC0000005 @ EIP := 0x6F2116D3`

Here is PR2022 logfile with debug level for d3d8 functions - 
[KrnlDebug_PRD1.zip](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/5470342/KrnlDebug_PRD1.zip)

2020-11-02 10:00 UTC, CookiePLMonster commented
Note to self - subhook has a new version, since we need to update the submodule either way update it to v0.8 before un-drafting!

2020-11-02 11:05 UTC, literalmente-game commented
Kelly Slater's Pro Surfer
Master: crashes
PR: reaches in-game
Symbol cache (PR): [Kelly Slater's Pro Surfer-637751d7.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/5474338/Kelly.Slater.s.Pro.Surfer-637751d7.txt)

2020-11-02 11:55 UTC, CookiePLMonster commented
Both submodule PRs are now merged, so this PR is ready for review/merge.

2020-11-02 13:09 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface(Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
If the `if(g_bPrintfOn)` check can be moved into a `LOG_CHECK_ENABLED_EX`, then a bit of overhead could be prevented by inserting `LOG_CHECK_ENABLED(LOG_LEVEL::DEBUG)` before the logging call, which makes it more clear the call is a logging call anyway, so the `// Log` comment line can be left out as well.

2020-11-02 13:11 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +xbox::void_xt D3DDevice_SetPixelShaderCommon(xbox::dword_xt Handle)
Better rename this into `CxbxImpl_SetPixelShader`

2020-11-02 13:13 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +xbox::void_xt D3DDevice_SetPixelShaderCommon(xbox::dword_xt Handle)
(unless you want to keep the name for logging purposes, but then warn against renaming via a comment that describes WHY the name is specifically chosen this way.)

2020-11-02 13:13 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface(Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
Function call overhead is negligible especially since the compiler is free to come up with a custom calling convention, but a valid point nonetheless.

2020-11-02 13:15 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +xbox::void_xt D3DDevice_SetPixelShaderCommon(xbox::dword_xt Handle)
I didn't put much thought into it, just noticed a `noinline` statement which was likely a workaround to some past bug and now is just noise.

2020-11-02 13:17 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +static void D3DDevice_SetRenderTarget_0_Inner
Perhaps the `_Inner` suffix can be dropped to avoid logging confusion? (There'll be no naming conflict, because the other is wrapped in a `EMUPATCH` macro.)

2020-11-02 13:19 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +static void D3DDevice_SetRenderTarget_0_Inner
Good idea, I handled the other cases but missed this one. Even without the `EMUPATCH` macro there would be no conflict because of different amount of arguments :)

2020-11-02 13:21 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface(Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
With me being unfamiliar with the logging system, how do you suggest this to be fixed?

2020-11-02 13:23 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	LOG_FUNC_ONE_ARG(Handle);
The `CxbxImpl_` prefix will show up in the log; Not sure we should fix/avoid that by jumping through hoops (like done above), but perhaps there's a solution that can avoid this issue entirely? Perhaps a change to the `LOG_INIT` macro that allows a custom function name replacing `__func__`?

2020-11-02 13:24 UTC, PatrickvL requested changes
Some thoughts on logging. Otherwise again great work!

2020-11-02 13:34 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface(Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
In Logging.h, change :
```
#define LOG_CHECK_ENABLED_EX(cxbxr_module, level) \
	if (g_EnabledModules[to_underlying(cxbxr_module)] && to_underlying(level) >= g_CurrentLogLevel)
```
into 
```
#define LOG_CHECK_ENABLED_EX(cxbxr_module, level) \
	if (g_bPrintfOn && g_EnabledModules[to_underlying(cxbxr_module)] && to_underlying(level) >= g_CurrentLogLevel)
```

and change:
```
#define LOG_FUNC_BEGIN_NO_INIT \
	do { if(g_bPrintfOn) { \
```
into 
```
#define LOG_FUNC_BEGIN_NO_INIT \
	do { { \
```

then, in here, change : 
```
	// Log
	Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface(Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
```
into 
```
	LOG_CHECK_ENABLED(LOG_LEVEL::DEBUG)
		Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface(Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
```

Optionally, in Logging.h introduce : 
```
#define IF_LOG_ENABLED() LOG_CHECK_ENABLED(LOG_LEVEL::DEBUG)
```
Then it can become :
```
	IF_LOG_ENABLED()
		Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface(Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
```

2020-11-02 16:58 UTC, CookiePLMonster commented
Applied all review comments except for the one we discussed on Discord which I consider too risky for this PR.

2020-11-02 17:32 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	Direct3D_CreateDevice_16__LTCG_eax_BehaviorFlags_ecx_ppReturnedDeviceInterface(Adapter, DeviceType, hFocusWindow, BehaviorFlags, pPresentationParameters, ppReturnedDeviceInterface);
Let's shelve this for later

2020-11-02 17:35 UTC, PatrickvL approved these changes
Splendid!

2020-11-02 17:36 UTC, merged

2020-11-17 14:59 UTC, gandalfthewhite19890404 commented
Lord of the Rings The Third Age crashes since PR was merged.