Misc fixes after the vertex declaration changes
Cxbx-Reloaded/Cxbx-Reloaded pull request #2031
Opened 2020-11-15 20:43 UTC by CookiePLMonster

This PR fixes a few regressions after the vertex declaration changes have been merged:

* Fixes `D3DDevice_SetVertexShader_0` not calling to a trampoline - after recent changes calling to guest code here became instrumental for correct rendering but only the non-LTCG variation had a trampoline.
* Fixes `X_VERTEXSHADER_FLAG_PROGRAM` flag for xdk-3948. In this XDK version the flag appears to have a value of 4, not 16. Adjusted the code accordingly and added test cases to verify that assumption, also removed the previous test case (with a xdk-3948 game as a case), because now we have a more specific test case added instead.
* Fixes a merge error in `CxbxImpl_SetViewPort` - causing `X`/`Y` values to be multiplied by MSAA scaling twice.

Fixes regressions in **NASCAR Heat 2002**, revealing that the vertex declaration changes helped this game a lot, fixing shadowing issues and making self-shadowing work correctly!
![image](https://user-images.githubusercontent.com/7947461/99196242-7746d400-278b-11eb-8c99-72f4c5e77614.png)

2020-11-15 20:44 UTC, LukeUsher commented
nice find! Excellent work, as always

2020-11-15 20:45 UTC, LukeUsher requested changes
just a minor indentation fix, otherwise good

2020-11-15 20:45 UTC, LukeUsher commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	CxbxVertexShaderSetFlags();
Indenting seems off here

2020-11-15 20:48 UTC, PatrickvL submitted a review, later dismissed
LGTM

2020-11-15 20:50 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> -			// Test-case : Amped
Perhaps mention this removed test-case above, near `LOG_TEST_CASE("Unknown vertex shader flag")`

2020-11-15 20:51 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	if (pXboxVertexShader->Flags & g_X_VERTEXSHADER_FLAG_PROGRAM) {
Perhaps refer to `CxbxVertexShaderSetFlags` here (otherwise someone might think this is a typo)

2020-11-15 20:53 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbVertexShader.cpp
> -			// Test-case : Amped
I don't think it's necessary, as it's effectively the same test case, but more specific.

2020-11-15 21:05 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> -			// Test-case : Amped
Sure. Maybe we should try to get confirmation that Amped won't trigger the non-valid check now ;)

2020-11-15 21:06 UTC, LukeUsher approved these changes

2020-11-15 21:07 UTC, medievil1 commented
fixes NFS HP2 (EA 040 V1.02) rearview mirror and I think road shadows looks better, car road shadows look inverted though, lighter where they should be darker, darker where they should be lighter 
![image](https://user-images.githubusercontent.com/38597905/99196800-9a0dc400-275c-11eb-9544-7d6371cf4b11.png)

2020-11-15 21:07 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbVertexShader.cpp
> -			// Test-case : Amped
I don't see how it would - in order to hit this code path `X_VERTEXSHADER_FLAG_PROGRAM` **has to** be false (so our new test case will **not** trigger). Therefore, it behaves the same way as NASCAR Heat 2002 does, both titles using an old enough XDK.

2020-11-15 21:13 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> -			// Test-case : Amped
Right. I had to wrap my head around the set/unset bits. No verification needed, indeed.

2020-11-15 21:14 UTC, PatrickvL approved these changes

2020-11-15 21:20 UTC, escape209 commented
Fixes shadows in Tony Hawk's Pro Skater 2X (previously invisible)
![image](https://user-images.githubusercontent.com/8225831/99197106-50d36980-2788-11eb-97b9-446d265afd1e.png)

2020-11-15 21:20 UTC, merged

2020-11-29 14:05 UTC, ObiKKa commented
> This PR fixes a few regressions after the vertex declaration changes have been merged:
The original poster above is alluding to PR #1894 created on May 9, 2020 by both PatrickvL and NZJenkins together (The sole commit in the PR seems to have come from a rebase, but there was an older list of many commits by both coders.). It had been in draft stage for a few months and was then merged by Luke Usher on November 15, 2020.

Sorry to bump this thread up.