Improve viewport calculations
Cxbx-Reloaded/Cxbx-Reloaded pull request #2033
Opened 2020-11-16 08:59 UTC by NZJenkins

- Track the backbuffer scale
- SetViewport tracks the Xbox viewport values instead of setting the viewport
so we can calculate what we need from them
- Rework GetViewportOffsetAndScale
- Vertex shader programs do not depend on D3D9 viewport to transform verts

Closes #1927

2020-11-16 09:17 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos.y *= -1;
Flipping Y could be done on CPU, by flipping the sign of the `.y` component of the `xboxViewportScaleInverse` constant

2020-11-16 09:23 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> -	HRESULT hRet = g_pD3DDevice->SetViewport(&HostViewPort);
If this was the last appearance of host `SetViewport()`, should or shouldn't that still be done once, in `Direct3D_CreateDevice_End` for instance?

2020-11-16 09:24 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> -	HRESULT hRet = g_pD3DDevice->SetViewport(&HostViewPort);
Nevermind - I see there's a new call to host SetViewport below...

2020-11-16 09:24 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	// We don't have a fixed function shader so we rely on D3D9 fixed function mode
(yet)

2020-11-16 09:28 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +		g_pD3DDevice->SetViewport(&hostViewport);
Okay, so when Fixed Function HLSL is completed, this bit of code /should/ go to `Direct3D_CreateDevice_End`, right? Or can `HostRenderTarget_Width` and/or `HostRenderTarget_Height` change over time? Then maybe it couldd be worthwhile to see if we could update vertex shaders such, that host viewport would always stay the same (even when render target dimensions change), if that's possible?

2020-11-16 09:30 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShader.cpp
> +	oPos.y *= -1;
Flipping Y could be done on CPU, by flipping the sign of the .y component of the xboxViewportScaleInverse constant

2020-11-16 09:31 UTC, PatrickvL reviewed
A few considerations & questions

2020-11-16 10:26 UTC, PatrickvL commented
Before, current master :
![image](https://user-images.githubusercontent.com/461930/99241674-7602bf00-27fe-11eb-98f0-59c1e0c081f1.png)
After : 
![image](https://user-images.githubusercontent.com/461930/99241709-83b84480-27fe-11eb-82f7-5c309003492e.png)

2020-11-16 16:32 UTC, escape209 commented
This fixes some 2D elements being missing in SpongeBob SquarePants: Battle for Bikini Bottom.

2020-11-16 17:38 UTC, mzji commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	https://docs.microsoft.com/en-us/windows/win32/direct3d9/viewports-and-clipping
Lacks of `//`

2020-11-16 17:40 UTC, gandalfthewhite19890404 commented
### Improvements:
**Black** now renders graphics - FMVs and actual gameplay.

2020-11-17 05:36 UTC, gandalfthewhite19890404 commented
### Regressions:
**Loons: The Fight for Fame** crashed with Unknown primitive pop-up fatal error. BUT I tried latest master - it does not crashed, so I decided to test 2033 again to get error screenshot and it does not crashed. Why?
With PR game looks much worse - missing graphics and exploded polygons:
![image](https://user-images.githubusercontent.com/24764335/99350672-634cc080-28b8-11eb-816d-48f87d1edf2f.png)


PS
should I edit previous post or I may just add them?

2020-11-17 05:41 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos.y *= -1;
yes, I can't remember why I made a point of doing it separately here
though AFAIK it should be optimized away since it is constant over the render, same with the inverse thing 🤷‍♂️ 

Viewport isn't really an accurate description of this variable now.
I'm thinking update the name to `xboxScreenspaceScale/Offset` or something, and remove the inverse so we can easily read what we thought the render target width/height was for debuggability?

2020-11-17 05:49 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +		g_pD3DDevice->SetViewport(&hostViewport);
I don't know what the significance of `Direct3D_CreateDevice_End` is

`ValidateRenderTargetDimensions` implementation suggests the rendertarget size can change at any time
I removed one of the calls to it so need to add that back in
I guess in `UpdateNativeD3DResources` makes the most sense, so the viewport stuff will probably have to stay there

2020-11-17 05:50 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	https://docs.microsoft.com/en-us/windows/win32/direct3d9/viewports-and-clipping
nice catch

2020-11-17 07:53 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos.y *= -1;
These variables don't even contain Xbox screenspace directly, they contain the adjustments so that output becomes normalized (and converted from OpenGL to Direct3D orthogonality).

As for the multiplication by inverse instead of a division, wasn't that also to retain accurately?

2020-11-17 09:01 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos.y *= -1;
True it's not screenspace.
It is the rendertarget "space" not including subpixels (but because rendertarget sizes are larger when using subpixel MSAA it is a bit confusing?)
Yes we just want to normalize all the things...`xboxNormalizingScale`? idk
Uh I don't remember I thought I just read somewhere divisions should be avoided (but since it is a constant I don't think it matters)

2020-11-17 10:25 UTC, medievil1 commented
ummm... KOTOR (LA-003 V1.9526529) menu is kinda jacked...lol
![image](https://user-images.githubusercontent.com/38597905/99378196-2a4f2480-2895-11eb-9645-113ceb9c5049.png)

2020-11-17 11:30 UTC, NZJenkins commented
Fixed KOTOR and rebased on master
But found some issues with samples which need investigation

2020-11-17 11:35 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos.y *= -1;
added some helper functions that calculate various dimensions side-by-side, hopefully that makes it clearer what the differences are

2020-11-17 12:33 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	g_pD3DDevice->SetVertexShaderConstantF(CXBX_D3DVS_IS_RHW_TRANSFORMED_POSITION_BASE, isRHWTransformedPosition, CXBX_D3DVS_IS_RHW_TRANSFORMED_POSITION_SIZE);
Because `xboxIsRHWTransformedPosition` is removed from HLSL, this `CXBX_D3DVS_IS_RHW_TRANSFORMED_POSITION_BASE` constant seems no longer needed...

2020-11-17 12:37 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +void GetRendertargetOutputDimensions(float& x, float& y) {
nit : uppercase T : Render**T**arget

2020-11-17 12:39 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	vScale[1] = -scaledHeight / 2;
Please add a comment about intentional Flipping of Y here (and perhaps also explain why)

2020-11-17 12:42 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +		g_pD3DDevice->SetViewport(&hostViewport);
It seems that for now, host Viewport must change along with RenderTarget dimensions. Optimizing this update to happen only when it changes can be done later.

2020-11-17 12:43 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
>  #define CXBX_D3DVS_IS_RHW_TRANSFORMED_POSITION_BASE (CXBX_D3DVS_TEXTURES_SCALE_BASE + CXBX_D3DVS_TEXTURES_SCALE_SIZE)
`CXBX_D3DVS_IS_RHW_TRANSFORMED_POSITION_BASE` can be removed (see above)

2020-11-17 12:45 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos /= xboxNormalizeScale;
Debugging advantage aside, replacing this divide by a multiplication of the inverse scale would avoid division by zero.

Also, didn't Silent/CookieMonster submit a PR on this very calculation a while ago about accuracy?

2020-11-17 12:47 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos.y *= -1;
Nice, thanks.

2020-11-17 12:48 UTC, PatrickvL requested changes
A few remarks, still ;)

2020-11-17 15:55 UTC, gandalfthewhite19890404 commented
Mafia (map and letters) and Pirates of a Caribbean(dialogues) are fixed now.

2020-11-17 21:47 UTC, MrDinkle commented
Mortal Kombat: Deception and Mortal Kombat: Armageddon now both render all of the ui-related elements correctly.
<details>
[CXBX_Deception](https://user-images.githubusercontent.com/43343017/99454467-72516400-28f4-11eb-8c6c-c9753a4971e6.PNG)

[CXBX_Armageddon](https://user-images.githubusercontent.com/43343017/99454464-71b8cd80-28f4-11eb-8ab8-1f2ad6a75f44.PNG)
</details>

2020-11-18 05:18 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos /= xboxNormalizeScale;
we still would divide by zero, just not as part of the shader
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2005 got clobbered by #1894 I believe

2020-11-18 05:49 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	vScale[1] = -scaledHeight / 2;
I don't know why.. it is what the XDK (and D3D9) does, isn't it just a convention?

2020-11-18 15:37 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float isRHWTransformedPosition[4] = { 0 };
`isRHWTransformedPosition` can also be removed

2020-11-18 15:37 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +		isRHWTransformedPosition[0] = 1.0f;
`isRHWTransformedPosition` can also be removed

2020-11-18 15:49 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos /= xboxNormalizeScale;
Indeed - and my conflict resolve is to blame for that;

As for what was done in #2005, it's comment (which is still present a few lines up) read :
````
 	// oPos.w and xboxViewportScale.z might be VERY big when a D24 depth buffer is used
	// and multiplying oPos.xyz by oPos.w may cause precision issues.
	// Pre-divide them to help keep the values reasonably small.
	// Test case: Burnout 3
````
And it did this by changing this old code :
````
	oPos.xyz *= oPos.w; // reverse perspective divide
	oPos.xyz /= xboxViewportScale.xyz; // reverse scale
````
Into this alternative :
````
	float3 divisor = xboxViewportScale.xyz / oPos.w;
	oPos.xyz /= divisor; // reverse scale and perspective divide
````

So, is appears that the division you now have here might avoid the precision issue as well (assuming that your `xboxNormalizeScale` divisor has the same accuracy when now pre-calculated on CPU compared to the GPU accuracy of the `divisor` in #2005).

Perhaps someone could confirm Burnout 3 is still fine with this PR?

2020-11-18 16:06 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	vScale[1] = -scaledHeight / 2;
Just add a comment stating : `// Flip Y to convert Xbox (OpenGL) to our D3D coordinate system` or something along those lines.

2020-11-18 20:09 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos /= xboxNormalizeScale;
![image](https://user-images.githubusercontent.com/38597905/99582353-016f8200-29b0-11eb-848b-7b444f813cfd.png)

2020-11-18 20:15 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos /= xboxNormalizeScale;
![image](https://user-images.githubusercontent.com/38597905/99583040-ecdfb980-29b0-11eb-94cf-f595d8e7b635.png)

2020-11-18 20:56 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos /= xboxNormalizeScale;
whatever's on top doesn't clear though....tracers left behind 
![image](https://user-images.githubusercontent.com/38597905/99587101-9a090080-29b6-11eb-9db9-843ad0455c9d.png)

2020-11-18 21:31 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos /= xboxNormalizeScale;
Thanks @medievil1! @CookiePLMonster confirmed on discord that this is how Burnout 3 looked before for him as well :
    good menus and UI, black screen in races because of them using an inlined IVB to "blit" it
So, this confirms this has not regressed.
Closing discussion.

2020-11-20 09:27 UTC, CookiePLMonster commented
Fixes cut off menus in DRIV3R:

Before:
![image](https://user-images.githubusercontent.com/7947461/99783695-07ce3d00-2b1b-11eb-93b8-e2630967fb10.png)

After:
![image](https://user-images.githubusercontent.com/7947461/99783538-d3f31780-2b1a-11eb-84e5-67b453f879ce.png)

2020-11-21 10:37 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	vScale[1] = -scaledHeight / 2;
Note in this code, _we_ are not flipping Y, it is what the XDK does. Ideally we are not doing anything here, since we want to match XDK behaviour.
It is the same as is documented in D3D9 so I don't think it's of note or there's anything much to add

Will comment to make it clearer that we are just imitating XDK, and we should be getting this from NV2A LLE instead

2020-11-21 10:59 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	oPos.y *= -1;
I flip-flopped back to calling it screenspace because I couldn't think of a good name 😖

2020-11-21 10:59 UTC, NZJenkins commented
Have fixed up some issues with antialias and backbuffer scale samples and rolled it into one commit.
Tossed up creating a new PR but just left it in here...

2020-11-21 11:51 UTC, PatrickvL approved these changes
LGTM!

2020-11-21 12:37 UTC, merged