Add warning to deprecated CI ymls
Cxbx-Reloaded/Cxbx-Reloaded pull request #2072
Opened 2020-12-11 10:10 UTC by Margen67

2020-12-11 11:40 UTC, RadWolfie commented
You are aware it will affect people using non-github hosting site? Such as GitLab, GitBucket, etc. Or perhaps any of us decide to move to different hosting site. imho, output a message of deprecated CI ymls aren't worth it. Plus other hosting site can act as a mirror as well.

2020-12-11 20:57 UTC, Margen67 commented
> 
> 
> You are aware it will affect people using non-github hosting site? Such as GitLab, BitBucket, etc. Or perhaps any of us decide to move to different hosting site. imho, output a message of deprecated CI ymls aren't worth it. Plus other hosting site can act as a mirror as well.

They're not maintained so if we absolutely have to keep them we should at least add a disclaimer.

2020-12-20 13:00 UTC, RadWolfie requested changes

2020-12-20 13:00 UTC, RadWolfie commented on .azure-pipelines.yml
> +    displayName: 'Deprecation warning'
I suggest rename title to "Third-Party CI Warning" or the like.

2020-12-27 00:07 UTC, RadWolfie approved these changes

2020-12-27 00:08 UTC, merged