Reduce the amount of work done per draw
Cxbx-Reloaded/Cxbx-Reloaded pull request #2123
Opened 2021-01-17 07:35 UTC by NZJenkins

Certain titles split geometry into many small sections, and do a huge number of draws per frame
These are some optimizations and tweaks to code that runs per-draw

Significantly increases performance in Crash Nitro Kart

2021-01-17 10:21 UTC, CookiePLMonster reviewed
Just a few nitpicks. I haven't tested it yet, but the changes look exciting! I'll be happy not to see all those redundant texture state sets in PIX captures too, so that change also improves debuggability.

2021-01-17 10:21 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	if (g_IndexBufferCache.size() > 10000) {
Since you're changing it, I suggest changing it to a `static constexpr size_t INDEX_BUFFER_CACHE_SIZE = 10000;` somewhere on top of this file, just to have it readily available.

2021-01-17 10:21 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +PreviousState PreviousStates[xbox::X_D3DTS_STAGECOUNT][xbox::X_D3DTSS_LAST + 1] = {};
I believe you want a `std::optional<DWORD>` here, since that'll allow for values "not to exist".

2021-01-17 10:21 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	auto curToken = (uint32_t*)pXboxFunction;
casting away constness is meh. Recommend `reinterpret_cast<const uint32_t*>(pXboxFunction);` instead.

2021-01-17 10:21 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	uint32_t* pCurToken = (uint32_t*)((uintptr_t)pXboxFunction);
A double typecast is most likely redundant here.

2021-01-17 10:34 UTC, CookiePLMonster commented
Brings a big speedup to **NASCAR Heat 2002** - I wasn't even aware previously that it's a 60 FPS game.

Master:
![image](https://user-images.githubusercontent.com/7947461/104837888-e8a02180-58b7-11eb-9c8b-23861057c344.png)

PR:
![image](https://user-images.githubusercontent.com/7947461/104837892-eccc3f00-58b7-11eb-81dc-96e603800359.png)

**Outrun 2** now has much better framerates:
![image](https://user-images.githubusercontent.com/7947461/104837896-f786d400-58b7-11eb-8539-fa22ae589350.png)

2021-01-17 10:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +PreviousState PreviousStates[xbox::X_D3DTS_STAGECOUNT][xbox::X_D3DTSS_LAST + 1] = {};
Additional benefit of `std::optional` - comparing `optional == value` will always return false if optional doesn't have a value, so the check below can be simplified to a simple equality check and it'll implicitly check for presence of a value.

2021-01-17 11:48 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShader.cpp
> -
Not having this version check anymore, makes one wonder : Are we going to forget about it, is there still other code mentioning it, or do we need to create an issue on the matter?

2021-01-17 11:50 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> +		EmuLog(LOG_LEVEL::WARNING, "Empty vertex shader");
If this is the only code left (rudimentary) recognizing state shaders and/or other unsupported versions, than indeed a LOG_TEST_CASE is needed, mentioning what versions should be handled later on.

2021-01-17 11:52 UTC, PatrickvL requested changes
Great work! Relatively little code changed, but with significant results, congrats!

Please do address the review remarks, and then it'll quickly be good to get merged!

2021-01-17 12:05 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +            auto lastState = &PreviousStates[XboxStage][State];
I'm not entirely sure our cached state will always reflected the actual host D3D state. There's a significant change host states could change by calls to SetRenderTarget, Clear, and possibly others.

So perhaps as detection code first to see if that indeed happens? (Detection is simply a compare between your cached value and the result of a call to host GetTexture[Sampler]State.)

Then, if internal changes are indeed detected, we can decide to either always compare against host state, or to use your cache but add case-specific host checks alongside it.

Or, we discover host never changes states internally, ever, and then we learned something valuable too ;)

2021-01-17 18:59 UTC, ObiKKa commented
...
> **Outrun 2** now has much better framerates:
...

Can you please mention your PC CPU & system memory specifications used for testing these games?

2021-01-17 23:48 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +PreviousState PreviousStates[xbox::X_D3DTS_STAGECOUNT][xbox::X_D3DTSS_LAST + 1] = {};
Nice that's exactly what's needed

2021-01-18 05:59 UTC, NZJenkins commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	auto curToken = (uint32_t*)pXboxFunction;
Can reinterpret_cast make a difference or it's style?

2021-01-18 06:24 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +            auto lastState = &PreviousStates[XboxStage][State];
I didn't see an indication of that in the docs?
If nothing's in the docs we may as well just wait for something to go wrong instead imo and save the churn

Previous states should probably be a class variable here - since the device can be recreated, then they might go out of sync

2021-01-18 07:09 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> +		EmuLog(LOG_LEVEL::WARNING, "Empty vertex shader");
Unless I'm misreading it the headers are consumed here now
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/master/src/core/hle/D3D8/XbVertexShader.cpp#L1376-L1404

2021-01-18 11:37 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	auto curToken = (uint32_t*)pXboxFunction;
Style - I'm not as worried about a C style cast as I am about casting away constness.

2021-01-18 11:39 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +            auto lastState = &PreviousStates[XboxStage][State];
States will definitely desync on device reset, but we don't do that. Other than that indeed, might be a good idea to clear those on device creation to have the states sync with possible device recreation during the process lifetime.

Regarding texture states, IIRC in OpenGL they bind to textures but in D3D they bind to slots, so I don't think we should be concerned about them "desyncing".

2021-01-18 11:48 UTC, RadWolfie commented on src/core/kernel/init/CxbxKrnl.h
> +// Which will make developers easier to note which applications has triggered quicker, easier, and doesn't require any individual log enabled to capture them.
Can you add the reason for the move back to CxbxKrnl.h? Such as CxbxKrnl_Xbe->m_szAsciiTitle is dependency to this, CxbxKrnl.h, file since common Logging.h file doesn't have any dependency.

2021-01-18 11:50 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> +#include "core/kernel/init/CxbxKrnl.h"
Also, did you tried include CxbxKnl.h first then Logging.h afterward?

2021-01-18 11:56 UTC, RadWolfie commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	auto curToken = (uint32_t*)pXboxFunction;
I for one rather avoid using C style and use C++ style. There's only little room in C++ standard to use C style under certain condition. The rest is better off using C++ style. Casting does have some difference between C and C++ by the way.

2021-01-18 12:44 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> +#include "core/kernel/init/CxbxKrnl.h"
It works including more than one header, but then you need to know to do that

2021-01-18 20:30 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +            auto lastState = &PreviousStates[XboxStage][State];
"The proof of the pudding, is in the eating", or : we won't know until we try.

I know for a fact that some Xbox D3D APIs change state, so it's not that far fetched to consider this might apply to host D3D as well.
Perhaps, we could extend the LOG_D3D_RESULT macro with a call to a state verification function, so that we can even see which host D3D API (if any) changes which state.

2021-01-19 10:46 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +            auto lastState = &PreviousStates[XboxStage][State];
IMO searching for undocumented D3D9 behaviour isn't a must have for the purposes of this PR - and if added in the most straightforward way during state updates, it would slow things down significantly

2021-01-19 10:48 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/VertexShader.cpp
> -
as mentioned in another comment the headers appear handled at the `LoadVertexShader`

2021-01-20 06:57 UTC, LukeUsher approved these changes

2021-01-20 08:54 UTC, PatrickvL approved these changes

2021-01-20 08:55 UTC, merged