Variant Update to Readme
Cxbx-Reloaded/Cxbx-Reloaded pull request #2130
Opened 2021-02-02 19:11 UTC by RadWolfie

Revise changelog
* Reword Wine being on Linux only to operating system as general.
* Update download link to official website's download page.

---
@Cxbx-Reloaded/developers, please discuss what other things need an update. Once team make agreement, feel free to update directly in this pull request.

I am granting permission to developers for any updates to this pull request whenever found something outdated or make review agreement to correct sentence/wording/whatever.

Also when there's nothing else need an update with full approval from most or all team members, last person remove draft status and merge it.

2021-02-03 11:31 UTC, RadWolfie commented
After Luke brought up about Ubuntu as debian-based operating system. I think it is best to have our own wiki page of Wine for easier update to know which operating system works and its requirement in order to work properly. One of an example would be Ubuntu (debian-based) will require:
```
sudo dpkg --add-architecture i386
sudo apt update
```

Although, I think I only did the first command on fresh install.

2021-03-12 10:49 UTC, ergo720 requested changes

2021-03-12 10:49 UTC, ergo720 commented on README.md
>      * **Wine users will need to use `CxbxReloaded-Release-VS2017.zip` for it to run correctly.**
Since we now know that vcrun2019 works as well, this line is no longer true and should either be deleted or at least updated to reflect this.

2021-03-12 11:02 UTC, LukeUsher requested changes

2021-03-12 11:02 UTC, LukeUsher commented on README.md
> +  * OS: Windows 7+ x64, or x86-64 operating system with Wine. 32-bit is not supported.
x86-64 operating system with Wine isn't strictly true: It specified Linux on purpose because Cxbx-R doesn't run on macOS using wine, and might have problems on BSD due to kernel/implementation differences (I haven't tested BSD yet), it is only confirmed working on Linux based systems.

We should keep this as "Linux" because we know other systems DO NOT work.

2021-03-12 11:02 UTC, LukeUsher commented on README.md
> +### OS with Wine (not officially supported by us)
I don't think this header needs to change, we can still just say "Wine", because in this case, Wine is the platform

2021-03-12 11:02 UTC, LukeUsher commented on README.md
>      * **Wine users will need to use `CxbxReloaded-Release-VS2017.zip` for it to run correctly.**
Fully agree

2021-03-14 17:42 UTC, RadWolfie commented on README.md
>      * **Wine users will need to use `CxbxReloaded-Release-VS2017.zip` for it to run correctly.**
While I do agree, although winetricks will need constant update for vcrun2019 binary changes over time. This type of instruction I'm not aware how to do so.

On the other news, Wine 6.3 (dev build) has implemented C2VectParallel at last! Which may likely become unnecessary for vcrun201(7|9) installation requirement. I should create a ticket for this as a reminder to do once Wine 6.3+ is release as stable.

2021-03-14 17:57 UTC, RadWolfie commented on README.md
> +  * OS: Windows 7+ x64, or x86-64 operating system with Wine. 32-bit is not supported.
I'll revert my edit and add a note below it. 👍

2021-04-23 20:50 UTC, PatrickvL submitted a review, later dismissed

2021-07-18 10:19 UTC, ergo720 commented
Superseded by https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2265

2021-07-18 15:27 UTC, ergo720 commented
@RadWolfie I added a new commit to address the review remarks.

2021-07-21 11:30 UTC, ergo720 approved these changes

2021-07-22 14:59 UTC, RadWolfie commented
Please do not convert to "ready for review" stage until whole team has read whole readme and approve current changes. This pull request is not the usual pull request that can be done by one or two members on the team.

Thanks

2021-07-22 16:37 UTC, RadWolfie commented
On Bug Reports section, I notice it is currently reference to our github's compatiblity repo proceedure. We need to update it for what need to be report in official website's compatibility webpage. Or say follow the proceedure on the website's compatibility report.

---

As for Special Thanks section, I believe we should mention our Xbox Kernel Test Suite's contributors for creating the tests and most likely made the fixes from Cxbx-Reloaded's codebase. Doing the HLE kernel codebase is heavy workload and a lot of effort. 😅

2022-01-23 08:55 UTC, RadWolfie commented on README.md
>      * **Wine users will need to use `CxbxReloaded-Release-VS2017.zip` for it to run correctly.**
Wine 7.0 stable came out about a week ago. So, we can update note to use VS2019 build. Not sure if Wine has VS2022 support or does not matter.

2022-03-31 23:37 UTC, ergo720 approved these changes

2022-03-31 23:37 UTC, merged