Tidy mip code and work around DXT crash with small textures
Cxbx-Reloaded/Cxbx-Reloaded pull request #2157
Opened 2021-03-11 07:40 UTC by NZJenkins

Some cleanup work while looking at an issue with DXT conversion when textures are smaller than a 4x4 block
Added a hack to avoid crashes, but stopped short of fixing the conversion code!

2021-03-11 08:53 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					}
This block could be sped up & simplified, by renaming `blockSize` into `minRowPitch`, and assigning it's value upfront (somewhere around where numRows is set). There, set it to 1 for non-compressed formats.

With that, this block here can skip the check for `bCompressed` and the `blockSize` determination, and be reduced to :
```
	if (dwMipRowPitch < minRowPitch) {
		dwMipRowPitch = minRowPitch;
	}
```

2021-03-11 08:53 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +			DWORD pxMipDepth = dwDepth;
This rename clouds the diff a little

2021-03-11 08:53 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				auto numRows = pxMipHeight;
The use of `auto` is a force of habit I guess? (Often, it's better to adhere to local coding style)

2021-03-11 08:53 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +			EmuLog(LOG_LEVEL::WARNING, "Converting DXT textures smaller than a block is not currently implemented. Ignoring conversion!");
Loving the fact you added an in-depth explanation here!

2021-03-11 09:55 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				auto numRows = pxMipHeight;
I type it when I don't care about the type, which turns out to be most of the time! 😛 
Yeah maybe I can change this back to DWORD then

2021-03-11 10:19 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					}
I'm not sure it's simpler?
We replace a special case with a more general `minRowPitch` behaviour, but we don't care about `minRowPitch` outside the special case. The special case is leaking and interleaving itself into other code imo

```c++
// Only relevant unless we're dealing with a compressed texture
DWORD minRowPitch = 0;
if (bCompressed) {
    // The row pitch can't be smaller than a single 4x4 block
    // even if we need to store just one pixel
    // DXT1 block size is 8 bytes
    // Other supported DXT formats are 16 bytes
    minRowPitch = X_Format == xbox::X_D3DFMT_DXT1 ? 8 : 16;
}
```

2021-03-11 11:17 UTC, LukeUsher commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				auto numRows = pxMipHeight;
I'd prefer the use of auto where possible, it's good to modernise the code we work on.

2021-03-11 11:22 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					}
Thing is, in execution there's already an if being performed, so we might as well perform the one that really matters, instead of at least one, at most two (and the blocksize determination in-between).

2021-03-11 11:24 UTC, PatrickvL requested changes
One more attempt to get you to reconsider optimizing the inner loop ;)

2021-03-11 11:24 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					}
Perhaps if you still want it to stand out, call it `minRowPitchForCompressedTextures` or something like that

2021-03-11 11:25 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				auto numRows = pxMipHeight;
True, but such things are better done in a one-shot-kills-all fashion, as now, it's getting spread over many commits & pull requests, which makes it harder to track if things go sour all of a sudden.

2021-03-11 11:26 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +			DWORD pxMipDepth = dwDepth;
... are you going to keep te rename, or change it back? (Which would have the benefit of a smaller commit, leading to focus on what actually changed)

2021-03-11 17:22 UTC, CookiePLMonster submitted a review, later dismissed
Do note this will most likely result in the lowest mipmaps of those uncrompressed textures being black or transparent. Other than that, LGTM as a temporary safeguard before we figure out how to make this code... not suck.

2021-03-12 10:45 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +			DWORD pxMipDepth = dwDepth;
was tossing up splitting it out and cleaning up some other syntax too, but eh. will keep it in mind for next time

2021-03-12 15:14 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					}
that would make it read :
```
	if (dwMipRowPitch < minRowPitchForCompressedTextures) {
		dwMipRowPitch = minRowPitchForCompressedTextures;
	}
```
which avoids the `if (bCompressed)` and `blockSize` determination in a hot spot, at the cost of determining this upfront.

2021-03-13 05:59 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +			blockSize = X_Format == xbox::X_D3DFMT_DXT1 ? 8 : 16;
Shouldn't (bCompressed) be checked here still? 
Also,  this blocksize variable declaration and assignment could be moved up or level,  towards before the loop over all faces starts

2021-03-13 06:06 UTC, PatrickvL requested changes
Nearly there!

2021-03-13 06:53 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +			blockSize = X_Format == xbox::X_D3DFMT_DXT1 ? 8 : 16;
compiler will probably hoist it. Should we care if it doesn't?

2021-03-13 07:23 UTC, PatrickvL approved these changes

2021-03-13 07:24 UTC, merged