Fix Azurik render issue
Cxbx-Reloaded/Cxbx-Reloaded pull request #2158
Opened 2021-03-11 09:34 UTC by NZJenkins

Remove #ifndef blocks that were driven by the opposite define than they should have been
Also provide the opposite flag as a comment, next to where the 'driver' define

Looks like this...
```hlsl
bool alphakill[4] = {false, false, false, false};
#define PS_COMBINERCOUNT 2
// enable PS_COMBINERCOUNT_SAME_C0
#undef PS_COMBINERCOUNT_UNIQUE_C0
// enable PS_COMBINERCOUNT_SAME_C1
#undef PS_COMBINERCOUNT_UNIQUE_C1
#define PS_COMBINERCOUNT_MUX_MSB
#define PS_COMPAREMODE_0(in) CM_LT(in.x) CM_LT(in.y) CM_LT(in.z) CM_LT(in.w)
```

2021-03-11 09:37 UTC, PatrickvL commented
Could you make it read
```
#undef PS_COMBINERCOUNT_UNIQUE_C0 // enables PS_COMBINERCOUNT_SAME_C0
#undef PS_COMBINERCOUNT_UNIQUE_C1 // enables PS_COMBINERCOUNT_SAME_C1
```
?

2021-03-11 09:38 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/PixelShader.cpp
> +void OutputDefineFlag(std::stringstream& hlsl, bool enabled, std::string define_enabled, std::string define_disabled = "")
```suggestion
void OutputDefineFlag(std::stringstream& hlsl, bool enabled, std::string_view define_enabled, std::string_view define_disabled = "")
```

If stringstream supports string views, of course.

2021-03-11 09:42 UTC, PatrickvL requested changes
If possible, try to output one-liners, like the suggestion I made above

2021-03-11 10:37 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/PixelShader.cpp
> +void OutputDefineFlag(std::stringstream& hlsl, bool enabled, std::string define_enabled, std::string define_disabled = "")
interesting... I guess string almost never needs to be passed then?

2021-03-11 10:39 UTC, NZJenkins commented
> 
> 
> If possible, try to output one-liners, like the suggestion I made above

Yup comments are stripped before the macros are applied 👍
much better!

2021-03-11 10:50 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/PixelShader.cpp
> +		hlsl << "\n#define " << define_enabled;
Could you add this :
```
		if (define_disabled.length() > 0) {
			hlsl << " // disables " << define_disabled;
		}
```

2021-03-11 17:19 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/PixelShader.cpp
> +void OutputDefineFlag(std::stringstream& hlsl, bool enabled, std::string define_enabled, std::string define_disabled = "")
Yes! It only makes sense when you want to "own" it, e.g. in constructors. For all other cases, `string_view` is superior because it is a near no-op conversion from both `std::string` and char literals.

The only "price" you pay is lack of a null terminator, but if you don't need one then you can use `string_view`.

2021-03-12 08:22 UTC, PatrickvL requested changes

2021-03-12 08:22 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/PixelShader.cpp
> +	}
If we always want to `#define` one of the two, then this implementation could become :

```
	if (define_disabled.length() > 0) {
	    if (enabled) {
			hlsl << "\n#define " << define_enabled << " // not " << define_disabled;
		} else {
			hlsl << "\n#define " << define_disabled << " // not " << define_enabled;
		}
	} else {
		if (enabled) {
			hlsl << "\n#define " << define_enabled;
		} else {
			hlsl << "\n#undef " << define_enabled;
		}
	}
```

2021-03-12 12:15 UTC, PatrickvL approved these changes

2021-03-12 12:15 UTC, merged