Hlsl ps
Cxbx-Reloaded/Cxbx-Reloaded pull request #2163
Opened 2021-03-14 21:05 UTC by medievil1

2021-03-14 22:22 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	g_pD3DDevice->SetVertexShaderConstantF(230, fogStuff, 1);
Better declare a symbol for this literal numerical value of 230, choose a form and name in line with what's already being used for other VS constants

2021-03-14 22:23 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	auto fogEnable = XboxRenderStates.GetXboxRenderState(X_D3DRS_FOGENABLE);
fogEnable is read but not used here, if it's not needed,  please remove the variable and read.

2021-03-14 22:29 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    /* foginfo is broken down into
For readability, consider declaring const variables for each of the components,  assign the source components to those variables, and use them in the code below. 

This way,  the comment is no longer needed,  the code using the variables becomes more readable,  while the optimizer will still compiler it into the same code (so no additional instructions will be generated for this use of intermediate aliases)

2021-03-14 22:31 UTC, PatrickvL requested changes
Nice work!

Could you address the code review remarks and add a few before & after screenshots to the pull request description, to illustrate how this improves fog modes?

2021-03-15 00:25 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	g_pD3DDevice->SetVertexShaderConstantF(230, fogStuff, 1);
done!

2021-03-15 00:25 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	auto fogEnable = XboxRenderStates.GetXboxRenderState(X_D3DRS_FOGENABLE);
removed and done!

2021-03-15 00:25 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    /* foginfo is broken down into
done!

2021-03-15 00:25 UTC, medievil1 commented
before
![image](https://user-images.githubusercontent.com/38597905/111089690-48572980-8503-11eb-85aa-518f4cca05ce.png)

after
![image](https://user-images.githubusercontent.com/38597905/111089492-84d65580-8502-11eb-812f-551db2b2594e.png)

2021-03-15 04:49 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	// if a better location is viable, i am all for it
done

2021-03-15 06:50 UTC, PatrickvL requested changes
A few more nitpicks and then we're good

2021-03-15 08:26 UTC, NZJenkins reviewed
Some nitpicky comments otherwise LGTM 👍 
The fixup commits should probably be squashed before merging

2021-03-15 08:26 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +       or the results in PS are inconsistant PS fog in may be incorrect*/
nitpick: this is indented differently to other code

2021-03-15 08:26 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	xOut.oFog = fogFactor; // Note : Xbox clamps fog in pixel shader /was oFog.x
thought:
> // Note : Xbox clamps fog in pixel shader

I guess this isn't the case, since you had to saturate the fog factor!
Maybe this whole comment can go...

2021-03-15 08:26 UTC, NZJenkins commented on src/core/hle/D3D8/XbD3D8Types.h
> +
nitpick: extra whitespace

2021-03-15 08:26 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +float4 foginfo : register(c230);
suggestion: not sure what this comment means
could be `// Parameters for mapping the shader's fog output value to a fog factor`?

2021-03-15 08:26 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +
nitpick: extra whitespace

2021-03-15 08:59 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	xOut.oFog = fogFactor; // Note : Xbox clamps fog in pixel shader /was oFog.x
Well, in our pixel shader hlsl code for XFC (the final combiner stage, which incorporates fog), we have this : 
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/37195a61da45367c6e8c10220253b24486e8a58c/src/core/hle/D3D8/Direct3D9/CxbxPixelShaderTemplate.hlsl#L315
and this
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/37195a61da45367c6e8c10220253b24486e8a58c/src/core/hle/D3D8/Direct3D9/CxbxPixelShaderTemplate.hlsl#L150-L158

which leadds to the conclusion that the fog factor (as passed into the Xbox register combiner XFC stage / our pixel shader HLSL for this), is indeed saturated per-pixel.

So at first we could assume that it won't be necessary to saturate here in the vertex shader.

But on the other hand, it also seems like the fog.a input is never modified inside the PS HLSL code, so perhaps in the future, we could optimize this by removing the saturation operation over fog.a from PS HLSL, and instead saturate here, like you have right now (which is probably more efficient, because vertex shaders run per vertex which is much less than the per-pixel run of pixel shaders).

2021-03-15 09:02 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	xOut.oFog = fogFactor; // Note : Xbox clamps fog in pixel shader /was oFog.x
(Oh : note, that as long as we're still using host Fixed Function for null pixel shaders, we also better saturate the fog factor in our vertex shaders, because we don't know if we can rely on host FF to do this.)

2021-03-15 09:51 UTC, PatrickvL requested changes

2021-03-15 09:51 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = { fogStart, fogEnd, density, fogTableMode };
Maybe a bit obsessive, but since fog table mode is the deciding factor (pun intended) in how the other values are used, it may be clearer to put this mode as a first value in the array.
Also, because fog start and end are only used in the 3rd table mode, it may be best to put these in the final two array slots.

Oh, and for consistency, better rename `density` into `fogDensity`.

This would turn it into this code :
```
	auto fogTableMode = XboxRenderStates.GetXboxRenderState(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGTABLEMODE);
	auto fogDensity = XboxRenderStates.GetXboxRenderStateAsFloat(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGDENSITY);
	auto fogStart = XboxRenderStates.GetXboxRenderStateAsFloat(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGSTART);
	auto fogEnd = XboxRenderStates.GetXboxRenderStateAsFloat(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGEND);
	float fogStuff[4] = { fogTableMode, fogDensity, fogStart, fogEnd };
```

(If you agree, then don't forget to also update the aliasses for them in the shader, as the components they reside in would get shuffled around as well by this!)

2021-03-15 09:51 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    float  fdepth   =   oFog.x;
Consider using the same variable names as the C++ code that assigned values to these variables.
When applying that, `foginfo` begins to stand out, so should also be changed into `fogInfo`.

If you're addressing the const prefix and suggested reordering as well, that would lead to this code :
```
    const float fogDepth = oFog.x; 
    const float fogTableMode = fogInfo.x;
    const float fogDensity = fogInfo.y;
    const float fogStart = fogInfo.z;
    const float fogEnd = fogInfo.w;
```

(obviously, also update below code to use the renamed variables)

2021-03-15 09:51 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +float4 foginfo : register(c230);
Also, I suggest to change casing into `fogInfo`, or even `CxbxFogInfo`.

Also, please mention the constant for this register index at the end of the line : ` // CXBX_D3DVS_CONSTREG_FOGINFO = 230

2021-03-15 09:51 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
> +#define CXBX_D3DVS_FOGINFO_CONST                   230
Better make this consistent, and call it `CXBX_D3DVS_CONSTREG_FOGINFO`

2021-03-15 09:53 UTC, PatrickvL commented
> before
> ![image](https://user-images.githubusercontent.com/38597905/111089690-48572980-8503-11eb-85aa-518f4cca05ce.png)
> 
> after
> ![image](https://user-images.githubusercontent.com/38597905/111089492-84d65580-8502-11eb-812f-551db2b2594e.png)
> 
> Azurik is the only game I know for sure it fixes (linear fog is used in some areas so you go no textures at all), but should fix any game using linear distance fog or any of the other special modes in the fog table....
> example video as well
> 
>  Desktop.2021.03.12.-.21.17.24.01.mp4

Better move this towards the topmost pull request description (as a comment like this might easily get overlooked)

2021-03-15 10:04 UTC, PatrickvL requested changes

2021-03-15 10:04 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
>  	float* constant_floats = HLE_get_NV2A_vertex_constant_float4_ptr(0);
It's nicer if vertex shader constants were set in the same order as in which they are declared. This would mean that the actual constants we set here, should be set first, and only then, below that in the order in which they are declared : `CXBX_D3DVS_CONSTREG_VREGDEFAULTS_FLAG_BASE`, `CXBX_D3DVS_SCREENSPACE_SCALE_BASE`, `CXBX_D3DVS_SCREENSPACE_OFFSET_BASE`, `CXBX_D3DVS_TEXTURES_SCALE_BASE` (all set in `CxbxUpdateHostViewPortOffsetAndScaleConstants()`) and only then `CXBX_D3DVS_CONSTREG_FOGINFO` !

2021-03-15 10:04 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
>  #define CXBX_D3DVS_CONSTREG_VREGDEFAULTS_BASE      (X_D3DVS_CONSTREG_COUNT)
Better make FOGINFO consistent with the rest of the CONSTREG's, and call it CXBX_D3DVS_CONSTREG_FOGINFO.

Also, `CXBX_D3DVS_CONSTREG_FOGINFO` should be defined somwhere in this list of CONSTREG's (I guess at the end, or at a logical insertion point), via the same convention as all the others have been declared!

2021-03-15 10:08 UTC, PatrickvL requested changes
Surprising how many improvements could still be found - but don't feel bad about that, most remarks are about (local) consistency in the way the code is written, not about the actual fix, so still kudos for all the work that went into that!

2021-03-15 19:02 UTC, medievil1 commented on src/core/hle/D3D8/XbD3D8Types.h
>  #define CXBX_D3DVS_CONSTREG_VREGDEFAULTS_BASE      (X_D3DVS_CONSTREG_COUNT)
name change ok, BUT it was already in the constregs section (line 1041)

I did move it to 1043 though just so it didn't break up the group of 4 VREGDEFAULTS

// Special Registers, used to pass additional information to the shaders
`/ TODO co-locate shader workaround constants with shader code
#define CXBX_D3DVS_CONSTREG_VREGDEFAULTS_BASE      (X_D3DVS_CONSTREG_COUNT)
#define CXBX_D3DVS_CONSTREG_VREGDEFAULTS_SIZE      16
#define CXBX_D3DVS_CONSTREG_VREGDEFAULTS_FLAG_BASE (CXBX_D3DVS_CONSTREG_VREGDEFAULTS_BASE + CXBX_D3DVS_CONSTREG_VREGDEFAULTS_SIZE)
#define CXBX_D3DVS_CONSTREG_VREGDEFAULTS_FLAG_SIZE 4
#define CXBX_D3DVS_CONSTREG_FOGINFO                230 /`

2021-03-15 19:12 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
>  	float* constant_floats = HLE_get_NV2A_vertex_constant_float4_ptr(0);
so move this to the end of the section :P 
done.....

2021-03-15 19:14 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    float  fdepth   =   oFog.x;
done...had debated doing just that....
also reordered them where they are defined.. as:
```auto fogTableMode = XboxRenderStates.GetXboxRenderState(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGTABLEMODE);
	auto fogDensity = XboxRenderStates.GetXboxRenderStateAsFloat(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGDENSITY);
	auto fogStart = XboxRenderStates.GetXboxRenderStateAsFloat(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGSTART);
	auto fogEnd = XboxRenderStates.GetXboxRenderStateAsFloat(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGEND);

2021-03-15 19:17 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = { fogStart, fogEnd, density, fogTableMode };
done as noted in next review comment...

2021-03-15 19:18 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +float4 foginfo : register(c230);
sounds good...lol
External passthru to me was just passing the values in 
Didn't really consider how to name it...

2021-03-15 19:20 UTC, medievil1 commented on src/core/hle/D3D8/XbD3D8Types.h
> +
done

2021-03-15 19:22 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	xOut.oFog = fogFactor; // Note : Xbox clamps fog in pixel shader /was oFog.x
how about a *Needs testing* since I am not 100% sure yet... for Azurik it seemed to need saturation, BUT for other games it might have different results... not enough to know just yet...

2021-03-15 19:33 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +       or the results in PS are inconsistant PS fog in may be incorrect*/
something more like this? 
```    float  fogDepth   =   oFog.x; 
    float  fogMode    =   foginfo.x;
    float  fpgDensity =   foginfo.y;
    float  fogStart   =   foginfo.z;
    float  fogEnd     =   foginfo.w;
    
    float fogFactor;

    if(fogMode == 0)
    fogFactor = fogDepth;
    if(fogMode == 1)
    fogFactor = saturate(1 / exp(fogDepth * fogDensity)); /* / 1 / e^(d * density)*/
    if(fogMode == 2)
    fogFactor = saturate(1 / exp(pow(fogDepth * fogDensity, 2))); /* / 1 / e^((d * density)^2)*/
    if(fogMode == 3)
    fogFactor = saturate((fogEnd - fogDepth) / (fogEnd - fogStart)) ;

2021-03-15 19:54 UTC, medievil1 reviewed
somehow initiated a review of myself..lol

2021-03-15 20:01 UTC, medievil1 commented
> 
> 
> Surprising how many improvements could still be found - but don't feel bad about that, most remarks are about (local) consistency in the way the code is written, not about the actual fix, so still kudos for all the work that went into that!

not surprising to me.. new to all this... surprised there were not even more issues

2021-03-15 20:15 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +	xOut.oFog = fogFactor; // Note : Xbox clamps fog in pixel shader /was oFog.x
also another thought.... I have the 3 modes saturated currently... should the passthrough oFog.x alone be saturated?? if so I can just removes them int he formula and just saturate fogfactor at the xOut

2021-03-16 07:14 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
> -
Restore empty separation line

2021-03-16 07:17 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
> +#define CXBX_D3DVS_CONSTREG_FOGINFO                230
Enclose with empty separation lines above and below

Replace 230 with a summation of preceding base plus size

2021-03-16 07:18 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	 // Placed this here until we find a better place
Correct indentation

2021-03-16 07:19 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	auto fogTableMode = XboxRenderStates.GetXboxRenderState(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGTABLEMODE);
Prefix these variables with `const`

2021-03-16 07:19 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +float4  CxbxFogInfo: register(c230); // = CXBX_D3DVS_CONSTREG_FOGINFO
Prefix with `uniform`

2021-03-16 07:20 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +const float  fogDepth   =   oFog.x;
Correct indentation

2021-03-16 07:21 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +const float  fogMode    =   CxbxFogInfo.x;
Rename into `fogTableMode`, so it's named identical to its C++ counterpart

2021-03-16 07:22 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +float fogFactor;
Correct indentation

2021-03-16 07:24 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    fogFactor = abs(fogDepth);
Correct indentation; each additional nesting level (like following an if) must use an additional indentation

2021-03-16 07:24 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    fogFactor = 1 / exp(abs(fogDepth) * fogDensity); /* / 1 / e^(d * density)*/
Same here

2021-03-16 07:24 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    fogFactor = 1 / exp(pow(abs(fogDepth) * fogDensity, 2)); /* / 1 / e^((d * density)^2)*/
Same here

2021-03-16 07:24 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    fogFactor = (fogEnd - abs(fogDepth)) / (fogEnd - fogStart) ;
Same here

2021-03-16 07:28 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +const float  fogDepth   =   oFog.x;
Notice how all uses of `fogDepth` in below code apply `abs()` function to its value; If that's correct for all cases, the apply the function here once, at assignment, and remove it from all uses.

2021-03-16 07:30 UTC, PatrickvL reviewed
Again a list of remarks. As a fair general suggestion, it may help to review your own changes for consistency before committing.

2021-03-16 09:59 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
> +
it's still there.... the nitpick was an indication to remove it, so : not done (yet)

2021-03-16 10:02 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	 // Placed this here until we find a better place
Note : check consistent use of tab and/or spaces

2021-03-16 10:05 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	auto fogTableMode = XboxRenderStates.GetXboxRenderState(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGTABLEMODE);
Also, current coding style still prefers actual types instead of `auto`. For `fogTableMode` that would mean `uint32_t`, for the others, that would mean `float`.

2021-03-16 10:09 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = { fogTableMode, fogDensity, fogStart, fogEnd };
Note, that the array contains `float` values, but `fogTableMode` is an `uint32_t` value, thus it needs to be cast here; Most code in Cxbx uses the C-style cast syntax `(float)fogTableMode`, although we're gradually migrating to C++-style which would be the somewhat longer syntax `static_cast<float>(fogTableMode)` - I'll let you decide which one is best here.

2021-03-16 10:54 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = { fogTableMode, fogDensity, fogStart, fogEnd };
actually, since it was added with ps_hlsl, I can just GetXboxRenderStateAsFloat for it, and it will pull it as float like the others, I think anyway... I will resolve it one way or the other though....

2021-03-16 11:00 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +const float  fogDepth   =   oFog.x;
thats a possibility.... actually in reading through some code I ran across nv2a shaders and noticed there were 6 table modes it is using, linear, linear_ABS, EXP, EXP_ABS and EXP2 and EXP2_ABS... not sure if that was an xbox thing or simply something they did in xqemu... but if xbox used it, they would probably need to be added as possible modes, though currently it seems fine with abs always applied...

2021-03-16 12:35 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = { fogTableMode, fogDensity, fogStart, fogEnd };
Nope. You can't use `GetXboxRenderStateAsFloat` as that's for reading values stored as a float. Fog table mode is not stored as a float. It is stored as an unsigned 32 bit integer. Thus you should read it like that. But because it's put in a float, it needs casting, so that the integer value gets encoded into a floating point value.

Integers and floats are encoded differently, so you can't read one as if it's the other, but you can convert them, using a cast (this is all very basic coding stuff every contributor should be aware of).

2021-03-16 19:58 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    if(fogMode == 0)
Looking at this again,  it may also be good to replace the 0, 1, 2 and 3 numbers with constants,  or at least, mention the symbol name of each number in an end of line comment

2021-03-16 20:09 UTC, medievil1 commented on src/core/hle/D3D8/XbD3D8Types.h
> +#define CXBX_D3DVS_CONSTREG_FOGINFO                230
not exactly sure how to do this... 
I mean I can see how it is setup,  
`#define CXBX_D3DVS_CONSTREG_VREGDEFAULTS_BASE      (X_D3DVS_CONSTREG_COUNT)`
is setting to 192, then size adds 16 for 208 in CXBX_D3DVS_CONSTREG_VREGDEFAULTS_FLAG_BASE, etc...  is size just a number to achieve the next result? 
I used 230 because Azurik, used constants all the way up to 228and I wanted to make sure I was outside the "used" range, however from the defines, the last one in the constreg section isn't close to 230

2021-03-16 21:29 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
> +#define CXBX_D3DVS_CONSTREG_FOGINFO                230
`#define CXBX_D3DVS_CONSTREG_FOGINFO (CXBX_D3DVS_CONSTREG_VREGDEFAULTS_FLAG_BASE + CXBX_D3DVS_CONSTREG_VREGDEFAULTS_FLAG_SIZE)`

2021-03-16 21:40 UTC, medievil1 commented on src/core/hle/D3D8/XbD3D8Types.h
> +#define CXBX_D3DVS_CONSTREG_FOGINFO                230
ahhhhhbut that will also entail changing the next in the list (Since it is currently not last) would it not? to simplify I will move it to the end and use the last in list 
`CXBX_D3DVS_SCREENSPACE_SCALE_BASE already uses (CXBX_D3DVS_CONSTREG_VREGDEFAULTS_FLAG_BASE + CXBX_D3DVS_CONSTREG_VREGDEFAULTS_FLAG_SIZE)`

2021-03-16 21:51 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	auto fogTableMode = XboxRenderStates.GetXboxRenderState(xbox::_X_D3DRENDERSTATETYPE::X_D3DRS_FOGTABLEMODE);
in my defense (auto), they were direct copies from FF in direct3d9.cpp line 6443 :)
I will change them though and add const....

2021-03-16 21:53 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	 // Placed this here until we find a better place
and get new glasses... my eyesight is getting so poor I could not see they were one space off

2021-03-16 21:57 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = { fogTableMode, fogDensity, fogStart, fogEnd };
ahhh I misunderstood what `GetXboxRenderStateAsFloat` does then, I assumed it converted to float on the get as the result is a float while `GetXboxRenderState` resulted in uint32_t....

2021-03-16 22:35 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    if(fogMode == 0)
`const float FOG_TABLE_NONE   = 0;
const float FOG_TABLE_EXP    = 1;
const float FOG_TABLE_EXP2   = 2;
const float FOG_TABLE_LINEAR = 3;`

2021-03-16 23:08 UTC, PatrickvL commented on src/core/hle/D3D8/XbD3D8Types.h
> +#define CXBX_D3DVS_CONSTREG_FOGINFO                230
If that's the last one, then sure. 

Do take care that the shader will be using the same index

2021-03-16 23:10 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = { fogTableMode, fogDensity, fogStart, fogEnd };
Yeah,  the function name should communicate that as well,  but it's already quite long.  At any rate,  be careful not to assume too much

2021-03-16 23:13 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    if(fogMode == 0)
Yeah something along those lines. 

Actually, these and other global symbols should be in an include file, used by both c and hlsl code. But let's address that later.

2021-03-17 00:13 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +const float  fogDepth   =   oFog.x;
after further thought, will remove abs from the math and apply it to the value. I know it works as is, and should I find in the future that there needs to be an abs AND non abs version it can be added at that time

2021-03-17 00:18 UTC, medievil1 commented
> 
> 
> Again a list of remarks. As a fair general suggestion, it may help to review your own changes for consistency before committing.

I thought I had..lol.. as I said new to this so still learning and I appreciate all the feedback!! ... next time will go much smoother!

2021-03-17 01:10 UTC, medievil1 commented
> 
> 
> Why revert? Did you update the constant index for fog info in hlsl?



> 
> 
> Why revert? Did you update the constant index for fog info in hlsl?

there was an issue I am tracking it down, the game stage that had distance fog was not working so either the constant wasn't being read or an issue with the compare values... wasn't aware before commit because other stages were working fine.... also sorry for delay, internet decided to crap out all of a sudden

2021-03-17 02:02 UTC, medievil1 commented
> 
> 
> Why revert? Did you update the constant index for fog info in hlsl?

it is resolved..... a couple of issues actually...I updated but was off by one, and static cast couldn't handle uint32_t to float...

2021-03-17 02:47 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +    if(fogMode == 0)
that would be great.... as they are actually already defined in normal c, just not accessible from hlsl shader and it didn't make sense declaring them in constants cause you then have the same issue

2021-03-17 17:14 UTC, Margen67 commented
Sneakers now renders (mostly) correctly ingame:
![image](https://user-images.githubusercontent.com/3462541/111508979-80c85480-8709-11eb-8ce1-315673d71912.png)

2021-03-17 19:39 UTC, medievil1 commented
> 
> 
> Sneakers now renders (mostly) correctly ingame:
> ![image](https://user-images.githubusercontent.com/3462541/111508979-80c85480-8709-11eb-8ce1-315673d71912.png)

wasn't this already fix in h
lsl_ps PR/Branch?

2021-03-17 22:54 UTC, merged