Detect mismatches between the cxbxr executables
Cxbx-Reloaded/Cxbx-Reloaded pull request #2182
Opened 2021-04-05 11:37 UTC by ergo720

This adds a couple of checks to make sure that cxbxe.exe, cxbxr-emu.dll and cxbxr-ldr.exe all come from the same commit build, and aborts otherwise. This is to identify situations in which the user mixes different executable versions (for example, by dropping in the same folder different versions) and encounters otherwise unexplainable issues.

2021-04-05 12:18 UTC, PatrickvL requested changes

2021-04-05 12:18 UTC, PatrickvL commented on src/common/win32/EmuShared.h
> -		int          m_Reserved7[4];
This reserved variable would still be needed for Emuzshared binary compatibility between loader and gui based emulation,  build from the same git version

2021-04-05 12:18 UTC, PatrickvL commented on src/loader/cxbxr-ldr.cpp
> +#include "strsafe.h" // For StringCchCopy
Genuine question: have you checked this doesn't pull in any additional libraries,  not during linking and not during runtime?  If it does, that will sooner or later cause problems with the address range reservation

2021-04-05 12:22 UTC, ergo720 commented on src/common/win32/EmuShared.h
> -		int          m_Reserved7[4];
@RadWolfie asked me to remove these reserved variables, because with the checks it's no longer possible to mix different executable versions and thus we don't need to worry about compatibility of EmuShared

2021-04-05 12:31 UTC, ergo720 commented on src/loader/cxbxr-ldr.cpp
> +#include "strsafe.h" // For StringCchCopy
I can't use `std::strncpy` here because the loader does not link against the CRT, so I have no choice but to use a Windows function.

2021-04-05 13:05 UTC, ergo720 commented on src/loader/cxbxr-ldr.cpp
> +#include "strsafe.h" // For StringCchCopy
Ok, I replaced `StringCchCopy` with a for loop, which does the same.

2021-04-05 14:41 UTC, PatrickvL commented on src/common/win32/EmuShared.h
> -		int          m_Reserved7[4];
Correct me if I'm wrong, but wasn't `CXBX_LOADER` defined for the DLL, but not in the GUI? This would cause a mismatch in the layout of this struct (which is exchanged via EmuShared).

Perhaps a review is required to determine how much use `CXBX_LOADER` still applies. (I guess at the very least is serves as a marker that indicates related pieces of code, which would need alteration when we drop emulation from the GUI executable.)

2021-04-05 14:42 UTC, PatrickvL commented on src/loader/cxbxr-ldr.cpp
> +#include "strsafe.h" // For StringCchCopy
Thanks. Just as long as it's clear as to why this is done...

2021-04-05 15:04 UTC, RadWolfie commented on src/common/win32/EmuShared.h
> -		int          m_Reserved7[4];
@PatrickvL is correct, they need to be reserved because of GUI also load same layout. Otherwise, you will get size mismatch safeguard.

2021-04-05 15:08 UTC, ergo720 commented on src/common/win32/EmuShared.h
> -		int          m_Reserved7[4];
I didn't get any in all the tests I did with it removed. I suppose you are referring to this check here https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/52c88d746253c4df7cec24b9b1a9cb085a763603/src/common/win32/EmuShared.cpp#L121

2021-04-05 15:30 UTC, RadWolfie commented on src/common/win32/EmuShared.h
> +		char m_git_version[GitVersionMaxLength];
Wrong place to put it. It MUST be right below `m_size`, which is at line 67. This is a requirement for compatiblity support and ability to output proper git version output mismatch.

2021-04-05 15:30 UTC, RadWolfie commented on src/common/win32/EmuShared.h
> -		int          m_Reserved7[4];
That's correct. Still, put one reserved back in else block. Eventually, structure will be misalign over time which will trigger the size difference between cxbx and cxbxr-emu because of that extra field.

2021-04-05 20:13 UTC, RadWolfie requested changes

2021-04-05 20:13 UTC, RadWolfie commented on projects/cxbxr-ldr/CMakeLists.txt
> +add_dependencies(cxbxr-ldr misc-batch)
I missed this part, add new line here please.

2021-04-06 19:51 UTC, RadWolfie requested changes
I made a several review remarks. Though, I also made a review remark branch for recommend changes.

review remark branch: https://github.com/RadWolfie/Cxbx-Reloaded/commits/git-version-check-review-remark

I notice there's a merge in there. Disregard that merge commit since it's base from main repo's master branch when I pull the pull request's branch.

Some changes involve such as re-word popup messages, use direct compare between loader/emu than EmuShared first, and relocate git version inside CxbxVersion for reduce time to re-compile whole solution.

2021-04-07 15:17 UTC, RadWolfie reviewed
Last two changes. Then everything looks good to me.

2021-04-07 15:17 UTC, RadWolfie commented on src/common/win32/EmuShared.h
> +		// * Git version string of cxbx.exe
```suggestion
		// * Git version string of first launched initialized
```
Something like ^.

2021-04-07 15:17 UTC, RadWolfie commented on src/common/win32/EmuShared.h
> +		// * Git version Accessor (only the get method is provided because it should not be changed
```suggestion
		// * Git version Accessor (only the get method is provided because it should not be changed)
```
Missing closing bracket.

2021-04-07 18:44 UTC, RadWolfie approved these changes

2021-04-07 18:48 UTC, PatrickvL approved these changes
Looks fine, thanks. Merging...

2021-04-07 18:48 UTC, merged