Fixed function pixel shader
Cxbx-Reloaded/Cxbx-Reloaded pull request #2184
Opened 2021-04-06 08:46 UTC by NZJenkins

Placeholder shader until we are able to directly load the pixel shader program used on the Xbox
A shader is generated for each texture op and argument combination

This does not implement any Xbox extensions, so should behave more or less the same as D3D9
F2 toggles the pixel shader - though fogging for D3D9 fixed function is no longer supported

Includes some other graphics-related fixes

2021-04-06 10:36 UTC, PatrickvL reviewed
A few questions & suggestions for your consideration.

2021-04-06 10:36 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +static bool IsVolumeTexture[4] = IS_VOLUME_TEXTURE_FLAGS; // This should be replaced with a hardcoded value
Wow, what happens here!?

2021-04-06 10:36 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	bool alphaReplicate = fmod(arg, X_D3DTA_ALPHAREPLICATE) >= X_D3DTA_ALPHAREPLICATE / 2;
This `fmod`-based bit test should be moved towards a tooling macro, if used more often

2021-04-06 10:36 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	ctx.SPECULAR = input.iD1;
If you insert front-face detection here, and use `iB0` / `iB1` as alternative source values, then the above `// TODO handle frontface/backface` would be solved

2021-04-06 10:36 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		o = ctx.SPECULAR;
This would need a frontface/backface handling TODO too, right?

2021-04-06 10:36 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		o = ctx.DIFFUSE; // TODO handle frontface/backface
This TODO could be handled when assigning a value to this `DIFFUSE` context structure field, in `main()`

2021-04-06 10:36 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		return arg1 * ctx.DIFFUSE.a + arg2 * (1 - ctx.DIFFUSE.a);
Here, `DIFFUSE` would need to use the backface color when appropriate, right?

2021-04-06 10:36 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		ctx.CURRENT.rgb += input.iD1.rgb;
Better add `ctx.SPECULAR.rgb` here, if you're going to put backface colors in the context diffuse/specular fields.

2021-04-06 10:45 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +static bool IsVolumeTexture[4] = IS_VOLUME_TEXTURE_FLAGS; // This should be replaced with a hardcoded value
`IS_VOLUME_TEXTURE_FLAGS;` gets replaced
Since as far as I could tell we can only use a sampler with Tex2D or Tex3D, not both

2021-04-06 10:48 UTC, PatrickvL reviewed
Some more remarks

2021-04-06 10:48 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		return arg0 * arg1 + (1 - arg0) * arg2;
Why not use the actual `lerp()` function here?

2021-04-06 10:48 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +
Please comment on why ordering 1, 2, 0 is used.

2021-04-06 10:48 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	float4 aArg0 = GetArg(s.ALPHAARG0, ctx);
Please comment on why ordering 1, 2, 0 is used.

2021-04-06 10:48 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> -    bool bOldOrder = g_LibVersion_D3D8 <= 3948; // Verified old order in 3944, new order in 4039
Why was this dropped?

2021-04-06 10:48 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +
Nevermind the previous question on why `bOldOrder` was dropped - it's because you've handled them here. Nice work.

2021-04-06 10:48 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +static bool IsVolumeTexture[4] = IS_VOLUME_TEXTURE_FLAGS; // This should be replaced with a hardcoded value
Ah, I see the code searches and replaces `IS_VOLUME_TEXTURE_FLAGS` - better mention that here in a comment!!

2021-04-06 10:52 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	ctx.SPECULAR = input.iD1;
Yes. Though we don't read the required renderstates from the NV2A to implement it properly yet IIRC so I didn't bother

2021-04-06 10:53 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		return arg1 * ctx.DIFFUSE.a + arg2 * (1 - ctx.DIFFUSE.a);
I think we would set DIFFUSE and SPECULAR to front or back in the beginning, and then we can forget about it from then on

2021-04-06 10:54 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		ctx.CURRENT.rgb += input.iD1.rgb;
yep shouldn't need to be using `input` at that point at all!

2021-04-06 10:57 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		return arg0 * arg1 + (1 - arg0) * arg2;
I tried to stick to the D3D9 docs which defines the functions like this

2021-04-06 10:59 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> -    bool bOldOrder = g_LibVersion_D3D8 <= 3948; // Verified old order in 3944, new order in 4039
This mapping logic was moved to the `NormalizeValue` function

2021-04-06 12:27 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +
done

2021-04-06 12:27 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	float4 aArg0 = GetArg(s.ALPHAARG0, ctx);
done

2021-04-06 12:29 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		o = ctx.DIFFUSE; // TODO handle frontface/backface
added a comment to that end

2021-04-06 12:29 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		o = ctx.SPECULAR;
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2184#discussion_r607745327

2021-04-06 12:30 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		ctx.CURRENT.rgb += input.iD1.rgb;
done

2021-04-06 12:53 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	ctx.SPECULAR = input.iD1;
Well, there's this : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/01b3ce4eec9178e8e704232fd12477a4e557505e/src/core/hle/D3D8/Direct3D9/CxbxPixelShaderTemplate.hlsl#L328-L335

2021-04-06 13:04 UTC, PatrickvL commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	// Insert the shader into the cahce
nit : cache (not cahce)

2021-04-06 13:04 UTC, PatrickvL commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		stageSetup << target << "COLOROP = " << D3DTOPToString[(int)s.COLOROP] << ";\n";
Guard against bounds-overflow?

2021-04-06 13:08 UTC, PatrickvL commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		stageSetup << target << "ALPHAOP = " << D3DTOPToString[(int)s.ALPHAOP] << ";\n";
Guard against bounds-overflow?

2021-04-06 13:08 UTC, PatrickvL commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		if (states[i].COLOROP == X_D3DTOP_DISABLE)
What if ALPHAOP is not disabled?

2021-04-06 13:08 UTC, PatrickvL commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	FixedFunctionPixelShaderState ffPsState;
nit : empty line between those?

2021-04-06 13:08 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				g_UseFixedFunctionPixelShader = !g_UseFixedFunctionPixelShader;
So, F2 no longer swaps `g_UseFixedFunctionVertexShader` - aren't users going to notice? Perhaps move that toggle to another hotkey?

2021-04-07 06:15 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	ctx.SPECULAR = input.iD1;
Yep. It doesn't work afaik due to reason above

2021-04-07 06:19 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		if (states[i].COLOROP == X_D3DTOP_DISABLE)
Doesn't matter. if colorop is disabled the stage is

2021-04-07 06:22 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				g_UseFixedFunctionPixelShader = !g_UseFixedFunctionPixelShader;
Users shouldn't be pressing f2
Imo VS is pretty stable by now - we should purge FF as soon as we can

2021-04-07 07:56 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	ctx.SPECULAR = input.iD1;
to expand: I am thinking of `TWOSIDEDLIGHTING`, which is not mapped right now in `XbConvert`
Which probably corresponds to `GL_LIGHT_MODEL_TWO_SIDE`?
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glLightModel.xml

But it might be that lighting doesn't have to be enabled to use frontface and backface colours
Don't know any test cases for backface colouring without lighting

2021-04-07 09:16 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		stageSetup << target << "COLOROP = " << D3DTOPToString[(int)s.COLOROP] << ";\n";
added some guards and logging too

2021-04-07 09:24 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				g_UseFixedFunctionPixelShader = !g_UseFixedFunctionPixelShader;
I agree only if those AMD issues are resolved by using a FF PS shader. If not, that hotkey should likely stay.

2021-04-07 09:37 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				g_UseFixedFunctionPixelShader = !g_UseFixedFunctionPixelShader;
I think we should do better than a debug key if for some reason there is still an issue.
It was never intended to be a workaround

2021-04-07 09:40 UTC, NZJenkins commented
If all is well I'll squash the messy fixup commits before merge

2021-04-07 09:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	if (arg == X_D3DTA_CURRENT)
Any reason not to use `else if` in this block?

2021-04-07 09:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		t = IsVolumeTexture[i]
What about cubemaps? They need `texCUBE`.

2021-04-07 09:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	return output;
Nitpick, but the function can just return `float4` unless you foresee it'll be returning more in the future at some point. It's unlikely though as iirc xbox doesn't support multiple rendertargets.

2021-04-07 09:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +            case xbox::X_D3DTOP_BLENDCURRENTALPHA:
I think this would be easier to understand if switch cases used numbers instead of those constants, as those cases are not supposed to be meaningful stage states (instead being converted to such).

2021-04-07 09:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		auto sourceFile = hlslDir.append("FixedFunctionPixelShader.hlsl").string();
```suggestion
		auto sourceFile = hlslDir.append("FixedFunctionPixelShader.hlsl").native();
```

This will return a `wstring` and thus not do character conversion, `ifstream` can handle this fine I'm pretty sure.

2021-04-07 09:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	const std::string opToString[] = {
```suggestion
	static constexpr std::string_view opToString[] = {
```

Those are constant strings so no need to exercise heap allocations. `string_view` will most likely make them compiled in .rdata as-is.

2021-04-07 09:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	const std::string argToString[] = {
```suggestion
	static constexpr std::string_view argToString[] = {
```

As above.

2021-04-07 09:41 UTC, CookiePLMonster commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	EmuCompileShader(finalShader, "ps_3_0", &pShaderBlob, pseudoSourceFile.c_str());
Note for the future: Do ensure `EmuCompileShader` understands that the path passed to it is UTF-8. Otherwise make it accept a `wstring` and change the line above to return `.native()`.

2021-04-07 10:02 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	if (arg == X_D3DTA_CURRENT)
It's better aligned that's about it. Just pretend it's a switch 😉

2021-04-07 10:05 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		t = IsVolumeTexture[i]
I don't know. They might just be volume textures? @PatrickvL ?

2021-04-07 10:09 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		t = IsVolumeTexture[i]
yes need to look at handling `X_D3DRTYPE_CUBETEXTURE`

2021-04-07 10:17 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	return output;
you're right we probably won't want to output anything else, but can't seem make it float4 since the compiler wants a semantic i.e. COLOR. will just leave it as is

2021-04-07 10:25 UTC, CookiePLMonster commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	return output;
`float4 main(const PS_INPUT input) : COLOR0`

2021-04-07 10:29 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	return output;
oh nice

2021-04-07 10:35 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	EmuCompileShader(finalShader, "ps_3_0", &pShaderBlob, pseudoSourceFile.c_str());
We need `LPCSTR` i.e. 8bit ANSI - that would mean we shouldn't pass wstring?
I am not sure what we are supposed to do if the path is not ANSI - since I think it's required for HLSL includes.
Maybe it should be a relative path since we have control over it i,e. ./hlsl/filename?

2021-04-07 10:37 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	const std::string argToString[] = {
since we need a string from the return value, I am not sure if there is a benefit, for D3DTA?

2021-04-07 12:04 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		auto sourceFile = hlslDir.append("FixedFunctionPixelShader.hlsl").string();
not sure what character conversion you're referring to

2021-04-07 14:13 UTC, PatrickvL requested changes
I know, when people go through your code with a fine comb, it doesn't feel ... great... but it's with the best of intentions that these remarks are made!

2021-04-07 14:13 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	// But some titles seem to set it to DIFFUSE
Could you mention a few titles that set `DIFFUSE` instead of `CURRENT` or `TEMP`?

And either add a TODO to handle the `DIFFUSE` case, or actually implement it, or explain in a comment if & why only `TEMP` or `CURRENT` are valid outputs.

This, because `X_D3DTA_` has these suffixes : `DIFFUSE`, `CURRENT`, `TEXTURE`, `TFACTOR`, `SPECULAR`, `TEMP` (besides the flags), so in theory, each of those could be selected as TextureStage output, right?

2021-04-07 14:13 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		t = IsVolumeTexture[i]
Cubes are not the same as volume textures; A volume texture layers slices on top of eachother, to create a 3D matrix of pixels that can be sampled. A cube is just 6 faces, so only the exterior can be sampled. Calculation of the pixel memory address(es) to sample, is obviously different for these two modes, so yeah, `texCUBE` is required here, if you want to support cube-maps in fixed function ;)

2021-04-07 20:04 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	bool LightingEnable = (float)XboxRenderStates.GetXboxRenderState(X_D3DRS_LIGHTING);
Yep or just implicit cast?

2021-04-07 20:04 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	bool PointSpriteEnable = XboxRenderStates.GetXboxRenderState(X_D3DRS_POINTSPRITEENABLE);
Is it?

2021-04-07 20:09 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	else if (op == X_D3DTOP_SELECTARG1)
There is a comment
D3DCompile stackoverflows 🤷‍♂️

2021-04-07 20:13 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	return float4(0, 1, 1, 1);
No reason at all. Will comment

2021-04-07 20:28 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +float4 Op(float op, float4 arg1, float4 arg2, float4 arg0, TextureArgs ctx, PsTextureStageState stage) {
Seems like noise to me

2021-04-07 20:30 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +static float4 TexCoords[4];
Nope since it's not needed. Saves passing them around, nothing to see here

2021-04-07 20:43 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +float4 GetArg(float arg, TextureArgs ctx) {
Note PS inputs are floats, so having an int arg emits extra instructions to do a conversion.
We can change it to int at no cost, but only since arg will currently be known at compile time

2021-04-07 21:16 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		stage->ALPHAKILL = XboxTextureStates.Get(i, xbox::X_D3DTSS_ALPHAKILL);
Yes - maybe in the hlsli file so it's closer to the implementation and less likely to become stale

2021-04-07 22:27 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +float4 Op(float op, float4 arg1, float4 arg2, float4 arg0, TextureArgs ctx, PsTextureStageState stage) {
> Seems like noise to me

I happen to agree with @PatrickvL, main reason there is `const` existance. If we are not going to modify arguments, then it will perform more optimization than without `const`. On the plus side, it will also prevent us rewrite the arguments unintentionally.

2021-04-07 22:58 UTC, fantesykikachu commented
I am testing on an AMD GPU, on master most games crash or have no textures, the last good version was right before the original hlsl vertex shader (non fixed function), I have done a cursory test of all of my games (about 50), and I am happy to report that basically all of them are as good or better than they were back then. The only two regressions that I observed that are also regressions against master with DXVK, are Fuzion Frenzy and Metal Arms: Glitch in the System.

Fuzion Frenzy master:
![ff master](https://user-images.githubusercontent.com/21281083/113944584-0055ba80-97c2-11eb-8cd8-06b727b05f58.PNG)

Fuzion Frenzy PR:
![ff PR](https://user-images.githubusercontent.com/21281083/113944612-0f3c6d00-97c2-11eb-8197-b75b7eb2fcb0.PNG)

Metal Arms master:
![metal arms master](https://user-images.githubusercontent.com/21281083/113944660-24190080-97c2-11eb-8b07-78aece59eeef.PNG)

Metal Arms PR:
![metal arms PR](https://user-images.githubusercontent.com/21281083/113944857-7528f480-97c2-11eb-8c72-4ba2d727836f.PNG)

2021-04-08 03:55 UTC, RinMaru commented
> Metal Arms PR:
> ![metal arms PR](https://user-images.githubusercontent.com/21281083/113944857-7528f480-97c2-11eb-8c72-4ba2d727836f.PNG)

Metal arms doesnt render anything for me

2021-04-08 06:24 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +float4 Op(float op, float4 arg1, float4 arg2, float4 arg0, TextureArgs ctx, PsTextureStageState stage) {
Don't care if it exists. It probably has a place but no reason to blanket add it.

My understanding is it makes no difference to shader asm too. Happy to be shown otherwise

With this I just see future me trying to debug/tweak a shader, and having to remove const to assign an argument...

2021-04-08 06:26 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	// But some titles seem to set it to DIFFUSE
DoA is listed below as a test case
The RESULTARG texture state is documented to be CURRENT or TEMP as noted in the comment

2021-04-08 09:44 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +		stage->ALPHAKILL = XboxTextureStates.Get(i, xbox::X_D3DTSS_ALPHAKILL);
done. There's a comment on the field so it shows up in intellisense wherever used :)

2021-04-08 09:44 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	return float4(0, 1, 1, 1);
done

2021-04-08 09:44 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	bool PointSpriteEnable = XboxRenderStates.GetXboxRenderState(X_D3DRS_POINTSPRITEENABLE);
done

2021-04-08 09:45 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	bool LightingEnable = (float)XboxRenderStates.GetXboxRenderState(X_D3DRS_LIGHTING);
just removed the cast altogether

2021-04-08 09:46 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	EmuCompileShader(finalShader, "ps_3_0", &pShaderBlob, pseudoSourceFile.c_str());
I've added a TODO since apparently we need an ANSI string, but we don't currently control the path.
If we can coax visual studio to use the .exe location as the working directory, we should be able to use a relative path

2021-04-08 09:47 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/TextureStates.cpp
> +            case xbox::X_D3DTOP_BLENDCURRENTALPHA:
done

2021-04-08 09:47 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		t = IsVolumeTexture[i]
done

2021-04-08 09:48 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +	const std::string argToString[] = {
using `static const std::string` since `string_view` did not seem to be beneficial, here

2021-04-08 09:48 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	if (state.stages[i].IsTextureSet) {
done

2021-04-08 09:49 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +float4 Op(float op, float4 arg1, float4 arg2, float4 arg0, TextureArgs ctx, PsTextureStageState stage) {
done

2021-04-08 09:49 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +TextureArgs Stage(
done

2021-04-08 09:54 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	}
Would it produce more efficient byte code when the final check is omitted?

2021-04-08 09:54 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	}
Or here's an idea : Remove `IsTextureSet`, and make it a `SAMPLE_NONE` sample type?

2021-04-08 10:00 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +
I had added them around the block as it felt a bit cramped

2021-04-08 10:10 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	}
The sample type is known at compile time - so this code is compiled away
In fact, the HLSL compiler doesn't allow us to do this branch at runtime (at least in `ps_3_0`)
Each sampler is defined at at the beginning with a particular dimension/type e.g.
```
    dcl_2d s0
    dcl_2d s1
```

2021-04-08 10:13 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	}
Good idea - will save a few instructions too

2021-04-08 10:25 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +
Sure, fine.

2021-04-09 12:37 UTC, PatrickvL commented on src/core/hle/D3D8/XbPixelShader.cpp
> -			// SampleType is initialized to SAMPLE_2D
Instead of removing this comment, it could've been updated to `SAMPLE_NONE`

2021-04-09 12:44 UTC, PatrickvL approved these changes
Looks good now, great work!

2021-04-09 12:45 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +	}
Thanks for applying this - it makes it even cleaner. The less fuss, the better!

2021-04-09 15:21 UTC, merged