kernel: implement title mount path
Cxbx-Reloaded/Cxbx-Reloaded pull request #2193
Opened 2021-04-12 22:32 UTC by RadWolfie

Finally, it is here! Ability to remember first load title (from CdRom0/Mbfs devices).

I made some changes relative to:
- Move Xbox file path to host path into its own function.
- Added ability to bind cli load's path to xbox environment for symbolic link purpose.
- Remember title mount path on first cli load.
  - NOTE: Reboot's cli load is from launchdata page's file path to xbe.
  - Also critical for chihiro titles and retail's xbox live service.
- Add xbox's max_path and apply to relative usage. (I may not get them all, can be fix in later pull request.)
- Due to incomplete implemention of IoCreateDevice, there is a hack in place to prevent dashboard reboot continuously.

---

I have personally tested with official dashboard (4920), xbox live, and Exhibition Demo Disc (vol 1). They are able to response very well with this pull request as of commit 152d6be.

2021-04-13 10:22 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlHal.cpp
> +#pragma optimize("", off)
Why do you need to turn optimizations off for this file? This seems bad.

2021-04-13 10:25 UTC, ergo720 commented on src/core/kernel/init/CxbxKrnl.cpp
> +#pragma optimize("", off)
2/3 Why do you need to turn optimizations off for this file? This seems bad.

2021-04-13 10:25 UTC, ergo720 commented on src/core/kernel/support/EmuFile.cpp
> +#pragma optimize("", off)
3/3 Why do you need to turn optimizations off for this file? This seems bad.

2021-04-13 10:31 UTC, ergo720 commented on src/core/kernel/init/CxbxKrnl.cpp
> +		for (n = 0, i = 1; i < slash_search->size(); i++, n = 0) {
Just to be sure of it: is the change  0 -> 1 for `i` intentional or accidental?

2021-04-13 10:58 UTC, ergo720 commented on src/core/kernel/init/CxbxKrnl.cpp
> +		// TODO: DriveD should auto mount base on launchdata page's ; delimiter xbe path.
```suggestion
		// TODO: DriveD should auto mount based on the launchdata page's ; delimiter in the xbe path.
```

2021-04-13 11:27 UTC, ergo720 commented on src/core/kernel/support/EmuFile.h
> +static constexpr char CxbxDelimiterAutoMountDriveLetter = 'D';
No need for `static` here. `constexpr` variables are implicitly `const`, and `const` on global/namespace scope implies `static`.

2021-04-13 11:48 UTC, PatrickvL commented on src/core/kernel/init/CxbxKrnl.cpp
> +		for (n = 0, i = 1; i < slash_search->size(); i++, n = 0) {
...and if intentional, then why not simply remove the first character from `slash_search` instead?

2021-04-13 11:59 UTC, PatrickvL requested changes
Nice work! Just a few remarks to consider...

2021-04-13 11:59 UTC, PatrickvL commented on src/core/kernel/support/EmuFile.cpp
> +	// Convert Xbox XBE Path to Host Path
This can become a header comment instead of inline.

2021-04-13 11:59 UTC, PatrickvL commented on src/core/kernel/support/EmuFile.cpp
> +	{
This set of curly brackets can be removed now, and then the indentation of the contained code can be decreased by one level.

2021-04-13 11:59 UTC, PatrickvL commented on src/core/kernel/support/EmuFile.cpp
> +
Duplicate newline. One suffices.

2021-04-13 11:59 UTC, PatrickvL commented on src/core/kernel/support/EmuFile.cpp
> +		std::error_code error;
Can this `error` safely be ignored? Perhaps comment on it...

2021-04-13 11:59 UTC, PatrickvL commented on src/core/kernel/support/EmuFile.cpp
> +				/*if (RelativePath.compare(0, 7, "CDROM0:") == 0) {
At least, when commented-out code is introduced, add a `TODO` comment along with it, explaining what still needs to be done before this can be enabled.

2021-04-13 11:59 UTC, PatrickvL commented on src/core/kernel/support/EmuFile.cpp
> +#include "common/util/strConverter.hpp"
For what symbols is this #include needed? It helps to add a EOL comment mentioning that (so that if that symbol is ever removed from code, this include can be removed along with it)

2021-04-13 11:59 UTC, PatrickvL commented on src/core/kernel/support/EmuFile.h
> +static constexpr char CxbxDelimiterAutoMountDriveLetter = 'D';
This variable also doesn't seem to be used as a delimiter (which is normally a sub-string that resides between two separate parts of a string). So, better drop the `Delimiter` part from this symbol name, and simply call it `CxbxAutoMountDriveLetter`. IMHO.

2021-04-13 14:37 UTC, RadWolfie commented on src/core/kernel/support/EmuFile.cpp
> +		std::error_code error;
Yes, it can be safely ingored since we expect return value to either true or false. Normally when directory creation fail, it will throw C++ exception error. Since we don't check for C++ exception error nor do we have a "fixed" SEH exception issue duration of the emulation. We need error here to tell fileystem not to throw an exception error.

2021-04-13 15:13 UTC, PatrickvL commented on src/core/kernel/support/EmuFile.cpp
> +		std::error_code error;
Okay, thanks. Please summarize that into a comment, so no-one will wonder about this any further.

2021-04-13 15:39 UTC, RadWolfie commented on src/core/kernel/support/EmuFile.h
> +static constexpr char CxbxDelimiterAutoMountDriveLetter = 'D';
We only perform auto mount base on `;` delimiter. Using `CxbxAutoMountDriveLetter` is misleading since kernel don't always auto mount D letter. Well, since XDK does it for titles to automatic assign D letter. I guess I could remove delimiter part.

2021-04-13 15:39 UTC, RadWolfie commented on src/core/kernel/init/CxbxKrnl.cpp
> +		for (n = 0, i = 1; i < slash_search->size(); i++, n = 0) {
> Just to be sure of it: is the change 0 -> 1 for `i` intentional or accidental?

Accidental, I was thinking about Windows' network shared directory issue at the time. Change the `i` wouldn't fix it anyway.

2021-04-13 15:45 UTC, RadWolfie commented on src/core/kernel/init/CxbxKrnl.cpp
> +		for (n = 0, i = 1; i < slash_search->size(); i++, n = 0) {
It's revert back to original code.

2021-04-13 15:47 UTC, RadWolfie commented on src/core/kernel/support/EmuFile.cpp
> +		std::error_code error;
done

2021-04-13 17:52 UTC, PatrickvL approved these changes
Okay,  seems fine now.
Let's await a few test reports before merging this

2021-04-13 17:57 UTC, RadWolfie commented
> Okay, seems fine now.
> Let's await a few test reports before merging this

What I would like to hear is titles using xbox live has ability to go into xbox live dashboard and back properly. Though, base on my changes should work as intended. One of title I couldn't test is Call of Duty 3.

2021-04-13 20:57 UTC, RadWolfie commented
Eh, I need to make an inline function for this since it need to be done 3 times for different paths.

2021-04-13 21:29 UTC, RadWolfie commented
Okay, solved the host's symbolic link to full path issue. I still haven't found working titles able to go into xbox live dashboard.

2021-04-23 20:48 UTC, PatrickvL approved these changes

2021-04-23 20:48 UTC, merged