Fix RtlUnicodeStringToAnsiString bug
Cxbx-Reloaded/Cxbx-Reloaded pull request #2200
Opened 2021-04-16 17:52 UTC by RadWolfie

When make an atttempt to create profile from DoA 1 Ultimate's online section. It made a fatal crash due to incorrect unicode to string size which lead to buffer overflow exception. After [add a test for xbox kernel test suite](https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/pull/70), I have fix any possible result for success and failure in the process of fixing Cxbx-Reloaded's RtlUnicodeStringToAnsiString bug.

With this fix, DoA 1 Ultimate's profile creation no longer crash.

```
0x0134 - RtlUnicodeStringToAnsiString: Tests Starting
  Test 'Initialize unicode string.' PASSED
  Function 'RtlUnicodeStringToAnsiString' returned 0x0 as expected
  Test 'Convert partial unicode to ansi string (alloc).' PASSED
  Function 'RtlUnicodeStringToAnsiString' returned 0x0 as expected
  Test 'Convert partial unicode to ansi string.' PASSED
  Function 'RtlUnicodeStringToAnsiString' returned 0x80000005 as expected
  Function 'RtlUnicodeStringToAnsiString' returned 0x0 as expected
  Test 'Convert full unicode to ansi string.' PASSED
  Function 'RtlUnicodeStringToAnsiString' returned 0x80000005 as expected
  Function 'RtlUnicodeStringToAnsiString' returned 0x0 as expected
  Test 'Unicode to max ansi string.' PASSED
  Function 'RtlUnicodeStringToAnsiString' returned 0x0 as expected
  Test 'Max unicode to max ansi string.' PASSED
0x0134 - RtlUnicodeStringToAnsiString: All tests PASSED
```

---

It will resolve https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/pull/70's crash and return expecting results.

2021-04-17 15:08 UTC, PatrickvL requested changes
A small bug, some suggestions for improvement, and a few remarks / questions.

2021-04-17 15:08 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlRtl.cpp
>  		if (!(DestinationString->Buffer = (PCHAR)ExAllocatePoolWithTag(len, 'grtS'))) {
Prior contents (if any) will be overwritten by this assignment. Would it make be wise to validate we don't leak memory this way? (Which would happen if the existing `Buffer` pointer is a valid memory address, not owned by any other reference.)

On the other hand, perhaps by design `DestinationString` is assumed to be uninitialized, in which case we should not verify existing values before overwriting them...

2021-04-17 17:21 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlRtl.cpp
> +	else if (DestinationString->MaximumLength < len) {
Using `<` is correct, len variable is actually "maximum length". Perhaps I should rename it for clarification. Maximum length value include null terminate whilst length doesn't for all "STRING" structures.

Hmm... I see I failed to include a test for length == max length check in the kernel test.

2021-04-17 17:21 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlRtl.cpp
>  	DestinationString->Buffer[DestinationString->Length] = 0;
Replaced? We don't have `RtlUnicodeToMultiByteN` test implement and I wasn't sure what do if we're using `RtlUnicodeToMultiByteN` call properly. Perhaps we should implement the `RtlUnicodeToMultiByteN` test for verification.

Also... good spot on for NULL should be xbox::zeroptr. 👍

2021-04-17 17:21 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlRtl.cpp
>  	RETURN(ret);
Actually, you make a very good point! 👍 I will fix it soon.

2021-04-17 17:21 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlRtl.cpp
>  		if (!(DestinationString->Buffer = (PCHAR)ExAllocatePoolWithTag(len, 'grtS'))) {
I believe it is the latter. Since titles do make call to RtlUnicodeStringToAnsiString with request to allocate buffer internally return back to title. It's pretty much the same in general programming do.

There appear to be no checks involve for unitialized value nor check if buffer is null pointer.

2021-04-17 20:22 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlRtl.cpp
> +	else if (DestinationString->MaximumLength < len) {
Updated len variable to `AnsiMaxLength` for better clarification and added a test from kernel test suite side for this. It doesn't matter which test has buffer overflow return. Since it always reduce down by one for current length base on destination's given maximum length. The only time we use `<=` operator is when we compare it against DestinationString's Length field.

So, it's the same way. Yet I use `AnsiMaxLength` without need access to DestinationString's Length field.

2021-04-17 20:24 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlRtl.cpp
>  	RETURN(ret);
done

2021-04-17 20:24 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlRtl.cpp
>  	DestinationString->Buffer[DestinationString->Length] = 0;
done

2021-04-17 20:24 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlRtl.cpp
> +		RETURN(ret);
done

2021-04-19 06:50 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlRtl.cpp
>  		if (!(DestinationString->Buffer = (PCHAR)ExAllocatePoolWithTag(len, 'grtS'))) {
Agreed

2021-04-20 08:44 UTC, PatrickvL approved these changes

2021-04-20 08:44 UTC, merged