cmake: Fix for Ninja generator
Cxbx-Reloaded/Cxbx-Reloaded pull request #2207
Opened 2021-04-24 16:41 UTC by scribam

This PR allows to use the Ninja generator with CMake to build Cxbx-Reloaded.

2021-04-24 18:13 UTC, PatrickvL commented on projects/cxbxr-ldr/CMakeLists.txt
> -  /LARGEADDRESSAWARE
It's better to keep each flag on a separate line,  because that won't cause too long lines, and any change on the flags will be easier to merge as it would only change/ remove/introduce single lines.

2021-04-24 18:14 UTC, PatrickvL commented on projects/cxbxr-emu/CMakeLists.txt
> -  /INCREMENTAL:NO
Here each flag on a separate line too

2021-04-24 18:14 UTC, PatrickvL commented on projects/cxbxr-emu/CMakeLists.txt
> -  /Zi
Here each flag on a separate line too

2021-04-24 18:14 UTC, PatrickvL commented on projects/cxbx/CMakeLists.txt
> -  /INCREMENTAL:NO
Here each flag on a separate line too

2021-04-24 18:14 UTC, PatrickvL commented on projects/cxbx/CMakeLists.txt
> -  /Zi
Here each flag on a separate line too

2021-04-24 18:15 UTC, PatrickvL requested changes
What's this ninja thing?

2021-04-24 18:19 UTC, scribam commented
Having flags on separate lines seems to break Ninja which doesn't keep a space between each flags
```
FAILED: bin/cxbxr-ldr.exe 
cmd.exe /C "cd . && C:\Users\scribam\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\211.7142.21\bin\cmake\win\bin\cmake.exe -E vs_link_exe --intdir=projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.299\bin\Hostx86\x86\link.exe /nologo projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir\__\__\src\CxbxVersion.cpp.obj projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir\__\__\src\common\AddressRanges.cpp.obj projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir\__\__\src\common\ReserveAddressRanges.cpp.obj projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir\__\__\src\loader\cxbxr-ldr.cpp.obj  /out:bin\cxbxr-ldr.exe /implib:projects\cxbxr-ldr\cxbxr-ldr.lib /pdb:bin\cxbxr-ldr.pdb /version:0.0 /machine:X86 /INCREMENTAL:NO /subsystem:console /LARGEADDRESSAWARE/FIXED/DYNAMICBASE:NO/BASE:0x10000/STACK:65536,65536/NODEFAULTLIB/ENTRY:rawMainLINK_LIBRARIES = kernel32.lib   && cd ."
LINK: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.299\bin\Hostx86\x86\link.exe /nologo projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir\__\__\src\CxbxVersion.cpp.obj projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir\__\__\src\common\AddressRanges.cpp.obj projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir\__\__\src\common\ReserveAddressRanges.cpp.obj projects\cxbxr-ldr\CMakeFiles\cxbxr-ldr.dir\__\__\src\loader\cxbxr-ldr.cpp.obj /out:bin\cxbxr-ldr.exe /implib:projects\cxbxr-ldr\cxbxr-ldr.lib /pdb:bin\cxbxr-ldr.pdb /version:0.0 /machine:X86 /INCREMENTAL:NO /subsystem:console /LARGEADDRESSAWARE/FIXED/DYNAMICBASE:NO/BASE:0x10000/STACK:65536,65536/NODEFAULTLIB/ENTRY:rawMainLINK_LIBRARIES = kernel32.lib /MANIFEST /MANIFESTFILE:bin\cxbxr-ldr.exe.manifest" failed (exit code 1181) with the following output:
LINK : warning LNK4044: unrecognized option '/LARGEADDRESSAWARE/FIXED/DYNAMICBASE:NO/BASE:0x10000/STACK:65536,65536/NODEFAULTLIB/ENTRY:rawMainLINK_LIBRARIES'; ignored
LINK : fatal error LNK1181: cannot open input file '=.obj'
ninja: build stopped: subcommand failed.
```
Ninja is a small build system with a focus on speed. https://ninja-build.org/

2021-04-24 18:28 UTC, RadWolfie commented on projects/cxbxr-ldr/CMakeLists.txt
> -  /LARGEADDRESSAWARE
I agree with ^ hence the main reason they are on new lines when I introduce 

In summary, having each flag on new line is easier for...
1. Human readability.
2. Git friendly and at least notice the accidental removal after solve rebase conflict.

2021-04-24 18:30 UTC, PatrickvL commented
Best report that bug to ninja then!

2021-04-24 19:08 UTC, RadWolfie commented
Weird, I find it strange. Possible workaround is to create our own variable list then output them into the command as a long term solution.

2021-04-24 21:16 UTC, scribam commented
It works with the backslashes, thanks for the tip 👍

2021-04-25 06:26 UTC, RadWolfie commented on projects/cxbx/CMakeLists.txt
> + $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<CONFIG:RELEASE>>:/Zi>
I don't really understand what reason you're going with this route and why there are reduntants conditional. Since we do have a block for identify `CMAKE_CXX_COMPILER_ID` above here. As for config release check is fine. Still, don't need redundants conditional as it can be done in one conditional check. Backslashes should work for it.

2021-04-25 06:28 UTC, RadWolfie commented on projects/cxbxr-ldr/CMakeLists.txt
> + $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<CONFIG:RELEASE>>:/Oi>
Same thing here.

2021-04-25 06:29 UTC, RadWolfie commented on projects/cxbxr-emu/CMakeLists.txt
> + $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<CONFIG:RELEASE>>:/Zi>
Here too as well.

2021-04-25 08:26 UTC, scribam commented on projects/cxbx/CMakeLists.txt
> + $<$<AND:$<CXX_COMPILER_ID:MSVC>,$<CONFIG:RELEASE>>:/Zi>
I tried to use backslashes for this and it doesn't work, that's why I duplicate the conditions to have each flag on a separate line.
If someone wants to add a new flag with other conditions, it feels easier to me to add a new line here rather than dealing with an other conditional block.

2021-04-26 17:04 UTC, RadWolfie approved these changes

2021-04-26 20:00 UTC, PatrickvL approved these changes

2021-04-26 20:01 UTC, merged