Change IVB to an array of 4-float slots
Cxbx-Reloaded/Cxbx-Reloaded pull request #2215
Opened 2021-05-06 13:08 UTC by NZJenkins

Will fix Halo logo and menu text rendering (once it's visible!)
- Remove references to fixed function concepts, since slots might contain anything
e.g. don't exclude the 4th component of the slot corresponding to NORMAL in fixed function mode
- Use the IVB table directly for simplicity. Copy all table data to the vertex buffer

2021-05-06 13:30 UTC, PatrickvL requested changes
Wow, soo much code that can be removed - beautiful!

Only a few small remarks. Well done!

2021-05-06 13:30 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexBuffer.cpp
> +		uiStride += sizeof(float) * 4;
This won't ever differ from one draw to the other, so could be initialized once (which would shave off some per-draw overhead).

2021-05-06 13:30 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexBuffer.cpp
> +		int index = Register == X_D3DVSDE_VERTEX ? 0 : Register;
Replace `0` (zero) by `X_D3DVSDE_POSITION`, please.

2021-05-06 13:30 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexBuffer.cpp
> +	if (Register >= X_D3DVSDE_VERTEX && Register <= X_VSH_MAX_ATTRIBUTES) {
How can this ever work correctly, given `X_D3DVSDE_VERTEX = 0xFFFFFFFF`, while `X_VSH_MAX_ATTRIBUTES` is 16?

2021-05-06 21:15 UTC, NZJenkins commented on src/core/hle/D3D8/XbVertexBuffer.cpp
> +	if (Register >= X_D3DVSDE_VERTEX && Register <= X_VSH_MAX_ATTRIBUTES) {
As an int that's -1 (as long as we're 32bit?)
Yeah this can be made clearer

2021-05-06 23:01 UTC, medievil1 commented
KOTOR breaks....
![image](https://user-images.githubusercontent.com/38597905/117375677-7d498200-ae9d-11eb-9a4b-0907995be4f5.png)

2021-05-08 00:56 UTC, medievil1 commented
actually KOTOR is kinda broken on master so it could be a different commit responsible

2021-05-12 13:47 UTC, PatrickvL commented
@medievil1 thanks for looking into this. It'd be great if we could figure out the root cause for the issue you've observed and investigated, because this is one of those changes that would be very beneficial to have merged

2021-05-12 13:48 UTC, PatrickvL commented
It might be a memory corruption issue, possibly related to multi threading and resizing buffers

2021-05-13 11:53 UTC, dreimer1986 commented
Emulating MS-004 v1.09 (Halo) The log is bombed with

[0x1B74] WARN : VTXB    Unknown IVB Register : 9
[0x1B74] WARN : VTXB    Unknown IVB Register : 4
[0x1B74] WARN : VTXB    Unknown IVB Register : 9
etcetcetc

2021-05-16 09:59 UTC, NZJenkins commented
> KOTOR breaks....

> It might be a memory corruption issue, possibly related to multi threading and resizing buffers

It turned out it was that I've bound all 16 slots in here, but 13-15 are unsupported/unused by the fixed function pipeline.
For slots 13-15, `Xb2PCRegisterType` returns `D3DDECLUSAGE_UNSUPPORTED` ... will just return a TEXCOORD semantic

> Emulating MS-004 v1.09 (Halo) The log is bombed with
>
> [0x1B74] WARN : VTXB    Unknown IVB Register : 9

Thanks - I'd misplaced an `else` block!

2021-05-16 10:20 UTC, NZJenkins commented on src/core/hle/D3D8/XbVertexBuffer.cpp
> +	if (Register >= X_D3DVSDE_VERTEX && Register <= X_VSH_MAX_ATTRIBUTES) {
declared `X_D3DVSDE_VERTEX` as -1 instead

2021-05-16 10:49 UTC, PatrickvL approved these changes
Besides the potential to pre-initialize some stuff, this looks fine. Great work!

2021-05-16 11:13 UTC, PatrickvL commented
If you're really worried about vertex buffer bandwidth overhead, we may need to retain `g_InlineVertexBuffer_WrittenRegisters`, and generate and cache different vertex declarations. When the stride stays the same, we can all still use the same single buffer, or we could declare one buffer per attribute (that would have my preference).

2021-05-16 12:57 UTC, PatrickvL commented
I think this is ready for merge now, after some more testing.

@medievil1 could you re-test KOTOR and see if it still crashes, or now works okay?

2021-05-16 16:28 UTC, medievil1 commented
still some issues
![image](https://user-images.githubusercontent.com/38597905/118404755-33e9f700-b642-11eb-9d3c-0fa9a5075f39.png)
![image](https://user-images.githubusercontent.com/38597905/118404762-3d735f00-b642-11eb-9856-bac8196b21de.png)
it is only partially rendering

2021-05-17 07:15 UTC, NZJenkins commented
Fixed 0 stride introduced in the last commit

2021-05-17 15:39 UTC, PatrickvL approved these changes
LGTM!

2021-05-17 15:55 UTC, merged