Change Memory/buffer release order. delete X_CDirectSoundStream*   when ref. count decrease to 0
Cxbx-Reloaded/Cxbx-Reloaded pull request #2236
Opened 2021-06-08 12:51 UTC by jackchentwkh

Change Memory/buffer release order to the reverse order of creation. 
delete X_CDirectSoundStream*   pThis in the 2nd call to CDirectSoundStream_Release(). 
this makes CrashTwinsanity happily ingame. 
somehow CrashTwinsanity calls CDirectSoundStream_Release twice with the same X_CDirectSoundStream*, and it only null out it's internal X_CDirectSoundStream* after the 2nd call of release. this modification makes it happy. so far no regressions with other titles. need further test.

2021-06-08 13:03 UTC, LukeUsher requested changes
Changing the order of operations is useful, but you shouldn't be freeing the related data structures without verifying the reference count is indeed 0.

2021-06-08 13:03 UTC, LukeUsher commented on src/core/hle/DSOUND/DirectSound/DirectSoundStream.cpp
> +            //delete pThis;
What happens if a game only calls Release once? Won't the pThis pointer leak? 

it might be worth checking the reference count (uRet) and deleting pThis when the reference count is zero.

2021-06-08 13:03 UTC, LukeUsher commented on src/core/hle/DSOUND/DirectSound/DirectSoundStream.cpp
> +                pThis->EmuDirectSoundBuffer8 = nullptr;
This might not be safe: You don't check that the reference count is 0 before erasing the pointer, Release may decrement the reference count, it *only* frees the buffer when it returns zero.

2021-06-08 13:03 UTC, LukeUsher commented on src/core/hle/DSOUND/DirectSound/DirectSoundStream.cpp
> +            if (pThis->EmuDirectSound3DBuffer8 != nullptr) {
Not safe: see comment on EmuDirectSoundBuffer8.

2021-06-09 01:02 UTC, jackchentwkh commented
original code flow:
if pThis!=nullptr && soundbuffer!=0
{
    ref=soundbuffer->release();
    //most guest code will have ref=0 here, no problem. some titles will have ref.=1 such as CrashTwinsanity and Halo, which will introduce trouble later when the guest code call dsstream_release twice with the same pthis
    if(ref==0) {
        packet_clear(); // we'll have access violation here if the guest code call DSStream_release twice with the same pThis. in the 2nd 
        call, the guest side buffer pointed by the packet is invalidate.
        DSStream_cache.erase()
        delete pThis.
    }
}

in the situation of DSStream_release called twice with same pThis, 
packet_clear will have access violation with xbox::XMEDIAPACKET access, like this code.         
 if (buffer->xmp_data.pdwStatus != xbox::zeroptr) {
        (*buffer->xmp_data.pdwStatus) = status;
the xbox::XMEDIAPACKET xmp_data is invalidated before the 2nd time DSStream_Release was called
which means the guest code removes those packets in the time between the fist call and 2nd call to DSStream_Release
if we don't clear host packet in the first call, further access violation might be introduced when the host side packets are being processed and the quest side clears the xbox::XMEDIAPACKET

2021-07-09 16:36 UTC, RadWolfie commented
Closing this pull request in favor of https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2257 mimic hack solution.

2021-07-09 16:36 UTC, closed without merging