fixing 3D mip-map conversion with volume texture, fix Halo
Cxbx-Reloaded/Cxbx-Reloaded pull request #2237
Opened 2021-06-10 03:43 UTC by jackchentwkh

using correct 3D mip map dimention sizes in all 3 dimensions, and calculate correct source size.
this fix Halo, get in game.

2021-06-10 06:22 UTC, PatrickvL approved these changes
Yes! You did it! Nicely done!

Please add a few screenshots for good measure, to mark this milestone

2021-06-10 06:25 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				dwMipOffset += pxMipDepth * dwMipSize;//for 3D volumeTexture, the dwDepth >1 in mip_level 0, pxMipDepth must be multiplied.
Do we have test cases for this? Asking, because in this commit, this is the only change I'm a little bit in doubt about...

2021-06-10 06:31 UTC, jackchentwkh commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				dwMipOffset += pxMipDepth * dwMipSize;//for 3D volumeTexture, the dwDepth >1 in mip_level 0, pxMipDepth must be multiplied.
frankly I don't know how to verify it neither. the I modify this code and test it directly with Halo then it work out of the box.
I have no idea how to verify whether it's correct or not can you give me some hint? or can you test halo for it?

2021-06-10 07:26 UTC, LukeUsher requested changes
Looks great! Nice work, but there's a couple of typos in the comments

2021-06-10 07:26 UTC, LukeUsher commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +							pSrc, pxMipWidth, pxMipHeight, dwMipRowPitch, dwMipSize,//use dwMipSize instaed of dwSrcSlicePitch here, because the mipSize changed in 3D mip map.
typo: instaed -> instead

2021-06-10 07:26 UTC, LukeUsher commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +							pxMipDepth,//usd pxMipDepth here because in 3D mip map the 3rd dimension also shrinked to 1/2 at each mip level.
typo: usd -> used or use

2021-06-10 07:26 UTC, LukeUsher commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					pxMipDepth /= 2;//this is for 3D volumeTexture mip-map, it shrinked down to 1/2 in 3 diemesions. this variable should be used.
typo: diemesions -> dimensions

2021-06-10 08:30 UTC, NZJenkins reviewed
nice find!

2021-06-10 08:30 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					dwCubeFaceSize += pxMipDepth * dwMipSize;
question: I know the change here is replacing `dwDepth` with `pxMipDepth`, and nothing else but...

Cubemaps shouldn't have depth - does what this code is doing make sense?
Why is the cube face size a special case? Isn't it just another 2D texture?

2021-06-10 08:30 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				dwMipOffset += pxMipDepth * dwMipSize;//for 3D volumeTexture, the dwDepth >1 in mip_level 0, pxMipDepth must be multiplied.
suggestion: again I _suspect_ mip size should include depth already

2021-06-10 08:30 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					pxMipDepth /= 2;//this is for 3D volumeTexture mip-map, it shrinked down to 1/2 in 3 diemesions. this variable should be used.
nitpick:
Not sure what is meant by
> this variable should be used

this pr adds a long comment at each change.

I think it'd be best to add comments about what these variables/data is, and make sure they're well defined.
Then what we do at every step should make more sense and need less comments.

In this case we are already dividing all the other dimensions by two, I don't think depth warrants a special comment here

2021-06-10 08:36 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				dwMipOffset += pxMipDepth * dwMipSize;//for 3D volumeTexture, the dwDepth >1 in mip_level 0, pxMipDepth must be multiplied.
> if there is a way to retrieve the src texture data and examine it with other tools, then it's possible to quickly verify this.

it's possible to examine textures in a frame capture and view each mip level. Can do this with Intel GPA

2021-06-10 08:41 UTC, jackchentwkh commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				dwMipOffset += pxMipDepth * dwMipSize;//for 3D volumeTexture, the dwDepth >1 in mip_level 0, pxMipDepth must be multiplied.
GPA only works for me the 1st time after installation. after that, it won't work. I am still struggle with it. as for this case, we're supposed to check the texture from guest, not host, GPA could only check the texture after conversion. but I would like to check the guest texture first.

2021-06-10 08:57 UTC, jackchentwkh commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +							pSrc, pxMipWidth, pxMipHeight, dwMipRowPitch, dwMipSize,//use dwMipSize instaed of dwSrcSlicePitch here, because the mipSize changed in 3D mip map.
at mip level 0, mipSize == dwSrcSlicePitch, but when mip level increases, the mipSize decreases accordingly, on the other hand, dwSrcSlicePitch never changes.  thus the source size per layer should follow mipSize instead of dwSrcSlicePitch when the mip_level loops to levels other than 0. you have to be aware that this conversion code is inside a for loop which loops through the mip levels. and the conversion code converts one mip level at a time.

2021-06-10 08:59 UTC, jackchentwkh commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					dwCubeFaceSize += pxMipDepth * dwMipSize;
I don't know cube maps. what I am dealing with Halo is volume texture. the case I am dealing with has width 0x20, height 0x20, depth 0x20.

2021-06-10 09:00 UTC, jackchentwkh commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				dwMipOffset += pxMipDepth * dwMipSize;//for 3D volumeTexture, the dwDepth >1 in mip_level 0, pxMipDepth must be multiplied.
nope, mipSize only calculates row_pitch X height

2021-06-10 09:03 UTC, jackchentwkh commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +					pxMipDepth /= 2;//this is for 3D volumeTexture mip-map, it shrinked down to 1/2 in 3 diemesions. this variable should be used.
yeah, for this specific comment I am actually leave it here for the ease of reviewing. 
because the MipDepth was devided by 2 at each mip level, which means the original code is aware of the 3D mip map.
but somehow the mipDepth wasn't used in the conversion, well, not in the toARGB conversion to be precise.

2021-06-10 09:26 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				dwMipOffset += pxMipDepth * dwMipSize;//for 3D volumeTexture, the dwDepth >1 in mip_level 0, pxMipDepth must be multiplied.
Hopefully it's easy to see if there was any issue converting the texture, even without a baseline. I'll have a look

2021-06-10 11:00 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +							pSrc, pxMipWidth, pxMipHeight, dwMipRowPitch, dwMipSize,//use dwMipSize instaed of dwSrcSlicePitch here, because the mipSize changed in 3D mip map.
Right. I guess it should've always been inside the loop.
Since that was the only use of `dwSrcSlicePitch`, it can be removed entirely! 🧹 

To confirm some terminology:
https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-textures-intro#3d-textures

The link refers to the mip-level aka slice of a 3D texture as 3D, which was my understanding.
But our conversion code refers to a slice as a single layer of a 3D texture i.e. width * height
IMHO best be consistent and track mip size in pixels as width * height * depth.
Then in the two other places we mip size, we don't have to multiply by depth.
We can divide by depth to make the existing conversion code happy

2021-06-11 09:20 UTC, LukeUsher approved these changes

2021-06-12 07:28 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +				dwMipOffset += pxMipDepth * dwMipSize;//for 3D volumeTexture, the dwDepth >1 in mip_level 0, pxMipDepth must be multiplied.
Got a capture and found a volume texture that looks good - no mipmap though apparently

2021-06-12 08:21 UTC, merged

2021-06-12 08:22 UTC, PatrickvL commented
Merged after confirmation from @NZJenkins 

Note, we still need to check whether volume mipmaps get converted correctly as well