Added support for memory unit devices
Cxbx-Reloaded/Cxbx-Reloaded pull request #2246
Opened 2021-06-21 23:34 UTC by ergo720

This adds support for a new input device, the memory unit (MU), which becomes available in the input gui when selecting the duke or S controller. For this cxbxr will now create a new folder called EmuMu in the same location where EmuDisk is created, and inside EmuMu there will be 8 folders, one for each MU. Regarding the internal code changes, this implements `XMountMUA`, `XMountMURootA`, `XUnmountMU`, `XReadMUMetaData` and extends the kernel functions `NtQueryVolumeInformationFile`, `NtDeviceIoControlFile` and `NtFsControlFile` to support MUs, in addition to the HDD. Testing is welcome.

2021-06-22 04:42 UTC, LanHikariDS commented
Can confirm that TimeSplitters 2 and TimeSplitters: Future Perfect read from/write to them flawlessly-
![image](https://user-images.githubusercontent.com/42668580/122864445-a8bfe900-d2f2-11eb-803c-cf22d00c38c3.png)
![image](https://user-images.githubusercontent.com/42668580/122864464-afe6f700-d2f2-11eb-8bbf-b0f7cf4e9750.png)

2021-06-22 17:39 UTC, RadWolfie requested changes
I had not made a full review, there's some changes need some fixes before I can re-review again.

I notice there are bunch of `dev1` and `port1` and the like which is not suitable to be use and lead confusion. Intead of using dev# and port#, they are actually iterator (in most cases), so using iDev and iPort, or i_dev and i_port, are preferred to be used.

2021-06-22 17:39 UTC, RadWolfie commented on src/core/kernel/support/EmuFile.cpp
> +	EmuNtSymbolicLinkObject *ret = FindNtSymbolicLinkObjectByDevice(DeviceCdrom0);
I highly recommend do not use `FindNtSymbolicLinkObjectByDevice` solution as it is not intended to be used at all. Instead it is replaced to `FindEmuDirPathByDevice`. Using our own `NtSymbolicLinkObject` objects should be last resort. In fact, FindNtSymbolicLinkObjectByDevice should techinically return list of `NtSymbolicLinkObject` objects. But symbolic link objects are not only target to drive letter. So, using `NtSymbolicLinkObject` only support to drive letters are entirely wrong.

In summary, our `NtSymbolicLinkObject` class and/or functions need a rework to support non-drive letters.

2021-06-22 17:46 UTC, RadWolfie commented
Beside code review, I tested the pull request's build with dashboard first, then Monopoly Party title.

I can confirm personalize MU names does work. And able to display the MU name in Monopoly Party title as seen below:

<details>
<summary>MU1A with personalize</summary>

![MU1A with personalize](https://user-images.githubusercontent.com/3938312/122973840-4b11b800-d357-11eb-8d44-77f4f728ac05.png)
</details>
<details>
<summary>MU1B without personalize (initialized by game title)</summary>

![MU1B without personalize](https://user-images.githubusercontent.com/3938312/122974241-b65b8a00-d357-11eb-918d-d9de71b5e9e4.png)
</details>

2021-06-25 15:55 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +			CxbxFormatPartitionByHandle(FileHandle);
I didn't mean by note "NOTE:", I meant by "HACK:" note.

2021-06-25 17:30 UTC, RadWolfie requested changes
Few code style changes and base on numerous to input mechanical not relative to memory unit devices. I recommended to perform full test with various titles that had been known to break in the past.

2021-06-25 17:30 UTC, RadWolfie commented on src/common/Settings.hpp
> +		int SlotType[2];
```suggestion
		int SlotType[XBOX_CTRL_NUM_SLOTS];
```
If not able to do above method, please add `XBOX_CTRL_NUM_SLOTS` in a comment on this line.

2021-06-25 17:30 UTC, RadWolfie commented on src/common/input/InputManager.h
> +};
Not a review remark, perhaps include microphone and keyboard (for PSO title) devices in a commented section?

2021-06-25 17:30 UTC, RadWolfie commented on src/common/input/InputManager.h
> +extern DeviceState g_devs[4 + 8];
```suggestion
extern DeviceState g_devs[4 + 4 * XBOX_CTRL_NUM_SLOTS];
```
imo, ^ will better than hardcode numbers.
Although, it appear we don't have macro for `XBOX_HW_NUM_PORT_SLOTS` or the like.

2021-06-25 17:34 UTC, ergo720 commented on src/common/input/SdlJoystick.cpp
> +				delete static_cast<int *>(Event.user.data1);
That's defined by SDL itself, I cannot change it.

2021-06-25 17:38 UTC, RadWolfie commented on src/core/hle/XAPI/Xapi.cpp
> +std::atomic<bool> g_bXppGuard = false;
I'm not sure if we need this additional guard?

> // Guard against the unfortunate case where XGetDevices or XGetDeviceChanges have already checked for g_bIsDevicesInitializing
	// and g_bIsDevicesEmulating and a thread switch happens to this function

Quote from `while (g_bXppGuard) {}` line.

Can't we simply check both booleans than rely on additional variable, g_bXppGuard?

2021-06-25 17:39 UTC, ergo720 commented on src/core/kernel/init/CxbxKrnl.cpp
> +
It cannot be put inside `g_InputDeviceManager.Shutdown();` because this is also called from the GUI, where `g_io_mu_metadata` doesn't exist. Also, this class has nothing to do with the input manager, it just regulates access to the MU partition headers.

2021-06-25 17:40 UTC, RadWolfie commented on src/common/input/SdlJoystick.cpp
> +				delete static_cast<int *>(Event.user.data1);
Strange, but ok SDL.

2021-06-25 17:45 UTC, RadWolfie commented on src/core/kernel/init/CxbxKrnl.cpp
> +
Okay, except MUs does have XPP type. So, it'll be wise to keep XPP types closely together and before memory manager's shutdown. As in memory manager should be the last one to shutdown as safe guard reason. Of course, before EmuShared's shutdown.

2021-06-25 17:46 UTC, ergo720 commented on src/common/input/InputManager.h
> +};
We could but, like the name says, this struct is meant to be used during the initialization code of the xbox controller window, to know which slot devices are to be displayed and we support. So, adding the unsupported devices, even if commented out, doesn't feel right to me, and can be easily added later when we will implement them.

2021-06-25 18:03 UTC, RadWolfie commented on src/common/input/InputManager.h
> +};
I don't agree with you. If you can remember, me and other guy had issues trying to find where SBC should be  placed at from existing defines. Beside, having commented out lines here as a "TODO" list will help better. And we do know both microphone and keyboard are insert into the controller's slots. By not having todo/notes here, we will eventually forget all over again. It is intended for a record.

2021-06-25 18:46 UTC, ergo720 commented on src/core/hle/XAPI/Xapi.cpp
> +std::atomic<bool> g_bXppGuard = false;
`UpdateXppState` is only called from `ConstructHleInputDevice` and `DestructHleInputDevice`, both of which set `g_bIsDevicesEmulating` to true. The unfortunate case happens when `XGetDevices` or `XGetDeviceChanges` are called, find `g_bIsDevicesEmulating = false`, proceed, but then a thread switch happens to `UpdateXppState`. Without the guard, the latter will concurrently access the xpp type, which might cause issues depending on which xpp type `XGetDevices` and `XGetDeviceChanges` are using.

2021-06-29 03:16 UTC, RadWolfie approved these changes
Known titles experienced regression in the past has pass test by our tester.

2021-06-29 03:16 UTC, merged