Added support for the lightgun input device
Cxbx-Reloaded/Cxbx-Reloaded pull request #2294
Opened 2021-11-20 21:02 UTC by ergo720

This adds support for a new input device, the lightgun, specifically the EMS TopGun II documented in the xboxdevwiki. The laser pointer of the gun is also emulated as a circle drawn as an Imgui overlay over the rendering window, so that players can know where they are shooting at on the rendering window. Note that this will only work with xbox games that use xinput to control the lightgun, and thus it won't work with chihiro games that use JVS input instead. Known xbox games that support lightguns are Starsky & Hutch, The House of the Dead III (xbox version) and Silent Scope Complete.

2021-11-21 02:25 UTC, LanHikariDS commented
Tested against GunValkyrie and Steel Battalion, two titles that had controller issues that were fixed. Neither title shows input-based regressions in this PR.

2021-11-28 11:11 UTC, LukeUsher approved these changes

2021-11-28 19:50 UTC, PatrickvL commented on src/common/input/InputDevice.h
> +	// NOTE: using SetPort2 to avoid a collision with the SetPort macro provided by Windows headers
Good catch, but it might be better to `#undef SetPort` instead of avoiding the name?

2021-11-28 19:51 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
>  	m_imgui->DrawMenu();
Much of this code is repeated in pgraph, perhaps it's possible to move both copies into a single source file (of that allows reuse of the same code)?

2021-11-28 19:52 UTC, PatrickvL commented on src/devices/video/EmuNV2A_PGRAPH.cpp
>  	m_imgui->DrawMenu();
Much of this code also appears in Direct3D.cpp, consider moving this to a shared location

2021-11-28 19:54 UTC, RadWolfie requested changes

2021-11-28 19:54 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlHal.cpp
> +			g_EmuShared->SetLightgunLaser(&g_devs->info.ligthgun.laser);
Not a review remark, usually we save them directly whenever state has change. Although, I do understand the reason to place it here as EmuShared doesn't have kernel function type to sync anything that is not real-time update.

nit: Doing this way will only remember port 1's laser state. Therefore will produce a bug if users are using port 2 - 4 instead. (Such as myself usually do testing pull request's relative input changes on port 3 and 4.) If we are going to merge as-is with this change. I recommended to create ticket for a reminder to fix this.

Also, can we expand InputManager to perform lightgun's saving state? Such as verify if the device is lightgun then save it.

---

EDIT: Actually, I notice there's a union for SBC and lightgun. So, this change is not right.

2021-11-28 19:54 UTC, RadWolfie commented on src/core/common/imgui/ui.cpp
> +		ImColor(ImVec4(1.0f, 1.0f, 0.0f, 1.0f))  // ply4: yellow
nit: use full name instead of ply.

2021-11-28 19:54 UTC, RadWolfie commented on src/common/win32/EmuShared.h
> +		uint8_t      m_LightgunLaser;
nit: This state can stored only one lightgun device instead of up to 4 lightgun devices base on total ports available on hardware.

Plus House of the Dead III's cover art state it can support up to 2 players. Same thing with Starsky & Hutch title, except one being driver and other being shooter (lightgun).

2021-11-28 19:54 UTC, PatrickvL commented on src/core/hle/XAPI/Xapi.cpp
> +			ret = ERROR_NOT_SUPPORTED;
Does Phantasy star online also call this on the keyboard device? In that case a similar note as above might be appropriate

2021-11-28 20:00 UTC, PatrickvL approved these changes
Only a few small remarks, and admittedly I didn't review very thoroughly, but this looks fine

2021-11-28 20:38 UTC, RadWolfie commented on src/core/hle/XAPI/Xapi.cpp
> +			ret = ERROR_NOT_SUPPORTED;
`XInputSetLightgunCalibration` function doesn't exist in PSO title since there's no lightgun support for it.

2021-11-29 10:29 UTC, ergo720 commented on src/common/input/InputDevice.h
> +	// NOTE: using SetPort2 to avoid a collision with the SetPort macro provided by Windows headers
That `undef` was already used in `InputManager.h` , but I decided to remove it in favor of changing function name, just like we do for `LOG_LEVEL::ERROR2` + even with the `undef`, when switching to this file, IntelliSense will still report this as a macro anyway.

2021-11-29 12:08 UTC, ergo720 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
>  	m_imgui->DrawMenu();
Maybe, however I fell like that should be done in a separate PR instead of here.

2021-11-29 12:16 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlHal.cpp
> +			g_EmuShared->SetLightgunLaser(&g_devs->info.ligthgun.laser);
> Not a review remark, usually we save them directly whenever state has change.

There's no need to save this variable whenever it changes, because its state is already saved in `g_devs[port].info.ligthgun.laser`. I only need to store it in EmuShared so that it survives the reboot. And yes, it should indeed check if a lightgun is connected and the state should be saved on a per-port basis.

2021-11-29 13:54 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
>  	m_imgui->DrawMenu();
Yeah, sure. Now that you've nicely moved the `DrawLightgunLaser` calls into `DrawWidgets`, this refactoring suggestion no longer applies to this PR anymore anyway.

2021-11-29 13:54 UTC, PatrickvL commented on src/devices/video/EmuNV2A_PGRAPH.cpp
>  	m_imgui->DrawMenu();
Above remark no longer applies.

2021-11-29 13:54 UTC, PatrickvL approved these changes

2021-11-29 18:28 UTC, RadWolfie approved these changes
LTGM

2021-11-29 18:33 UTC, merged