Updated Ps kernel functions to use Ob handles + unpatch thread XAPI functions + added APC support to kernel via Ob
Cxbx-Reloaded/Cxbx-Reloaded pull request #2315
Opened 2022-01-27 23:51 UTC by ergo720

This PR rewrites the kernel thread code to make use of Ob handles, instead of native ones. It also properly implements PsQueryStatistics and enables the execution of thread notification routines. These changes make it possible to unpatch SetThreadPriority, GetThreadPriority, SetThreadPriorityBoost, GetExitCodeThread and XSetProcessQuantumLength. Finally, this updates NtQueueApcThread to deliver APCs with the kernel, instead of just forwarding to ntdll, which also allows the removal of the thread handle duplication hack that was in place for it before.

One thing I notice is that this seems to apparently break the dashboard for me, which now goes to the fatal error screen instead of booting. However Radwolfie is not able to reproduce the issue, so this needs testing from the community.

2022-01-28 07:12 UTC, NZJenkins commented
This seems to break Amped (crash during level select), which was fixed in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2146

2022-01-28 16:33 UTC, RadWolfie commented
@NZJenkins, eventually all of handles will be managed by Ob's handle manager. In my opinion, we should accept any form of regressions from handles without add/re-implement hacks to safeguard Windows' handles. It may take about couple weeks to a month worth to resolve regressions relative to handles.

2022-01-28 16:45 UTC, PatrickvL requested changes
Tried to be thorough on this review - although there's only one actual bug (or so I assume)

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +template<bool NoConversion>
For clarity, consider inverting this boolean into `DoConversion` (obviously, also invert the default argument declaration and all calls)

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +	if (xhandle == NtCurrentThread()) {
This special case only applies to thread-handles, which introduces a chance for a false positive match on non-thread handles. How could we avoid this? Perhaps via an additional template boolean `ForThreads`?

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		if (xhandle == xbox::PspGetCurrentThread()->UniqueThread) {
Here a false-positive match could also occur for non-thread handles...

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +				if (g_pfnThreadNotification[i]) {
Should access to `g_pfnThreadNotification` be made thread-safe / locked?

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		}
Are we sure that the original xbox kernel doesn't set this variable until after above check? Or should it be set before that check?

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		RegisterXboxHandle(eThread->UniqueThread, handle);
Surely this needs to register `ThreadId` ?

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		}
Consider extracting this calling of thread notification routines into a separate method, named `PspCallThreadNotificationRoutines` or something like that, as this code appears in both `PsCreateSystemThreadEx` and `PsTerminateSystemThread` (just pass in the `Create` boolean as an argument, which is the only difference between the two current implementations).

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +			g_pfnThreadNotification[i] = NotifyRoutine;
Should access to `g_pfnThreadNotification` be made thread-safe / locked?

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +	}
Consider extracting this calling of thread notification routines into a separate method, named `PspCallThreadNotificationRoutines` or something like that, as this code appears in both `PsCreateSystemThreadEx` and `PsTerminateSystemThread` (just pass in the `Create` boolean as an argument, which is the only difference between the two current implementations).

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +	EmuKeFreeThread(ExitStatus);
Is this called for "cxbxr threads that execute xbox code"? Does that apply here? Please elaborate on this call in a comment.

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +		Dummy = static_cast<xbox::PBYTE>(Pcr->NtTib.StackBase) - 12;
Granted, this code was merely reindented, but please consider replacing the magic number 12 by a descriptively named constant, and use that everywhere it applies to.

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +		xbox::NtClose(eThread->UniqueThread);
No need to dereference the variable anymore, now that it resides in the local `UniqueThread` variable (likely compiled into a register value) - so use that instead (unless threading requires re-reading the source variable each time?)

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +			xbox::RtlZeroMemory(EThread, sizeof(xbox::ETHREAD));
The end-of-line comment belongs either on a separate line, or behind the actual zeroing-call.

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +			EThread->UniqueThread = reinterpret_cast<xbox::HANDLE>(GetCurrentThreadId());
Could this assignment cause confusion on further use of `EThread->UniqueThread`?

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +			EThread->UniqueThread = reinterpret_cast<xbox::HANDLE>(GetCurrentThreadId());
Also, is `GetCurrentThreadId()` a native ThreadId? Or should it be the `-2` from `#define NtCurrentThread() ((HANDLE)-2)` ?

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> -		EThread->UniqueThread = GetCurrentThreadId();
Am I right to understand that when `EThread` is non-null, this `UniqueThread` field is already set by `PsCreateSystemThreadEx` to the "ob handle of the ethread obj"? This might be a valuable comment...

2022-01-28 16:45 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		}
When does this case actually happen? When there's a collision between an obsolete handle still being present and a new identical handle being added?? This might need some more comments to become clear.

2022-01-28 16:57 UTC, RadWolfie commented on src/core/hle/XAPI/Xapi.cpp
> -	// titles don't come this far as-of yet.
No need for test, XLaunchNewImageA had been unpatched since 2017.

2022-01-28 16:58 UTC, RadWolfie commented on src/core/hle/XAPI/Xapi.cpp
> -				PopupInfo(nullptr, "The title is rebooting to dashboard");
Unused since 2017

2022-01-28 17:02 UTC, ergo720 commented on src/core/kernel/common/ps.h
> +XBSYSAPI EXPORTNUM(259) OBJECT_TYPE PsThreadObjectType;
Because it's wrong, `PsThreadObjectType` does not have the volatile qualifier. https://github.com/XboxDev/nxdk/blob/587177545f309695f47f364c173baa1df5413879/lib/xboxkrnl/xboxkrnl.h#L2326

2022-01-28 17:02 UTC, PatrickvL commented on src/core/hle/XAPI/Xapi.cpp
> -	// titles don't come this far as-of yet.
Ah, it wasn't enclosed in an `#if 0`, so I didn't check if it actually appeared in the patches list.
Still can't hurt to see if these test cases still work...

2022-01-28 17:04 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlKe.cpp
> +	assert(Pcr);
The comment above it explains it: if it ever happens, it's a bug and should be fixed instead of trying to handle it. Also note that this function is called very frequently in the thread code, so this check is probably costly.

2022-01-28 17:05 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +			status = ObReferenceObjectByHandle(SourceHandle, zeroptr, &Object);
It's unnecessary as our Ob's system are starting to use more of `ObReferenceObjectByHandle`. If unsure what 2nd parameter is, using function's list of references will tell you what it is or at least go in the function's definition to tell easier.

2022-01-28 17:06 UTC, PatrickvL commented on src/core/hle/XAPI/Xapi.cpp
> -				PopupInfo(nullptr, "The title is rebooting to dashboard");
Again, I didn't verify whether `XLaunchNewImageA` still appeared in the list of registered patches. Even so, the remark about this popup still stands - we could still make it reappear in `HalReturnToFirmware` if we want to have some feedback on a reboot (perhaps only in debug runs, but still)...

2022-01-28 17:09 UTC, RadWolfie commented on src/core/kernel/support/NativeHandle.cpp
> +	if (xhandle == NtCurrentThread()) {
Windows doesn't accept non-speical handle for current thread. Therefore require to preserve the special handle. This is the only occur in threading situation. Everything else is handled by xbox's Ob handle.

2022-01-28 17:10 UTC, RadWolfie commented on src/core/kernel/support/NativeHandle.cpp
> +		if (xhandle == xbox::PspGetCurrentThread()->UniqueThread) {
It is not false positive... each handle are unqiue there are no same handle values given at any time.

2022-01-28 17:14 UTC, PatrickvL commented on src/core/kernel/common/ps.h
> +XBSYSAPI EXPORTNUM(259) OBJECT_TYPE PsThreadObjectType;
Okay, if that reference is accurate, then fine. Just wanted to make sure 😉

2022-01-28 17:15 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlKe.cpp
> +	assert(Pcr);
If you're sure the 'salvage' path was never relied upon, then fine. It's just that there's no mention of test-cases, so we can't verify.

2022-01-28 17:16 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		RegisterXboxHandle(eThread->UniqueThread, handle);
No, because that can always be retrieved later at any time with `GetCurrentThreadId`. In addition, registering the thread handle allows this code to work `GetNativeHandle(PspGetCurrentThread()->UniqueThread)`, so we can always retrieve the native handle of the current thread anywhere in the code, instead of the thread id which is not useful since the majority of win api use the thread handle instead of the id.

2022-01-28 17:17 UTC, ergo720 commented on src/core/kernel/support/EmuFS.cpp
> +			EThread->UniqueThread = reinterpret_cast<xbox::HANDLE>(GetCurrentThreadId());
Native thread id.

2022-01-28 17:18 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +			status = ObReferenceObjectByHandle(SourceHandle, zeroptr, &Object);
Mentioning the argument name when the value is non-descriptive, has been a coding convention - I was just wondering why it was removed. And indeed, a lookup of arguments is always possible, but that requires interaction in an editor, hindering the ease of reading, while the comment was right there already.

2022-01-28 17:19 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +	if (xhandle == NtCurrentThread()) {
Perhaps @ergo720 wants to respond. `GetNativeHandle` is an emulator function, not a WinAPI or xbox function.

2022-01-28 17:22 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		if (xhandle == xbox::PspGetCurrentThread()->UniqueThread) {
I'm not entirely sure, but it looks like multiple threads might have `UniqueThread` set to -2, which no longer makes it a unique value. (I do admit there's little to no chance -2 or $FFFFFFFD will ever be returned legitimately.)

2022-01-28 17:23 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		RegisterXboxHandle(eThread->UniqueThread, handle);
In my opinon, there should be two different handles. Using same `handle` is likely to trigger an issue for Windows making a close once unless `handle` from Windows has a 2nd increment in some way.

2022-01-28 17:23 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		RegisterXboxHandle(eThread->UniqueThread, handle);
Ah, indeed! That's clever, and should probably be documented in a comment!

2022-01-28 17:28 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +			status = ObReferenceObjectByHandle(SourceHandle, zeroptr, &Object);
Because it's useless imo, otherwise, we should have to add it whenever `ObReferenceObjectByHandle` is called, which will happen more and more in the code base as we switch to Ob handles.

2022-01-28 17:28 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +				status = ObOpenObjectByPointer(Object, OBJECT_TO_OBJECT_HEADER(Object)->Type, TargetHandle);
Because it's useless imo, otherwise, we should have to add it whenever `ObOpenObjectByPointer` is called, which will happen more and more in the code base as we switch to Ob handles.

2022-01-28 17:30 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlNt.cpp
> -	// without it.  Other SNK games might use it also, beware.
There is only a single test case, Metal Slug 3, which calls `NtQueueApcThread`, that I'm aware off.

2022-01-28 17:34 UTC, ergo720 commented on src/core/kernel/support/NativeHandle.cpp
> +		if (xhandle == xbox::PspGetCurrentThread()->UniqueThread) {
`UniqueThread` is an xbox handle handed out by Ob, it cannot be a non-thread handle.

2022-01-28 17:35 UTC, RadWolfie commented on src/core/kernel/support/NativeHandle.cpp
> +		if (xhandle == xbox::PspGetCurrentThread()->UniqueThread) {
> but it looks like multiple threads might have UniqueThread set to -2

If that's the case, then it is a bug. However, I had not seen any place where UniqueThread used for -2 when I was working with @ergo720.

2022-01-28 17:37 UTC, ergo720 commented on src/core/kernel/support/NativeHandle.cpp
> +		}
I saw it happening in the dashboard, because of the reason explained in the comment.

2022-01-28 17:38 UTC, RadWolfie commented on src/core/kernel/support/NativeHandle.cpp
> +		}
pinging @ergo720 for ^

2022-01-28 17:42 UTC, RadWolfie commented on src/core/hle/XAPI/Xapi.cpp
> -	// titles don't come this far as-of yet.
See pull request https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/721, they had been working ever since. ;P

2022-01-28 17:49 UTC, RadWolfie commented on src/core/kernel/support/EmuFS.cpp
> +		xbox::NtClose(eThread->UniqueThread);
Honestly, this is how kernel works and there is a check for `UniqueThread` which is happening I believe in XAPI's function.

2022-01-28 17:51 UTC, ergo720 commented on src/core/kernel/support/NativeHandle.cpp
> +		if (xhandle == xbox::PspGetCurrentThread()->UniqueThread) {
Well, except for the case this is an xbox thread converted from a host thread, that is, not created by the title with `PsCreateSystemThread`. In that case, `UniqueThread` will be the value returned by `GetCurrentThreadId`, so a native handle. @PatrickvL I strongly doubt the ob manager will ever hand out a -2 = 0xFFFFFFFE handle. It starts at zero and increases by 4 at every new handle it creates.

2022-01-28 18:01 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnl.cpp
> -xbox::KPCR* WINAPI KeGetPcr();
The original problem was because of WINAPI, which is only declared in the windows headers and thus becomes undefined when those are not included. Using NTAPI fixes it because we define that macro ourselves in our xbox headers. I did the renaming because similar functions in EmuFs are prefixed with Emu. Plus this function really only works with the emulator, since it's accessing the fs segment at the arbitrary slot, which is not how it works on hardware.

2022-01-28 18:08 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlKi.cpp
> +		// NOTE: we never use KernelRoutine
Because kernel APCs are only used internally by the kernel, while `NtQueueApcThread` (the only functions available to titles to use APCs), always creates a user APC. Since we never use kernel APCs in our kernel at the moment, there's no reason to use `KernelRoutine` at this time.

2022-01-28 18:18 UTC, ergo720 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> -                    }
Well, this is dead code because of the reasons explained in https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2217. So, we are not losing functionality because this doesn't work anyway.

2022-01-28 18:26 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> -                    }
In my opinion, we are still receving eary crash on reboot process due to the fact xbox threads are still running. We should terminate them before we shut down our emulation process. Doing so will prevent any false positive reports.

2022-01-28 18:35 UTC, ergo720 commented on src/core/kernel/support/EmuFS.cpp
> -		EThread->UniqueThread = GetCurrentThreadId();
Yes, this is documented in a comment I added inside `EmuGenerateFS`

2022-01-28 18:39 UTC, ergo720 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> -                    }
Those crashes are only visible with the debugger, because they only occur in the split of a second after `TerminateProcess` is called and the code still runs. Since the process is going to be killed right now, users will never see the crash anyway.

2022-01-31 10:49 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +				if (g_pfnThreadNotification[i]) {
No, the kernel uses the thread notification routines at passive level with no locks acquired, so we shouldn't either.

2022-01-31 11:50 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		}
This is just checking if the title wants to have the thread id. If it doesn't, `ThreadId` will be nullptr and setting it unconditionally will cause a crash in that case. Also, `eThread->UniqueThread` is set above with the call to `ObInsertObject` when successful, and if it fails, we won't even reach here.

2022-01-31 12:27 UTC, ergo720 commented on src/core/kernel/support/EmuFS.cpp
> +			EThread->UniqueThread = reinterpret_cast<xbox::HANDLE>(GetCurrentThreadId());
No, there's a comment above which explains this is for host threads used as xbox threads.

2022-01-31 12:34 UTC, ergo720 commented on src/core/kernel/support/EmuFS.cpp
> +		Dummy = static_cast<xbox::PBYTE>(Pcr->NtTib.StackBase) - 12;
Honestly, I'm not sure which name I should give it, this is just used to make the TLS have a 16 byte alignment, like the comment just above explains.

2022-01-31 12:44 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +	EmuKeFreeThread(ExitStatus);
This must always be called for both kinds of threads, to free the common resources that have been allocated for the thread.

2022-01-31 12:49 UTC, ergo720 commented on src/core/kernel/support/NativeHandle.cpp
> +template<bool NoConversion>
The normal (and most common) case for `GetNativeHandle`, is to do the conversion, while the special case is not to convert `NtCurrentThread` and return it as is. So, in my opinion, it's clearer the way it is now.

2022-01-31 14:09 UTC, PatrickvL commented on src/core/hle/XAPI/Xapi.cpp
> -	// titles don't come this far as-of yet.
There's no mention of Innocent tears in #721, but I'll take your word for it.

2022-01-31 14:14 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlKi.cpp
> +		// NOTE: we never use KernelRoutine
Ah, understood. Thanks. Then best change the comment into "NOTE: we don't use KernelRoutine yet"

2022-01-31 14:15 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +			status = ObReferenceObjectByHandle(SourceHandle, zeroptr, &Object);
Alright. Let's agree to disagree on the usefulness of this convention then ;)

2022-01-31 14:19 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlNt.cpp
> -	// without it.  Other SNK games might use it also, beware.
Okay, but the remark "Other SNK games might use it also" implies there might still be other test-cases, although I admit it's impossible to mention what's unknown until now. But at least mention "Metal Slug 3" as a "must-test title" in the Pull Request description.

2022-01-31 14:20 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +template<bool NoConversion>
Fine by me!

2022-01-31 14:28 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +	if (xhandle == NtCurrentThread()) {
Okay, as long as `NtCurrentThread()` returns `-2`, and all handles that are returned to xbox code are derived from the memory addresses where our kernel allocated the kernel Ob'jects, it's indeed impossible for those values to match (as we'll never allocate an object at memory address -2).

2022-01-31 14:31 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		if (xhandle == xbox::PspGetCurrentThread()->UniqueThread) {
Yeah, -2 won't ever be a valid Ob memory address.

2022-01-31 14:33 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		}
Yeah, that I understand, but I was referring to the preceding check (on `if (!X_NT_SUCCESS(result)) {`) - perhaps the original xbox kernel already assigns `*ThreadID` *before* that check

2022-01-31 14:36 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +	EmuKeFreeThread(ExitStatus);
Oh, that wasn't clear to me, because a comment in `EmuKeFreeThread` states : `This functions is to be used for cxbxr threads that execute xbox code`, which sentence I now understand has to be expanded with : ` and xbox threads created via PsCreateSystemThread(Ex)`

2022-01-31 14:43 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +		Dummy = static_cast<xbox::PBYTE>(Pcr->NtTib.StackBase) - 12;
Perhaps something like `NTTIB_STACKBASE_ALIGNMENT`? But whatever name we use, it's *having* a symbol name that's important, because once it appears everywhere our code currently has this magic 12, we can (A) easily find all places in code where it applies to this alignment, (B) we have a single declaration that can have a comment why the alignment is set to 12, and (C) other occurrences of the magic value 12 will no longer be misunderstood to have something to do with this alignment.

2022-01-31 14:48 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +		xbox::NtClose(eThread->UniqueThread);
Eh, how's "this is how kernel works" an answer to the suggestion? What kernel are you referring to? And why does it presumably read the same field three times in a row, while there's already a local variable where we read this field into? Again, I simply suggest to avoid repeated identical memory reads by using the local variable instead of the referenced field.

(Unless, as I stated above, it is a requirement because of some thread-safety concern, but in that case it would help to have a detailed comment explaining the potential problem that could arise if we don't re-read the field each time.)

2022-01-31 14:54 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +			EThread->UniqueThread = reinterpret_cast<xbox::HANDLE>(GetCurrentThreadId());
Oh, excuse me, I meant to ask : How high is the chance that this assignment of a host value, ever gets confused (and could thus potentially cause false positive matches), with the value we assigned to `UniqueThread` in `PsCreateSystemThreadEx` (via a call to `ObInsertObject`)?

2022-01-31 14:56 UTC, PatrickvL commented on src/core/kernel/support/EmuFS.cpp
> +			EThread->UniqueThread = reinterpret_cast<xbox::HANDLE>(GetCurrentThreadId());
Okay, thanks. (This confirmation made me write a followup question in the preceding conversation.)

2022-01-31 15:07 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +				status = ObOpenObjectByPointer(Object, OBJECT_TO_OBJECT_HEADER(Object)->Type, TargetHandle);
Alright. Let's agree to disagree on the usefulness of this convention then ;)

2022-01-31 15:11 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +				if (g_pfnThreadNotification[i]) {
Ehm, isn't it possible that 'passive level' can get replaced by another level, as long as we don't manage thread-switching ourselves? Even worse, when the multi-core hack is in effect, xbox code could be running simultaneously on multiple cores, so we can't rely on the same safety guarantees as an original xbox kernel...

2022-01-31 16:29 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		}
No, it's only done if `ObOpenObjectByPointer` succeeds (which is what the check above is for). If that is unsuccessful, it means that the thread creation failed, and thus there's no point in setting the thread id either.

2022-01-31 17:39 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		}
Great - if that's what the original xbox kernel also does, then this is fine

2022-02-01 08:54 UTC, PatrickvL requested changes
A partial review, after yesterdays new commits

2022-02-01 08:54 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +			g_pfnThreadNotification[i] = NotifyRoutine;
For thread safety, prepend `std::unique_lock lck(PspThreadNotificationMtx);` here (and probably, do a global rename of `PspThreadNotificationMtx` into `g_ThreadNotificationMtx`).

2022-02-01 08:54 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +	if (eThread->UniqueThread && g_iThreadNotificationCount) {
Please move the check on `g_iThreadNotificationCount` into `PspCallThreadNotificationRoutines` (and in there, right after the mutex is entered), so that will be thread-safe as well.

2022-02-01 08:54 UTC, PatrickvL commented on src/core/hle/XAPI/Xapi.cpp.unused-patches
> +			CxbxrKrnlAbort("Too many thread notification routines installed\n");
For thread safety, prepend `std::unique_lock lck(PspThreadNotificationMtx);` here (and probably, do a global rename of `PspThreadNotificationMtx` into `g_ThreadNotificationMtx`).

2022-02-01 08:54 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		// Call the thread notification routine(s)
This comment can be removed (the function call itself already conveys the same information).

2022-02-01 08:54 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		}
Please move the check on `g_iThreadNotificationCount` into `PspCallThreadNotificationRoutines` (and in there, right after the mutex is entered), so that will be thread-safe as well.

2022-02-01 08:54 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +	for (int i = 0; i < PSP_MAX_CREATE_THREAD_NOTIFY; i++) {
Please move all remote checks on `g_iThreadNotificationCount` to here (between entering the mutex and performing the for loop).

2022-02-01 08:54 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnl.cpp
> +			SwitchToThread();
Please also call `SwitchToThread` instead of the `Sleep(0)`'s in `xbox::KeWaitForMultipleObjects` and `xbox::KeWaitForSingleObject`.

Note, that our use of `Sleep(0)` is always meant to force a thread-switch, and some of our use of `Sleep(1)` are meant to do that too. However, in selected cases, `Sleep(1)` (and higher constant numbers) it's used to just pause a little while. (There's even a comment in our code explaining this : `// TODO : Improve performance replacing Sleep(1) with YieldProcessor`)

2022-02-01 10:56 UTC, ergo720 commented on src/core/hle/XAPI/Xapi.cpp.unused-patches
> +			CxbxrKrnlAbort("Too many thread notification routines installed\n");
Not sure if you have noticed, but this is the dead code of the unused xapi patches, and thus, it doesn't need any of that. In addition, this code is just wrong: it uses 16 notification routines instead of 8, and it mistakenly aborts the emulation when it exceeds the limit, when is should just return `STATUS_INSUFFICIENT_RESOURCES`

2022-02-01 11:22 UTC, PatrickvL commented on src/core/hle/XAPI/Xapi.cpp.unused-patches
> +			CxbxrKrnlAbort("Too many thread notification routines installed\n");
Oh crap - this comment was meant for `PsSetCreateThreadNotifyRoutine` only

2022-02-01 22:34 UTC, medievil1 commented
is this suppose to be functional? for me, every game closes back to cxbx ui

2022-02-02 12:00 UTC, ergo720 commented
@medievil1 With the exception of the dashboard, all games work like before for me, so I'm not sure what your issue might be. One thing I notice however, is that performance dropped considerably compared to master. It now takes a couple of minutes to start any game, because the call to `_beginthreadex` seems to take much longer than it does on master. Also, stopping the emulation now takes a couple of seconds instead of being instantaneous, and that is because of the thread suspending code that was added in some commits. However, since it hurts the user's experience and there's little benefit in it, I'm keen to remove it in the future.

2022-02-02 19:50 UTC, medievil1 commented
> @medievil1 With the exception of the dashboard, all games work like before for me, so I'm not sure what your issue might be. One thing I notice however, is that performance dropped considerably compared to master. It now takes a couple of minutes to start any game, because the call to `_beginthreadex` seems to take much longer than it does on master. Also, stopping the emulation now takes a couple of seconds instead of being instantaneous, and that is because of the thread suspending code that was added in some commits. However, since it hurts the user's experience and there's little benefit in it, I'm keen to remove it in the future.

very odd then cause I have tried multiple times, even new instance/folder instead of reading caps it craps out, no error, while master and other pr's run fine... I will pull the debug version and see if I can see more detail

2022-02-03 00:03 UTC, RadWolfie commented
> is this suppose to be functional? for me, every game closes back to cxbx ui

We recently became aware of this, two of us are able to reproduce the issue (sort of). Except we are not able to use debugger to pinpoint where silent crash occur or self terminated. We will need some extra time to figure out the cause. Thank you for bringing it to our attention. 🙂

Using loader or non-loader method has the same issue without debugger attached.

2022-02-06 11:08 UTC, ergo720 commented
I can confirm that https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2315/commits/c6672f6fbcc5b21bc95d4c407e6e1de8a78d6fa8 fixes the excessive slowness at emulation shutdown, so now I'm fine with keeping the thread suspending code that was added.

2022-02-17 17:05 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +	if (eThread->UniqueThread && g_iThreadNotificationCount) {
I changed `g_iThreadNotificationCount` from `int` to `std::atomic_int`, so it's unnecessary now.

2022-02-17 17:05 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		}
I changed `g_iThreadNotificationCount` from `int` to `std::atomic_int`, so it's unnecessary now.

2022-02-17 17:06 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +	for (int i = 0; i < PSP_MAX_CREATE_THREAD_NOTIFY; i++) {
I changed `g_iThreadNotificationCount` from `int` to `std::atomic_int`, so it's unnecessary now. 3/3

2022-02-20 13:10 UTC, PatrickvL submitted a review, later dismissed

2022-02-20 16:09 UTC, PatrickvL approved these changes

2022-02-22 22:20 UTC, merged