DirectSoundBuffer streaming
Cxbx-Reloaded/Cxbx-Reloaded pull request #2326
Opened 2022-03-02 11:44 UTC by NZJenkins

Xbox titles can write to audio buffers at any time - with no need to call lock APIs etc.

Continuously stream from audio buffers to improve titles that do.

Improvements:
* NBA Live 2005 (music / various sounds)
* Crash Tag Team Racing (Broken audio loops)
* Madagascar (Broken audio loops)
* Outrun 2006 (Performance related to fix by @RadWolfie, related PR #2311)

Regressions:
* Halo (intro is crackly)
* Probably lots of things

2022-03-03 03:16 UTC, LanHikariDS commented
Can confirm this PR does not contain the Halo 2 MMP crash of the predecessing PR

This PR provides mixed results with 007 Nightfire. In the main shooting levels, all Audio issues seem to have been fixed, but the driving segments have very terrible audio, and performance takes a massive nosedive during driving levels.

007 Agent Under Fire finally plays sound, but still locks up at the same point as it did in #2311

2022-03-04 08:51 UTC, NZJenkins commented
@RadWolfie found writing from the play cursor, instead of the write cursor (a hack that seemingly improved NBA Live 2005) caused various odd issues including DirectSound looping whole buffers of audio.

That hack has been removed, and the streaming options tweaked to what seems to work (on my PC at least...).
Even with the stream interval lowered to 1ms, NBA Live is still crackling a bit.

There may be bad perf implications for the current settings, and some titles may be affected differently
e.g. titles calling the sound APIs a lot, will contend for the global audio lock.
Some of the buffer settings have been made editable in the debug UI.
For perf issues, increasing the stream interval should help
![image](https://user-images.githubusercontent.com/9897874/156730542-f580731e-48ac-4426-8084-4aa2e936669c.png)

2022-03-05 02:47 UTC, LanHikariDS commented
007's aforementioned 'terrible audio' has been corrected by one of last night's updates to the PR, good stuff!

2022-03-05 02:51 UTC, medievil1 commented
add another fix to the list, 
the Hobbit no longer has cut off dialog

2022-03-06 16:14 UTC, NNX3x commented
With this PR I'm could hear improvements from two of my games:

- Prince of Persia: The sands of time, menu screen have music, master does not
- The Terminator: Dawn of Fate, Much better! For a very long time the audio in the menu screen has been in some sort of loop noise, but now i get some real music that comes in and out every few seconds. It's better but still is off.

2022-03-07 08:42 UTC, NZJenkins commented
Rebased on master and tidied up commits - removed broken Get/SetCurrentPosition behaviour (restoring Max Payne 2, may fix other crashing games)

2022-03-10 21:22 UTC, RadWolfie requested changes
Some changes necessary before allow to merge.

2022-03-10 21:22 UTC, RadWolfie commented on src/core/hle/DSOUND/DirectSound/DirectSoundBuffer.cpp
> -        LOG_FUNC_END;
Please restore these deletions. They are part of verbose debugging purpose.

2022-03-10 21:22 UTC, RadWolfie commented on src/core/hle/DSOUND/DirectSound/DirectSoundGlobal.cpp
> +	}
According to Imgui's documentation, they must be outside of `if` statement. Whenever open declaration is called, they must have closing declaration as well before make new call to (unnested) open declaration.

When I had `ImGui::EndChild();` inside if statement and outside window screen. An assertion was hit stating above procedure. So, that was my mistake.

```suggestion
		}
		ImGui::EndChild();

	}
	ImGui::End();
```

2022-03-10 21:22 UTC, RadWolfie commented on src/core/hle/DSOUND/DirectSound/DirectSoundGlobal.cpp
> +#include "DirectSoundInline.hpp"
For what reason DirectSoundInline.hpp include is used for? (need details)

2022-03-10 21:22 UTC, RadWolfie commented on src/core/hle/DSOUND/DirectSound/DirectSoundGlobal.cpp
> +#include "imgui_internal.h"
Please remove these debug changes. They are not intended to be upstream.

2022-03-11 20:40 UTC, NZJenkins commented on src/core/hle/DSOUND/DirectSound/DirectSoundGlobal.cpp
> +#include "DirectSoundInline.hpp"
comments can't save us!

2022-03-11 20:43 UTC, NZJenkins commented on src/core/hle/DSOUND/DirectSound/DirectSoundGlobal.cpp
> +#include "imgui_internal.h"
this is required for ImVec2
https://github.com/ocornut/imgui/issues/2832#issuecomment-538777840

2022-03-11 21:57 UTC, RadWolfie commented on src/core/hle/DSOUND/DirectSound/DirectSoundGlobal.cpp
> +#include "imgui_internal.h"
Okay, did some checking locally to see if it can be exposed through CMake. Apparently, it is not possible as imgui_internal header file is meant to be used inside ImGui project. And expect custom engine to either use their's or manually include builtin math from ImGui itself.

So, now they need to be move right below `#include <imgui.h>` line from this file. Any import headers from other projects within <> bracket need to be above any of our internal header files. Plus they need to stay in their specific purpose group as well.

2022-03-13 19:23 UTC, RadWolfie approved these changes
LTGM!

2022-03-13 19:54 UTC, RadWolfie commented on src/core/hle/DSOUND/DirectSound/DirectSound.cpp
> +			if (waitCounter > g_dsBufferStreaming.streamInterval) {
Thanks to @PatrickvL, he found the lost review remark. Here's the review remark:
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/77b48f2ec63dfbe23e12eaf5f723a37abdc88d3b#r67948074

2022-03-13 22:48 UTC, zstorm4 commented
pr causes freezing anytime a looped audio file (.wvs) plays in Metal Arms Glitch in the System (playable through a debug prototype). Mostly seems to be ambient audio tracks rather than one time messages, so not sure what's going on there.

2022-03-13 23:00 UTC, medievil1 commented
> pr causes freezing anytime a looped audio file (.wvs) plays in Metal Arms Glitch in the System (playable through a debug prototype). Mostly seems to be ambient audio tracks rather than one time messages, so not sure what's going on there.

have you verified it is NOT in master as well?

2022-03-13 23:17 UTC, zstorm4 commented
> > pr causes freezing anytime a looped audio file (.wvs) plays in Metal Arms Glitch in the System (playable through a debug prototype). Mostly seems to be ambient audio tracks rather than one time messages, so not sure what's going on there.
> 
> have you verified it is NOT in master as well?
I'm double checking my dump now. Don't know if bit rot is affecting it or what, but it's freezing on builds I've played multiple levels through now. Apologies and disregard for now.

2022-03-14 22:37 UTC, medievil1 commented
all of my games that didn't have streaming type sound are fixed by this, save one... knights of the temple 2 now DOES have music, but it is still distorted and prone to loud noise bursts

2022-03-28 12:06 UTC, PatrickvL commented on src/core/hle/DSOUND/DirectSound/DirectSound.cpp
> +			if (waitCounter > g_dsBufferStreaming.streamInterval) {
Seems fixed now!

2022-03-29 12:03 UTC, ergo720 approved these changes

2022-03-29 12:03 UTC, merged

2022-04-02 22:57 UTC, legend800 commented
Audio still loops on Virtua Cop 3 with this. Does this need to be applied to Chihiro processor or we just needs a separate fix?