Save and load compiled vertex shaders to/from disk
Cxbx-Reloaded/Cxbx-Reloaded pull request #2349
Opened 2022-04-14 13:28 UTC by NZJenkins

Which solves some minor stuttering caused by compiling shaders at runtime (or rather reduces it, since this is only for vs shaders)

Also, the FF VS is currently one giant shader whichis quite heavy, and we don't bundle a compiled version (we could whil variations aren't dynamically generated...)
but caching alleviates issues with it which can help render the first few frames right after boot e.g. the dashboard "zoom" effect at boot

Shaders get saved per title in a "Shaders" folder under the data path
TODO:
- [ ] Test the cache is rebuilt for new cxbx versions (in dev, need to regen cmake to change the version stamp...?)

2022-04-14 15:04 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	return fs::path(g_DataFilePath) / "Shaders" / fileName.str();
just a nit change here:
```suggestion
	return fs::path(g_DataFilePath) / "ShaderCache" / fileName.str();
```

2022-04-14 15:06 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	fs::create_directory(cachePath.parent_path());
imho, `fs` shortcut shouldn't be used. Beside, there's only one function used from filesystem library.

2022-04-14 15:07 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	namespace fs = std::filesystem;
I don't see any filesystem calls in this function. This line need to be remove.

2022-04-14 15:10 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	namespace fs = std::filesystem;
imho, fs shortcut shouldn't be used. Beside, there's only one function used from filesystem library.

2022-04-14 16:08 UTC, ergo720 commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> +		EmuLog(LOG_LEVEL::INFO, "An error occurred serializing the VSH cache");
This is an error condition right? So it should use the error log level.

2022-04-14 17:49 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> +	Header hExpected = CreateHeader();
This could be made a const or possibly even a constexpr

2022-04-14 17:49 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> +		existing->pHostVertexShader->Release();
Indentation level one extra please

2022-04-15 04:42 UTC, RadWolfie commented
> Test the cache is rebuilt for new cxbx versions (in dev, need to regen cmake to change the version stamp...?)

You don't need to touch cmake files to regenerate version stamp (which is git hash base on commit + tag, if any, itself). This is done through batch script as separate project and is run before project's build occur. Every time you build projects, you will see git hash output in the output window. If you are not creating commits, it will only append "-dirty" flag. "-dirty" flag is what you're looking for from GetGitVersionStr() function, if you need to force regen shader cache every time.

2022-04-17 21:22 UTC, NZJenkins commented
> > Test the cache is rebuilt for new cxbx versions (in dev, need to regen cmake to change the version stamp...?)
> 
> You don't need to touch cmake files to regenerate version stamp (which is git hash base on commit + tag, if any, itself). This is done through batch script as separate project and is run before project's build occur. Every time you build projects, you will see git hash output in the output window. If you are not creating commits, it will only append "-dirty" flag. "-dirty" flag is what you're looking for from GetGitVersionStr() function, if you need to force regen shader cache every time.

the tag doesn't seem to match when I build 🤷‍♂️

2022-04-18 12:21 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +			const ShaderKey ffKey = 0xFF;
Aren't you afraid of hash collisions on this seemingly randomly chosen value?

2022-04-18 15:58 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> -		// TODO compile the shader at a higher optimization level in a background thread?
Why is this remark removed? Is it not longer relevant? Or is the suggested functionality now delegated to another function?

2022-04-18 16:03 UTC, PatrickvL approved these changes
Functionality this looks fine. Perhaps some removed comments could be kept or moved, but otherwise this can be merged after successful testing

2022-04-18 20:05 UTC, NZJenkins commented on src/core/hle/D3D8/XbVertexShader.cpp
> +			const ShaderKey ffKey = 0xFF;
Nah just one more place to assume hash collisions don't happen...
It's 0xFF for fixed function ;)

2022-04-18 20:08 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> -		// TODO compile the shader at a higher optimization level in a background thread?
Didn't seem relevant - we compile at the highest optimisation level currently (iirc not true in the past)
Compiling with less optimisation might reduce stutter a bit - but this caching should also

2022-04-19 00:25 UTC, RadWolfie commented
@PatrickvL, please mark your reivews as resolve if you believe they are resolved. Thanks

2022-04-19 00:30 UTC, RadWolfie commented
> the tag doesn't seem to match when I build 🤷‍♂️

Please elaborate on this. Or was it misunderstood from your end?

2022-04-19 07:01 UTC, NZJenkins commented
> > the tag doesn't seem to match when I build 🤷‍♂️
> 
> Please elaborate on this. Or was it misunderstood from your end?

Nah I just can't read, the tag name threw me off

2022-04-27 09:34 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShaderSource.cpp
> +			EmuLog(LOG_LEVEL::INFO, "VSH cache version mismatch. The cache will not be loaded.");
Last commit fixed this

2022-04-27 09:36 UTC, PatrickvL requested changes
GitHub says conflicts need to be resolved before this can be merged, please considered a rebase.

2022-05-03 12:49 UTC, RadWolfie requested changes
Some changes required before able merge.

2022-05-03 12:49 UTC, RadWolfie commented on src/common/Settings.hpp
> +		int  Reserved99[9] = { 0 };
Misused of how reserved work. Reserved were originally meant to align properly. Since you take one bool out of int array. You left out 3 additional bools reserved.

Please use `bUnused_WasUseLoaderExec` or `Reserved4` variable. The latter is preferred.

2022-05-03 12:49 UTC, RadWolfie commented on src/common/win32/EmuShared.h
> +		bool GetUseShaderDiskCache() { Lock(); bool s = m_core.UseShaderDiskCache; Unlock(); return s; }
None of our EmuShared APIs are using any return, please fix by using parameter by design.

2022-05-03 12:49 UTC, RadWolfie commented on src/common/FilePaths.hpp
> +// FIXME include MAX_PATH
FIXME keyword is not common that will show up in IDEs. Please append `TODO:` as before text in order for it to appear on task list window.
These are the default tokens:
![image](https://user-images.githubusercontent.com/3938312/166453648-58234300-083a-48bb-b375-bbe112a6f051.png)

2022-05-03 12:49 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	if (!g_EmuShared->GetUseShaderDiskCache()) return;
Is it absolutely necessary to constant check EmuShared? EmuShared access design should only be access once per change occur.

According this pull request change, I don't see any IPC sync call during emulation which made this unnecessary and cause additional performance impact just for the lock/unlock. Please get the value from `CxbxInitWindow` function.

2022-05-03 12:51 UTC, RadWolfie commented
Beside review remark, if we are to implement backend settings for renderer's cache content. Should they need to be in the video settings instead of part of the core settings?

2022-05-04 04:14 UTC, closed without merging