Fix faux fullscreen overlay input
Cxbx-Reloaded/Cxbx-Reloaded pull request #2359
Opened 2022-05-11 00:14 UTC by RadWolfie

With this fix, overlay UI is able to respond to inputs instead of only hovering action. Plus allow to use other monitors as well.

2022-05-15 22:53 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
No empty line needed here

2022-05-15 22:53 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +
No empty line needed here

2022-05-15 22:54 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        SetWindowPos(hWnd, HWND_TOPMOST, lRect.left, lRect.top, 0, 0, SWP_NOSIZE);
Empty separator line needed above this one

2022-05-15 22:55 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +    if( g_XBVideo.bFullScreen) {
Why the space after the opening round bracket?

2022-05-15 22:56 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        if(CxbxKrnl_hEmuParent) {
Spacing between if and opening round bracket is not very consistent in this commit

2022-05-15 22:58 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +            // NOTE: SetWindowPos is used to make correction for other than main monitor to appear than remain invisible.
I'm not a native English speaker, so that may be part of the reason, but I find it difficult to understand the meaning of this sentence

2022-05-15 22:59 UTC, PatrickvL requested changes
Nice work! Just some small style remarks

2022-05-15 23:57 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +            // NOTE: SetWindowPos is used to make correction for other than main monitor to appear than remain invisible.
If you toggle faux fullscreen back to windowed mode (return to GUI's window), nothing is display on GUI's window. Only thing you will see is Cxbx-Reloaded name with title's logo just like when you load an xbe. Without this fix, renderer window will remain hidden for unknown reason. Unless you are on main monitor screen when toggle it again twice.

2022-05-15 23:59 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +    if( g_XBVideo.bFullScreen) {
I was debugging other things here. That's unintentional space here. 😂

2022-05-16 00:06 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        SetWindowPos(hWnd, HWND_TOPMOST, lRect.left, lRect.top, 0, 0, SWP_NOSIZE);
Main reason there's no empty separator line here is they are part of the function to make the effect work.

2022-05-16 00:06 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +
This is intentional as it is somehow a workaround fix for unknown issue on secondary monitors. It is not relative to the below code as they are actual method to make it work.

2022-05-16 00:06 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        if(CxbxKrnl_hEmuParent) {
Main reason there's no empty separator line here is they are part of the function to make the effect work.

2022-05-21 17:13 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +            // NOTE: SetWindowPos is used to make correction for other than main monitor to appear than remain invisible.
Suggested wording :
```
// NOTE: SetWindowPos makes render window contents show up on non-primary displays (which would otherwise only show host window contents).
```

2022-05-21 17:15 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        if(CxbxKrnl_hEmuParent) {
This will become a moot point anyway once sources are auto-formatted

2022-05-21 17:15 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +
This will become a moot point anyway once sources are auto-formatted

2022-05-21 17:45 UTC, PatrickvL approved these changes

2022-05-21 17:45 UTC, merged

2022-05-21 17:45 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +            // NOTE: SetWindowPos is used to make correction for other than main monitor to appear than remain invisible.
Thanks for the rewording, it is fixed.