I/O filesystem partial update
Cxbx-Reloaded/Cxbx-Reloaded pull request #2365
Opened 2022-05-21 20:06 UTC by RadWolfie

This is a major change to the filesystem.

With this fix to the filesystem we enable:
- [x] Native object manager enabled support.
- [x] Full symbolic link functionality instead of hardcode hacks for certain case and only had drive letters support.
- [x] Ability to create native devices and its interface.
  - The interfaces require irp work which are not in this pull request.
- [x] New file system is now base on host's native handle attachment to file object which no longer require xbox to host strings conversion checks anymore.
  - With a bonus benefit, we can use below functions with xbox objects to obtain their file path:
    - `Object2AbsolutePath` : Full path which use straightforward device path and file system's remaining path.
    - `Object2RemainingPath`: Like above except exclude device path. This enable support for rename functionality forward.
- [x] Additional verbose details to I/O objects and their ouputs

Two things I'll like to add:
1. There are some events coded in the structure. Except they are inactive due to object manager's event is not implemented yet.
2. Media Board will need to be implement and upstream into chihiro branch before can rebase after merge. Which is already been implemented locally.

See ticket #2361 for Top Priority's list of completions. Plus `Io(Check|Set|Removed)SharedAccess` functions which are currently unused and base on ReactOS.

---
These are critical titles to verify for ensure file system are still functional:
- Grand Theft Auto (3 and later): Always trigger reformat partition every time.
- Exhibition Demo Disc: Multi-xbe titles
  - Run Panzer Dragoon Orta's xbe directly is also critical to check as well. Using default will generate pdodemo folder whilst direct run PDO's xbe will generate in top partition's folder.
- Official dashboard: For verify Memory Units' and harddrive for titles' data listing. Plus edit Memory Units' names.
- Misc titles for verify gameplay testing.

---
<details>
<summary>Experiment test code for verification used (require to be after CxbxrSetupDrives call)</summary>

```cpp
	// Begin of I/O test
	std::string file_test = DeviceHarddisk0Partition3 + "\\test.txt";
	std::string file_test_rename = DeviceHarddisk0Partition3 + "\\rename.txt";
	xbox::STRING ObjectName;
	xbox::RtlInitAnsiString(&ObjectName, file_test.c_str());
	xbox::HANDLE FileHandle, dupFileHandle;
	xbox::OBJECT_ATTRIBUTES ObjectAttributes;
	X_InitializeObjectAttributes(&ObjectAttributes, &ObjectName, NULL, NULL);
	xbox::IO_STATUS_BLOCK IoStatusBlock;
	xbox::ntstatus_xt result = xbox::NtCreateFile(&FileHandle, FILE_GENERIC_READ | FILE_GENERIC_WRITE, &ObjectAttributes, &IoStatusBlock, nullptr, FILE_ATTRIBUTE_NORMAL, 0, FILE_OVERWRITE_IF, FILE_NON_DIRECTORY_FILE | FILE_SYNCHRONOUS_IO_NONALERT);

	std::string content_write_test = "This is a test.";
	char content_read_test[std::size("This is a test.")]{};
	result = xbox::NtWriteFile(FileHandle, NULL, nullptr, nullptr, &IoStatusBlock, content_write_test.data(), content_write_test.size(), nullptr);

#if 1 // Result currently return as access denied for some reason. Need to fix this test. (PDO for verification use shown to work)
	xbox::FILE_RENAME_INFORMATION FileInformation{ .ReplaceIfExists = false, .RootDirectory = xbox::zeroptr };
	xbox::RtlInitAnsiString(&FileInformation.FileName, file_test_rename.c_str());
	result = xbox::NtSetInformationFile(FileHandle, &IoStatusBlock, &FileInformation, sizeof(FileInformation), xbox::FileRenameInformation);
#else
	const std::string& host_directory = "P:\\Github Sync\\Cxbx-Reloaded\\build-vs22\\bin\\Debug\\EmuDisk\\Partition3";
	std::string host_file_test = host_directory + "\\test.txt";
	std::string host_file_test_rename = host_directory + "\\rename.txt";
	BOOL test = MoveFileA(host_file_test.c_str(), host_file_test_rename.c_str());
#endif

	result = xbox::NtDuplicateObject(FileHandle, &dupFileHandle, DUPLICATE_CLOSE_SOURCE);

	PVOID FileObject;
	if (X_NT_SUCCESS(result)) {
		result = xbox::ObReferenceObjectByHandle(FileHandle, xbox::zeroptr, &FileObject);
	}
	if (X_NT_SUCCESS(result)) {
		const auto& XboxTargetPathFull = Object2AbsolutePath(FileObject);
		const auto& XboxTargetPathRemaning = Object2RemainingPath(FileObject);
		xbox::ObfDereferenceObject(FileObject);
		xbox::NtClose(FileHandle);
	}

	xbox::LARGE_INTEGER ByteOffset{};
	result = xbox::NtReadFile(dupFileHandle, NULL, nullptr, nullptr, &IoStatusBlock, content_read_test, content_write_test.size(), &ByteOffset);

	result = xbox::NtClose(dupFileHandle);

	result = xbox::NtDeleteFile(&ObjectAttributes);

	// Symbolic Link test
	xbox::HANDLE RootDirHandle = xbox::zeroptr;
	std::string CreateDirectories[]{
		DeviceHarddisk0Partition3 + "\\test",
		DeviceHarddisk0Partition3 + "\\test\\1",
		DeviceHarddisk0Partition3 + "\\test\\1\\2",
		DeviceHarddisk0Partition3 + "\\test\\1\\2\\3",
	};
	for (size_t i = 0; i < std::size(CreateDirectories); i++) {
		xbox::STRING ObjectName;
		xbox::RtlInitAnsiString(&ObjectName, CreateDirectories[i].c_str());
		xbox::HANDLE DirHandle;
		xbox::OBJECT_ATTRIBUTES ObjectAttributes;
		X_InitializeObjectAttributes(&ObjectAttributes, &ObjectName, NULL, NULL);
		result = xbox::NtCreateFile(&DirHandle, FILE_LIST_DIRECTORY | SYNCHRONIZE, &ObjectAttributes, &IoStatusBlock, nullptr, FILE_ATTRIBUTE_NORMAL, 0, FILE_CREATE, FILE_DIRECTORY_FILE | FILE_SYNCHRONOUS_IO_NONALERT | FILE_OPEN_FOR_BACKUP_INTENT);
		if (X_NT_SUCCESS(result)) {
			xbox::NtClose(DirHandle);
		}
	}
	std::string CreateSymbolicLinks[]{
		DeviceHarddisk0Partition3,
		DrivePrefix + "W:\\test",
		DrivePrefix + "X:\\1",
		DrivePrefix + "Y:\\2",
		DrivePrefix + "Z:\\3",
	};
	for (size_t i = 1; i < std::size(CreateSymbolicLinks); i++) {
		xbox::STRING ObjectNamePrev, ObjectNameNext;
		xbox::RtlInitAnsiString(&ObjectNamePrev, CreateSymbolicLinks[i-1].c_str());
		std::string mount_drive = CreateSymbolicLinks[i].substr(0, 6);
		xbox::RtlInitAnsiString(&ObjectNameNext, mount_drive.c_str());
		result = xbox::IoCreateSymbolicLink(&ObjectNameNext, &ObjectNamePrev);
		if (!X_NT_SUCCESS(result)) {
			break;
		}
		xbox::PVOID FileObject;
		xbox::HANDLE DirHandle;
		ObjectAttributes.ObjectName = &ObjectNameNext;
		result = xbox::NtOpenFile(&DirHandle, FILE_LIST_DIRECTORY | SYNCHRONIZE, &ObjectAttributes, &IoStatusBlock, 0, FILE_DIRECTORY_FILE | FILE_SYNCHRONOUS_IO_NONALERT | FILE_OPEN_FOR_BACKUP_INTENT);
		if (X_NT_SUCCESS(result)) {
			result = xbox::ObReferenceObjectByHandle(DirHandle, xbox::zeroptr, &FileObject);
		}
		if (X_NT_SUCCESS(result)) {
			const auto& XboxTargetPathFull = Object2AbsolutePath(FileObject);
			const auto& XboxTargetPathRemaning = Object2RemainingPath(FileObject);
			xbox::ObfDereferenceObject(FileObject);
			xbox::NtClose(DirHandle);
		}
	}
	// Deattach leftover symbolic links
	for (std::size_t i = std::size(CreateSymbolicLinks) - 1; i > 0; i--) {
		xbox::STRING SymbolicLink;
		std::string mount_drive = CreateSymbolicLinks[i].substr(0, 6);
		xbox::RtlInitAnsiString(&SymbolicLink, mount_drive.c_str());
		result = xbox::IoDeleteSymbolicLink(&SymbolicLink);
	}
	// Delete leftover folders
	for (signed i = std::size(CreateDirectories) - 1;; i--) {
		xbox::STRING ObjectName;
		xbox::RtlInitAnsiString(&ObjectName, CreateDirectories[i].c_str());
		xbox::HANDLE DirHandle;
		xbox::OBJECT_ATTRIBUTES ObjectAttributes;
		X_InitializeObjectAttributes(&ObjectAttributes, &ObjectName, NULL, NULL);
		result = xbox::NtDeleteFile(&ObjectAttributes);
		if (!X_NT_SUCCESS(result)) {
			break;
		}
		// Exit once we reach to zero.
		if (!i) {
			break;
		}
	}
	// End of I/O test
```
</details>

2022-05-22 10:17 UTC, PatrickvL commented on src/core/kernel/support/EmuMu.cpp
> +	MuPath.HostBinHandle = CreateFileA(partitionHeaderPath.c_str(), GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, NULL, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS,
Is their an important reason to use the ANSI API? We're living in the Unicode (widestring) world for a while already ..

2022-05-22 10:19 UTC, PatrickvL commented on src/core/kernel/support/EmuMu.cpp
> +		nullptr,
Could you please add each member name per value in an end of line comment? That way code searches for these members will also find this initialization.

2022-05-22 10:25 UTC, PatrickvL commented on src/core/kernel/support/EmuMu.cpp
> +	bool succeeded{ true };
Why did you not use an assignment syntax here? (`bool succeeded = true;`)

2022-05-22 10:27 UTC, PatrickvL commented on src/core/kernel/support/EmuMu.cpp
> +		if (!er) {
Consider printing an error here from https://en.cppreference.com/w/cpp/error/error_code/message

2022-05-22 10:29 UTC, PatrickvL commented on src/core/kernel/support/EmuMu.cpp
> +
These empty separator lines could be removed (many others as well in this pull request)

2022-05-22 10:30 UTC, PatrickvL commented on src/core/kernel/support/EmuDisk.cpp
> +		DiskStartIo,
Could you please add each member name per value in an end of line comment? That way code searches for these members will also find this initialization.

2022-05-22 10:30 UTC, PatrickvL commented on src/core/kernel/support/EmuCdRom.cpp
> +		CdRomStartIo,
Could you please add each member name per value in an end of line comment? That way code searches for these members will also find this initialization.

2022-05-22 10:35 UTC, PatrickvL commented on src/core/kernel/common/types.h
> +	PDRIVER_DISPATCH     MajorFunction[IRP_MJ_MAXIMUM_FUNCTION + 1]; // See below for complete list of each offset function use.
It might be useful to create a struct DRIVER_DISPATCH_TABLE to replace the array with, so that each offset can be accessed by name, which would give more insight during debugging (member inspection)

2022-05-22 10:37 UTC, PatrickvL commented on src/core/kernel/common/types.h
> +} OPEN_PACKET, *POPEN_PACKET;
Consider adding end of line comments per member containing it's hexadecimal offset, plus at the end the total size of the struct

2022-05-22 10:46 UTC, PatrickvL commented on src/core/kernel/exports/EmuKrnlLogging.h
> +LOGRENDER_HEADER(FILE_FS_SIZE_INFORMATION)
Above, introduce a commented out registration for the newly introduced type `FILE_ATTRIBUTE_TAG_INFORMATION`

Other newly introduced types should be added likewise in their appropriate location

2022-05-22 10:50 UTC, PatrickvL commented on src/core/kernel/common/types.h
> +	// IRP_MJ_???
Is the union `Parameters` in `IO_STACK_LOCATION` related to these? That maybe worth a mention in a comment here.
Referring to the various blocks inside Parameters, their names might be associated with some of the unknown ??? marked lines in here.

2022-05-22 10:53 UTC, PatrickvL commented on src/core/kernel/common/types.h
> +} OPEN_PACKET, *POPEN_PACKET;
The same might be good to add to all other Xbox kernel struct types currently still lacking offsets and size indications

2022-05-22 10:54 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +	}
Please add a TODO comment or an explanation why this is empty

2022-05-22 10:56 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +	if (string.empty()) {
Consider performing this check first, before entering the lock

2022-05-22 10:58 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +	POBJECT_HEADER ObjectHeader = OBJECT_TO_OBJECT_HEADER(xobject);
Does this check really need to be in the lock? If not, move entering the lock to afterwards this check, to avoid needless contention

2022-05-22 11:02 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		it1->second.StrHash = StrHash;
Existing non-empty and different StrHash should decrease its reference counter, as it's about to be replaced.

Same below

2022-05-22 11:05 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		it2->second.StrHash = StrHash;
Also, decreasing the reference count of an existing StrHash (different from the one that's about to be assigned here) also requires handling cleanup when a reference count reaches zero!

2022-05-22 11:09 UTC, PatrickvL requested changes
Only done a partial review, as this is a huge change (great to see it done though!)

Some remarks to consider already. To be continued later...

2022-05-22 23:44 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlLogging.h
> +LOGRENDER_HEADER(FILE_FS_SIZE_INFORMATION)
Fixed in d54ea6a79782857076d2d4510b28909e5d4e9c0a commit, any further amissed will be in new review remark.

2022-05-22 23:47 UTC, RadWolfie commented on src/core/kernel/support/NativeHandle.cpp
> +	}
That is my mistake, a problematic area (not from this) caught my attention and forgot about finish this part of code. So, that's fixed as well. Thank you for bringing this to my attention! 😄👍

2022-05-22 23:52 UTC, RadWolfie commented on src/core/kernel/support/NativeHandle.cpp
> +	if (string.empty()) {
You could had selected multiple-lines block to do review remark instead of three separate comments. So I'll response to this beside other two comments.

Normally when I think of this, I always think about pre-planned to reserse the lock until there's nothing needed to update/release. For now, I will skip the lock guard over two pre-checks. **(fixed)**

2022-05-23 00:01 UTC, RadWolfie commented on src/core/kernel/support/NativeHandle.cpp
> +		it2->second.StrHash = StrHash;
I don't think I understand what you're saying. But this HandleHandle has its own mutex so none of three global variables are used at same time between threads. And this isn't place where decrease reference count occur. Perhaps take another look at the file as raw or explain it clearly for me?

2022-05-23 00:03 UTC, RadWolfie commented on src/core/kernel/common/types.h
> +} OPEN_PACKET, *POPEN_PACKET;
updated in review remark commit

2022-05-23 00:04 UTC, RadWolfie commented on src/core/kernel/common/types.h
> +} OPEN_PACKET, *POPEN_PACKET;
Um... duplicate of https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2365#discussion_r878840053 remark?

2022-05-23 00:06 UTC, RadWolfie commented on src/core/kernel/common/types.h
> +	PDRIVER_DISPATCH     MajorFunction[IRP_MJ_MAXIMUM_FUNCTION + 1]; // See below for complete list of each offset function use.
Currently in netural decision, I may be okay with this. We are bringing this to the team discussion for feedback.

2022-05-23 00:08 UTC, RadWolfie commented on src/core/kernel/support/EmuMu.cpp
> +
Added NOTE comment for reason there are multiple separator lines. This also included with EmuDisk, and EmuCdRom files.

2022-05-23 00:12 UTC, RadWolfie commented on src/core/kernel/support/EmuMu.cpp
> +	MuPath.HostBinHandle = CreateFileA(partitionHeaderPath.c_str(), GENERIC_READ | GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, NULL, OPEN_EXISTING, FILE_FLAG_BACKUP_SEMANTICS,
Our current strings in codebase are mostly using `std::string`. Though, xbox kernel doesn't have wchar_t strings supported if I remember that right. So, we may need to change `std::string` to `std::u8string` as we know xbox kernel do have utf-8 strings for filesystem.

2022-05-23 00:17 UTC, RadWolfie commented on src/core/kernel/support/EmuMu.cpp
> +	bool succeeded{ true };
I had seen some pull requests here that are using `var{};`, instead of `var = {};` which do perform same zero initialization. We can also do this way for set other than default zero as well. Might as well start using new C++ initialization method.

2022-05-23 00:18 UTC, RadWolfie commented on src/core/kernel/support/EmuDisk.cpp
> +		DiskStartIo,
Suppressed and use https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2365#discussion_r878835825 review remark as central discussion.

2022-05-23 00:19 UTC, RadWolfie commented on src/core/kernel/support/EmuCdRom.cpp
> +		CdRomStartIo,
Suppressed and use https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2365#discussion_r878835825 review remark as central discussion.

2022-05-23 00:27 UTC, RadWolfie commented on src/core/kernel/support/EmuMu.cpp
> +		nullptr,
Right now, irp aren't implemented. Any further work for irp will need to be done in separate pull request. For now, I implemented new C++20 method to improve our readability in codebase easier. I hope new change is enough to satisfy for now. Though, I am awaiting on further discussion for union topic before stay with new fix or re-update.

2022-05-23 00:29 UTC, RadWolfie commented on src/core/kernel/common/types.h
> +	// IRP_MJ_???
Reminder to @RadWolfie for next fixup remark.

2022-05-25 16:17 UTC, RadWolfie commented
After I notice something was off when I try to attempt copy soundtrack onto hdd from "Exhibition Demo Disc". `FileAttributes` argument has `0x88` input with `Options`' has `0x0` input. I checked out bitmask 0x8 to try figure out what it is used for. Seems like it was used in DOS' volume id flag. But `Options` argument has `0x0` input which means there is no parameter's validation check occur. For this, we need to sanction all parameters. I added `FileAtrributes` to the sanction in the new "fix Exhibition Demo Disc problem for copy soundtracks onto hdd" commit.

According to the rest of parameters, only thing left is `Disposition` have not been sanction and unlikely need any sanction.

2022-05-30 12:43 UTC, PatrickvL commented on src/core/kernel/support/EmuMu.cpp
> +		nullptr,
Okay. I see you've started to use designated initialization, that's fine too (even better, actually, since that will perform compile-time validation of correctly named fields).

2022-05-30 12:44 UTC, PatrickvL commented on src/core/kernel/support/EmuMu.cpp
> +	bool succeeded{ true };
Sure thing. I was just wondering if there was a pressing need to do so, but if this is the way forward, that's fine.

2022-05-30 12:52 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +	POBJECT_HEADER ObjectHeader = OBJECT_TO_OBJECT_HEADER(xobject);
I see you've addressed this in commit e173a5a177d35fad1c9517f27087010bce8d86e3. Thanks!

2022-05-30 12:53 UTC, PatrickvL commented on src/core/kernel/common/types.h
> +	// IRP_MJ_???
I see a comment for this was added in commit bfdcd30e9e3c0ab47846e10ba0d6537afbd67cd4 - thanks!

2022-05-30 12:56 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		it1->second.StrHash = StrHash;
Nowadays C++ offers [smart pointers](https://en.wikipedia.org/wiki/Reference_counting#C++ ) that could perhaps be used instead.

2022-05-30 12:59 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		it2->second.StrHash = StrHash;
I was talking about avoiding memory leaks when reference-count reaches zero - normally, when that happens, the resource being reference counted no longer serves a purpose (as there's no reference to it anymore), so should be disposed.

The locking you mention is a totally separate subject, not relevant to my remark here.

2022-05-30 13:02 UTC, PatrickvL commented on src/core/kernel/common/types.h
> +	PDRIVER_DISPATCH     MajorFunction[IRP_MJ_MAXIMUM_FUNCTION + 1]; // See below for complete list of each offset function use.
Additional remarks I had on this, copied from the team chat : 

> Obviously the nested union struct has to be the same size as the array, and have the named fields at the same offset as the corresponding indices in the array, and declare all fields of the same type as the array contains 
> The motivation for the suggestion to add a union overlay is, that it makes inspecting these members easier during debugging, because it'd be no longer necessary to remember the indices
> (Since they're function pointers, I'd expect them to show up as addresses, labelled with the corresponding symbol names)

2022-05-30 13:04 UTC, PatrickvL commented on src/core/kernel/support/NativeHandle.cpp
> +		it1->second.StrHash = StrHash;
Is see this is addressed in commit e173a5a177d35fad1c9517f27087010bce8d86e3 - thanks!

2022-05-30 16:02 UTC, RadWolfie commented on src/core/kernel/support/NativeHandle.cpp
> +		it2->second.StrHash = StrHash;
After internal discussion for clarification, I can understand clearly what Patrick is trying to say to me.

Technically, this shouldn't happen since xbox object are always unique and `AttachStringToXboxObject` should only use on new objects than re-use on existing objects. For now, I add `StrHashDereference` calls which will perform self-check if string hash is non-zero in commit 9631804.

2022-05-30 16:09 UTC, RadWolfie commented on src/core/kernel/common/types.h
> +	PDRIVER_DISPATCH     MajorFunction[IRP_MJ_MAXIMUM_FUNCTION + 1]; // See below for complete list of each offset function use.
Last updated from team chat vote:
Opposed: 1
Netural: 1
Proposed: 1

2022-06-05 10:45 UTC, ergo720 commented
Reminder for the community that this needs some testing before merging.

2022-06-05 16:02 UTC, LanHikariDS commented
PR enables custom soundtracks in all tested games (Dashboard, Burnout 3, GTA3, and GTAVC). One track bugged out in GTA3, but may have been a random fluke, will test further later.
Also seems to improve loading issues with Halo, but doesn't completely solve it
![image](https://user-images.githubusercontent.com/42668580/172059186-90bfc8bc-65d5-4e95-a899-6dcde2f0693c.png)

2022-06-06 05:26 UTC, LanHikariDS commented
Tested a bit further, sitting back and listening to my Custom Soundtrack now to double-check for playback errors, however, I do have some remarks. First and foremost, this PR seems to break stopping emulation. Every time emulation is stopped, Windows makes an error sound, and CXBX-R goes not responding for a moment. From there, a plethora of things can happen when the emulator reverts to 640x480, such as showing a black screen, restarting the current game at 640x480 (with broken aspect, likely dependant on user settings), or not closing the game at all and trimming the image. 
![image](https://user-images.githubusercontent.com/42668580/172099753-6dce3eaf-13c3-43cc-a5b4-8bd664d2b7d5.png)
![image](https://user-images.githubusercontent.com/42668580/172099777-5ad4f53a-99c2-42ae-bc65-743392c73560.png)
If it's any help, closing the emulator with an incorrectly closed game (Agent Under Fire) causes an XBE exception 
![image](https://user-images.githubusercontent.com/42668580/172099854-d39048a5-f679-486c-bd8a-aca6651e3f80.png)

Moreover, I regret to say the Halo improvement seems to have been a false positive. Upon first testing this PR, I got _four_ valid loads in a row, but have since been unable to get a single valid load since.

2022-06-06 18:59 UTC, medievil1 commented
I am not sure the cxbx closing issues are related to THIS PR, I have been having issues with games hanging (cxbx-ldr, not closing) multiple tries to get a game started, etc on master for a while (not sure if it was the threading pr' or the one that made cxbx-ldr the only option that I noticed it happening)

2022-06-09 13:17 UTC, RadWolfie commented
> First and foremost, this PR seems to break stopping emulation. Every time emulation is stopped, Windows makes an error sound, and CXBX-R goes not responding for a moment.

I remember has happened before. If I recall, it is not relative to this pull request issue. The cause is the shutdown process isn't fully feature complete. See #2366 ticket for this type of problem.

> From there, a plethora of things can happen when the emulator reverts to 640x480, such as showing a black screen, restarting the current game at 640x480 (with broken aspect, likely dependant on user settings), or not closing the game at all and trimming the image.

Thanks for report of this problem. It may not be caused from this pull request. I will make attempt to reproduce this problem soon.

2022-06-13 16:15 UTC, ergo720 commented
> First and foremost, this PR seems to break stopping emulation.

@LanHikariDS I found the issue: it's caused by this line https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/b43f6bbcdfbd87319c805a7d6d4a67f456276aec/src/common/cxbxr.cpp#L109 If you disable it, the shutdown issue goes away, at least for me. That code has been present for a couple of months now, it's just that this PR makes the issue more obvious now.

2022-06-13 19:24 UTC, medievil1 commented
> > First and foremost, this PR seems to break stopping emulation.
> 
> @LanHikariDS I found the issue: it's caused by this line
> 
> https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/b43f6bbcdfbd87319c805a7d6d4a67f456276aec/src/common/cxbxr.cpp#L109
> If you disable it, the shutdown issue goes away, at least for me. That code has been present for a couple of months now, it's just that this PR makes the issue more obvious now.

makes sense, cxbx-ldr hangs when it fails to stop. could be related to nz's soundbuffer pr too... possibly it is in the middle of flushing or similar when it gets the suspend, hangs, then causes cxbx-ldr to hang...the hang seems more prevalent when audio is streaming if I recall

2022-07-10 20:59 UTC, LanHikariDS commented
... why was this closed?

2022-10-04 19:24 UTC, Ehren1337 commented
> ... why was this closed?

probably distraction

2025-08-29 01:02 UTC, RadWolfie commented on src/core/kernel/common/types.h
> +	PDRIVER_DISPATCH     MajorFunction[IRP_MJ_MAXIMUM_FUNCTION + 1]; // See below for complete list of each offset function use.
Added in `kernel: add union to able see name of MajorFunction, address, and name of function in the debugger` commit.

2025-08-29 09:43 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		// TODO: We don't need this anymore, right????????????
I have a faint memory that this was necessary to be able to suspend threads form another thread, which happens in `KeSuspendThread`. So, you should first confirm if thread suspension still works with this change. If it turns out that it's still necessary, then either this must be reinstated, or you could try to see if it's possible to create a new thread with all access rights already. Alternatively, you can also leave this code here as it was.

2025-08-29 09:56 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +		// NULL native handle (e.g. directory objects hit this case)
In `NtCreateDirectoryObject`, I see that you have removed the line `RegisterXboxHandle(*DirectoryHandle, NULL); // we don't need to create a native handle for a directory object`, which supposedly hit this case. So, is this still possible to happen?

2025-08-29 10:41 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +		// NULL native handle (e.g. directory objects hit this case)
Directory objects are handled from the Xbox's filesystem directly. There is no host directory involve from `NtCreateDirectoryObject` API. It is handled by the xbox filesystem objects which will reach to `IopParseDevice` function. It is the heart of the device driver that is handled from xbox<->host filesystem sandbox. In the future, `IopParseDevice` will be interface with the actual emulated device driver.

2025-08-29 10:49 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		// TODO: We don't need this anymore, right????????????
I could write a test code to verify if there's a problem using `KeSuspendThread` function. Beside that, we can only have one host handle allocated to one xbox object. If it needs more permission access, then we can replace `handle` to `dupHandle` and free the original host's `handle`.

2025-08-29 11:50 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +		// NULL native handle (e.g. directory objects hit this case)
That's not what I asked. Also, now that I check better, I see that `SourceHandle` is being checked with `GetHandleInformation`, which will surely fail `if SourceHandle == NULL`, because that's the invalid handle for Windows too. So, if we reach here, the handle is surely valid and thus the check `if (SourceHandle != NULL)` can be deleted. The comment above it is incorrect too, since it's talking about a `nativeHandle`, which has now been removed.

2025-08-30 08:55 UTC, PatrickvL commented on src/core/kernel/common/types.h
> +	PDRIVER_DISPATCH     MajorFunction[IRP_MJ_MAXIMUM_FUNCTION + 1]; // See below for complete list of each offset function use.
Great!

2025-09-14 04:24 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlPs.cpp
> +		// TODO: We don't need this anymore, right????????????
https://github.com/Cxbx-Reloaded/xbox_kernel_test_suite/pull/110 tests has confirmed it is able to suspend/resume thread just fine. However, Cxbx-Reloaded is not in fully passable state sometimes.

Therefore the commented out code is fully removed.

2025-09-14 04:28 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +		// NULL native handle (e.g. directory objects hit this case)
Extra if statement check has been removed.

2025-09-14 17:01 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +	}
This code is broken, since `GetHandleInformation` is not a suitable substitute for `GetNativeHandle`. The reason for this, is that it's possible for a Windows handle to accidentally numerically collide with an xbox handle. If that were to happen, the current code will mistakenly attempt to close the xbox handle, while in reality it was a Windows handle. Same thing for `NtDuplicateObject`, `NtFlushBuffersFile`, `NtQueryDirectoryFile` and probably others too. The previous call to `GetNativeHandle` was solving the problem because it was querying a global map between xbox and Windows handles, which was populated as new xbox handles were created. Thus, if it was a Windows handle, it would fail to find it and we would know the source was a Windows handle.

2025-09-14 17:53 UTC, RadWolfie commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +	}
> The reason for this, is that it's possible for a Windows handle to accidentally numerically collide with an xbox handle.

> The previous call to GetNativeHandle was solving the problem because it was querying a global map between xbox and Windows handles, which was populated as new xbox handles were created.

False, it doesn't populate new xbox handles for every Windows handles and should not be used this way in reality. It is ***remain partial broken*** in either way. Once ***every*** single things mentioned in the listed are move over into xbox object manager system via `RegisterXboxObject`/`RemoveXboxObject` method. Then there's absolutely no way to mix between xbox and Windows handles at all. The titles I had tested still remain functional as upstream btw. `GetNativeHandle` is **NOT** managing both Windows and xbox handles at all. That is misleading. What `GetNativeHandle` actually do is check for xbox handle first then "assumed" it is Windows handle, this is still wrong.

I had explained to you why this is the wrong direction to go with. I had went thoroughly with the filesystem implementation and majority of the problems I had points out `GetNativeHandle` is not the correct way to deal with this problem. And technically still align in the remainder of conversion in the pull request. Every single xbox handles must be bind to xbox objects then those xbox objects can be bind to host handles. This is how we can make a proper kernel sandbox system without titles breaking.

> Same thing for `NtDuplicateObject`, `NtFlushBuffersFile`, `NtQueryDirectoryFile` and probably others too.

- `NtDuplicateObject`: This require every single things mentioned on the list to move over into xbox object manager system.
- `NtFlushBuffersFile`: Not relative to the issue, it is native support for xbox object manager system. However, it is still forward to Windows if the xbox handle are VALID only. Since it require irp work.
- `NtQueryDirectoryFile`: Not relative to the issue, it only handle the file system which is 100% native to xbox object support.

Instead of making this false report, please test if there **are any** regression. Since I cannot find any regression from my end with multiple titles. The only two titles I found did actually progress further as listed in OP post. If you do find regression, then report those issue and point out which part of the code is causing it.

2025-09-15 14:30 UTC, ergo720 commented on src/core/kernel/exports/EmuKrnlNt.cpp
> +	}
I went ahead and crafted an nxdk-powered app to specifically trigger the problem I was talking about. Here is the code:
```
#include <hal/xbox.h>
#include <windows.h>


void main()
{
    for (unsigned i = 0; i < 800; ++i) {
        // Create enough directory objects (handled by Ob in cxbxr) so that we collide with Windows handles (around 0x74D on my machine)
        HANDLE Handle;
        NTSTATUS Status = NtCreateDirectoryObject(&Handle, NULL);
        if (Status != STATUS_SUCCESS) {
            XReboot();
        }
    }
    
    // This will trigger the xbox/Windows handle collision
    HANDLE Handle;
    NtCreateEvent(&Handle, NULL, SynchronizationEvent, TRUE);
    NtClose(Handle);
    
    Sleep(1000);
    
    XReboot();
}

```

To be fair, I now notice that both current master and the PR are affected by the problem, so it’s an existing issue. Based on this, we can probably delay the issue for a future PR.

2025-09-15 14:38 UTC, merged