Fix vertex shader op independence
Cxbx-Reloaded/Cxbx-Reloaded pull request #2374
Opened 2022-06-17 12:30 UTC by NZJenkins

Ensure the MAC op does not interfere with the input of the ILU op.
- Use a temp register to store the output of the MAC op when necessary
- Reorganize vertex shader decoding to better reflect the data.
Decode one vsh instruction to one intermediate instruction, rather than to multiple independent instructions.
Test case:
KOTOR II (menu)
GTA III (lighting)

Cheers to xemu for solving this same issue a while back and medievil tracking down this was the issue with the KOTOR 1 menu (currently still broken)

GTA III sample
```c
temp = r4;
x_dp3(r4,w, r9.wyzz, r9.wyzz);
x_rsq(r1,w, temp.w);
```

2022-06-17 14:29 UTC, medievil1 commented
fixes sphinx and the cursed mummies disappearing/reappearing elements
Stubs the zombie, first time I know showing anything
![image](https://user-images.githubusercontent.com/38597905/174318084-3ab032e7-3d25-4c86-b2fa-c361d8c06a6f.png)

breaks otogi, nightcaster (vertex explosion), memorick(trees are missing), dreamfall(menu background is a vertex explosion to the center), azurik (looks like a ship in warp..lol)
![image](https://user-images.githubusercontent.com/38597905/174318178-372547cc-dc3c-411b-b43a-5d0fa24f2090.png)

still testing.....

2022-06-17 17:20 UTC, PatrickvL requested changes
Some remarks to look into

2022-06-17 19:22 UTC, medievil1 commented
issue that breaks the above mentioned games is the fact that oPos is getting saved to temp in the middle of reverse screenspace transform... so the offset isn't subtracted from the oPos used in the divided scale....
  temp = oPos;
  x_mul(oPos,xyz, r12, c(-38));
  x_rcc(r1,x, r12.w);
  oPos = temp;
  x_dp3(r7,w, r6, r6);
  x_mad(oPos,xyz, r12, r1.x, c(-37));

2022-07-05 20:37 UTC, medievil1 commented
this is another one that seems to offer no bad side, after last commit it seems to be great

2022-07-08 20:18 UTC, merged