Implement D3DDevice_RunVertexStateShader
Cxbx-Reloaded/Cxbx-Reloaded pull request #2380
Opened 2022-06-24 16:31 UTC by jackchentwkh

Implement D3DDevice_RunVertexStateShader HLE
a new submodule nv2a_vsh_cpu shall be added. 
both cxbx and cxbxr-emu projects shall be modified, all 4 c files inside "src" directory of nv2a_vsh_cpu submodule shall be added to these two projects in order to prevent compiler error messages. 
path to "import\nv2a_vsh_cpu\src" shall be added to the include paths setting of both projects.

tested with Spy Vs. Spy.

2022-06-24 17:14 UTC, jackchentwkh commented
This is the first time I add a new sub module to an existing project. And I am really not familiar with cmake. Would you kindly shine more light in further detail?

2022-06-24 20:18 UTC, ergo720 commented
You’ll have to create a new cmake file and place it in the projects directory of cxbxr, which is where we place all cmake files for external submodules that require a custom cmake file. In general terms, the contents of the new cmake file should be the same as those of the submodule cmake file, except for the command `find_package` and the variable `Boost_INCLUDE_DIR`, which should be deleted to remove the dependency on boost. I also notice that the debug C flags use –ggdb, which is specific to gcc and msvc probably won’t understand, so you should delete that too. Everything below the `Tests` comment can be deleted as well. Then, you need to update our main cmake file in the root directory of cxbxr with the command `add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/projects/nv2a_vsh_cpu")` and add the additional libraries to the command `set_target_properties` also in the same cmake file. Finally, you should update the `include_directories` command in the cmake files of cxbx and cxbxr-emu projects, so that they can actually find the `nv2a_vsh_emulator.h` header you are trying to include in main cxbx.

PS: check https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2290 to see how I added the libusb submdule as an example.

2022-06-24 20:20 UTC, ergo720 commented on .gitmodules
> +	url = https://github.com/abaire/nv2a_vsh_cpu.git
This submodule should be shallow, like all the others. You can do that with the command `git config -f .gitmodules submodule.<path>.shallow true`

2022-06-24 20:26 UTC, RadWolfie commented on .gitmodules
> +	url = https://github.com/abaire/nv2a_vsh_cpu.git
Shallow is only used for third-party projects not relative to xbox's end. This nv2a_vsh_cpu project is relative to xbox's end. So, using shallow may not be recommended as the project may recieve more updates since it is very fresh.

2022-06-24 20:52 UTC, ergo720 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	//LOG_UNIMPLEMENTED();
Is `D3DDevice_RunVertexStateShader` now completely implemented by this? If so, then you can just remove the macro. If it is still missing something, then you might want to add `LOG_INCOMPLETE();` instead.

2022-06-24 21:17 UTC, RadWolfie commented
By using nv2a_vsh_cpu's CMakeList.txt directly, I am receving an error about missing Boost library which confirm my theory. The repository indeed need to contain fix to allow skip unit test. Unit test is always required in main repository, except is not a requirement for third-party projects.

I recommended to wait until nv2a_vsh_cpu's repository contain necessary changes to cmake file before update this pull request to include the fix and I will provide commit for you to absorb or manually write them in. That's entirely up to you. 🙂

2022-06-24 22:03 UTC, medievil1 commented
I fixed the cmake issues (I think) it compiles to the end, BUT there are a few ```Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _nv2a_vsh_parse_program	cxbxr-emu	Y:\cxbxPR\vsh\Cxbx-Reloaded\build\projects\cxbxr-emu\Direct3D9.obj	1	
``` keeping it from finishing

2022-06-24 22:35 UTC, medievil1 commented
ok to resolve the above, you ALSO, in the cxbx and cxbx_emu make files have to add them to the linked libraries
target_link_libraries(cxbx
 PUBLIC libXbSymbolDatabase
 subhook
 libtomcrypt
 SDL2
 imgui
 libusb
 nv2a_vsh_emulator

2022-06-24 22:37 UTC, RadWolfie commented
@medievil1, can you verify if the changes applied to https://github.com/abaire/nv2a_vsh_cpu/compare/main...RadWolfie:opt-unit-test branch confirmed to be the same as your's?

2022-06-24 22:44 UTC, medievil1 commented
> @medievil1, can you verify if the changes applied to [abaire/nv2a_vsh_cpu@main...RadWolfie:opt-unit-test](https://github.com/abaire/nv2a_vsh_cpu/compare/main...RadWolfie:opt-unit-test) branch confirmed are the same as your's?
> 
> EDIT: For Cxbx-Reloaded's changes, there's only three lines to able compile the project with nv2a_vsh_emulator which are currently done locally.

not exactly, same principle, I just did step by step what Ergo suggested...removed boost(and now empty directory link) and the find package....
for cxbx, I changed cxbx-emu, cxbx and Main cmake lists, just to add paths to the nv2a_vsh source....not lots of changes, jist an add directory and the lib names mostly

2022-06-24 23:14 UTC, RadWolfie commented
Upstream pull request has been made: https://github.com/abaire/nv2a_vsh_cpu/pull/1

While waiting on above pull request to merge. Here's the [commit](https://github.com/RadWolfie/Cxbx-Reloaded/commit/4bd0d573f950a6a1d2cc0ac0cae47f79908bcc30) to make correction from this pull request to enable include nv2a_vsh_cpu repository into cmake system:

2022-06-24 23:39 UTC, medievil1 commented
> Upstream pull request has been made: [abaire/nv2a_vsh_cpu#1](https://github.com/abaire/nv2a_vsh_cpu/pull/1)
> 
> While waiting on above pull request to merge. Here's the [commit](https://github.com/RadWolfie/Cxbx-Reloaded/commit/4bd0d573f950a6a1d2cc0ac0cae47f79908bcc30) to make correction from this pull request to enable include nv2a_vsh_cpu repository into cmake system:

yea thats pretty much what I did....though now looking back I think I also had to fix the path to the src files inside the actual nv2a_vsh cmake list....I pulled them from import, but the list was in projects so path had to be appropriate

2022-06-25 01:29 UTC, jackchentwkh commented
Wow, sorry for causing so much trouble. 
@RadWolfie so after your upstream PR were merged, shall I cherry pick your[ commit ](https://github.com/RadWolfie/Cxbx-Reloaded/commit/4bd0d573f950a6a1d2cc0ac0cae47f79908bcc30) to my PR then?

2022-06-25 02:30 UTC, RadWolfie commented
> so after your upstream PR were merged, shall I cherry pick your[ commit ](https://github.com/RadWolfie/Cxbx-Reloaded/commit/4bd0d573f950a6a1d2cc0ac0cae47f79908bcc30) to my PR then?

You don't have to wait, you can cherry pick it locally and make fix some review remark(s) by @ergo720. You can also temporary pull my pull request as well to see if there's anything I may had missed or request some further change if need to. Once pull request is merged, last thing to do is update submodule. 🙂

2022-06-25 02:35 UTC, medievil1 commented
it has already been merged

2022-06-25 05:48 UTC, jackchentwkh commented
@RadWolfie sorry for me it will take me too much time to learn how to cherry pick or pull PR from your branch so I simply pick your changes and put it in my commit, hope you don't mind. and I also modified the cmake file of cxbx. 
 one strange thing is that after update submodule, I still didn't get the merged change from nv2a_vsh_cpu, so I manually download the cmakelist.txt and test it locally.

2022-06-25 05:50 UTC, jackchentwkh commented
btw, VS .sln an project files shall be regenerated to make those changes take effect.

2022-06-25 05:56 UTC, RadWolfie requested changes

2022-06-25 05:56 UTC, RadWolfie commented on projects/cxbx/CMakeLists.txt
> + "${CXBXR_ROOT_DIR}/import/nv2a_vsh_cpu/src"
We do not have any emulator codebase in cxbx. It is now only GUI codebase. Delete this change as it is not needed at all.

2022-06-25 05:56 UTC, RadWolfie commented on projects/cxbxr-emu/CMakeLists.txt
> +  "${CXBXR_ROOT_DIR}/import/nv2a_vsh_cpu/src"
Delete this change as it is not needed at all, it had been corrected in nv2a_vsh_cpu repository.

2022-06-25 05:56 UTC, RadWolfie commented on projects/nv2a_vsh_cpu/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
This file should not be here. Please delete it.

2022-06-25 06:04 UTC, RadWolfie commented
> one strange thing is that after update submodule, I still didn't get the merged change from nv2a_vsh_cpu, so I manually download the cmakelist.txt and test it locally.

Did you verify remote does has `https://github.com/abaire/nv2a_vsh_cpu.git` connected to a name? And did you go into `import/nv2a_vsh_cpu` folder to perform `git pull` command? Assuming the name is "origin", then it will be `git pull origin main` command.

> btw, VS .sln an project files shall be regenerated to make those changes take effect.

VS will regenerate whenever cmake's content changes is needed. If new source files are added, it will regenerate. New/updated/deleted sub-project will also cause VS to regenerate. They are controlled by `ZERO_CHECK` project.

2022-06-25 06:35 UTC, RadWolfie commented
I upload a [semi-functional branch](https://github.com/RadWolfie/Cxbx-Reloaded/commits/nv2a_vsh_cpu_pr) for you to pull. Although, I notice abaire made a change to the API for `nv2a_vsh_emu_initialize_xss_execution_state` to only two parameters. It's up to you to roll back few commits to cmake fix to work with cxbxr.

2022-06-25 08:02 UTC, jackchentwkh commented
@RadWolfie really appreciate for your great help. the current status of this PR is ready to be merged. but the commit history is a mess. 
  Frankly I will need some time to figure out the operations of these git related operations between different repos/branches/PRs/commits.
anyway, I will try to create a new branch, pull PR from your semi-functional branch, and finish the code change there. if I could success, then I will close this PR and open a new PR from the new branch. is this what your mean?

2022-06-25 08:34 UTC, jackchentwkh commented
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/pull/2382 is created to replace this one.

2022-06-25 09:20 UTC, jackchentwkh commented
replaced by #2382

2022-06-25 09:20 UTC, closed without merging

2022-06-25 15:45 UTC, RadWolfie commented
> if I could success, then I will close this PR and open a new PR from the new branch. is this what your mean?

Not what I meant, you can perform local hard reset on this PR's branch via `git reset --hard HEAD~6` command (this pull request, at this time, has 6 commits which can be remove). Then perform `git pull https://github.com/RadWolfie/Cxbx-Reloaded nv2a_vsh_cpu_pr` command to able pull the changes I made. After you verify the changes are working for you. You can perform force push than a normal push to clear out old commits with new commits. From there, you could continue with your review remarks. It's fine when you decided to start again on new branch with another pull request to continue with reviews.