Hotload shaders
Cxbx-Reloaded/Cxbx-Reloaded pull request #2439
Opened 2023-11-09 06:49 UTC by NZJenkins

Hotload shaders. Just for fun, not sure if this will be useful.
But also consolidated the shader code a bit.

- All shaders are now read from files (instead of some being inline strings or #included strings)
- `ShaderHlsl` in `Shader.h` has all the shader text for both pixel and vertex shaders, and keeps track of if they were updated.
- On start, Cxbx will watch the HLSL directory for changes.
If a change is detected, shader caches are flushed and _all_ shaders are reloaded.
This is not wired up to an option so can't be switched off.

- [ ] Add safety net e.g. include backup copies of shaders in cmake?

2023-11-09 20:32 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        EmuLog(LOG_LEVEL::DEBUG, "Using hard ware vertex processing");
Why was a space inserted between hard and ware?

2023-11-09 20:40 UTC, PatrickvL commented on src/core/hle/D3D8/XbPixelShader.cpp
> +  // TODO hlsl hotloading support
What does this TODO need, specifically? Or is it a left-over that has already been done?

2023-11-09 21:02 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +		return 1;
For consistency, also do `fsWatcherThread = 0;`

2023-11-09 21:04 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +				g_ShaderHlsl.shaderVersionOnDisk += 1;
Why not just `++`?

2023-11-09 21:06 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +		while (true) {
Is there a global "shutdown-requested" boolean that could be checked here?

2023-11-09 21:08 UTC, PatrickvL commented on projects/misc/batch.cmake
> +# Copy HLSL files to the output directory, which we will can load at runtime
"will can" - What's it gonna be? ;)

2023-11-09 22:13 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	// TODO move d3d9 state to VertexShader.cpp
Would it be much work to actually do this?

2023-11-09 22:17 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +		if (passthroughShader) {
Would there be benefit in updating these separately, only when requested? That could avoid a needless compile when only one of the two is ever accessed.

2023-11-09 22:18 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +IDirect3DVertexShader* InitShader(void (*compileFunc)(ID3DBlob**), const char* label) {
Can't this stay static?

2023-11-09 22:23 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.h
> +struct ShaderHlsl {
With the rightful rename of `VertexShaderSource` into `VertexShaderCache`, it's perhaps good to change this name into `ShaderSources`, given that this type doesn't manage compiled shaders but the underlying shader (template) source codes (the fact they're in HLSL syntax is less important).

2023-11-09 22:28 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShader.cpp
> +	auto notionalSourceName = "CxbxVertexShaderTemplate.hlsl";
Would it make sense to change this type from `auto` into `static std::string`?

2023-11-09 22:32 UTC, PatrickvL requested changes
Besides the code remarks, a question : would it be possible to move the shared HLSL code towards an include file? That'd avoid having to change anything in that separately for each shader.

2023-11-10 00:52 UTC, RadWolfie commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	// TODO move d3d9 state to VertexShader.cpp
nit: Always include colon after TODO/NOTE, etc comments.

2023-11-10 06:06 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +		while (true) {
No, out if scope unless this is unstable for some reason. I was going to make this toggleable opt in via imgui but stopped short

2023-11-10 06:09 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +				g_ShaderHlsl.shaderVersionOnDisk += 1;
I don't care either way but can change if there is a good reason

2023-11-10 06:16 UTC, NZJenkins commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	// TODO move d3d9 state to VertexShader.cpp
I'm not sure but didn't want to touch too much.
If it's incorrect I'll remove it,
though.

2023-11-10 06:31 UTC, NZJenkins commented on src/core/hle/D3D8/XbVertexShader.cpp
> +		if (passthroughShader) {
It would be more efficient but I don't think it's worth it for a niche feature

2023-11-10 06:33 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/VertexShader.cpp
> +	auto notionalSourceName = "CxbxVertexShaderTemplate.hlsl";
Idk honestly

2023-11-10 07:52 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +			.append("hlsl/");
Why is the function calls on a separate lines? Aren't they suppose to be on same line?

2023-11-10 07:56 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +	fsWatcherThread = CreateThread(nullptr, 0, fsWatcher, nullptr, 0, nullptr);
nit: use C++'s std::thread instead of Windows' exclusive function.

2023-11-10 08:48 UTC, NZJenkins commented on src/core/hle/D3D8/XbVertexShader.cpp
> +IDirect3DVertexShader* InitShader(void (*compileFunc)(ID3DBlob**), const char* label) {
not sure what you mean specifically. `shader` should be temporary here though

2023-11-10 09:40 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +		return 1;
using `std::thread` means it's not necessary, we can check the thread is running with `joinable`

2023-11-10 09:47 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +			.append("hlsl/");
just style

2023-11-10 09:59 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +	fsWatcherThread = CreateThread(nullptr, 0, fsWatcher, nullptr, 0, nullptr);
nice, std::thread is much simpler also

2023-11-10 11:59 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +// End of vertex shader footer
Can this comment be removed entirely?

2023-11-10 12:03 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.h
> +extern ShaderSources g_ShaderHlsl;
It's probably cleaner to rename the `g_ShaderHlsl` global variable into `g_ShaderSources`, along with its also renamed type name.

2023-11-10 12:06 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +		while (true) {
It's what's done mostly in this repository, so if you're editing this file anyway, best take it along

2023-11-10 12:16 UTC, ergo720 commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +	fsWatcherThread = std::thread([]{
I see that this `std::thread` is neither joined nor detached. In that case, the C++ standard says that `std::terminate` is invoked when the destructor of the object is called. To avoid that, you should either join or detach the thread yourself, or better, just use `std::jthread` from C++20, which automatically joins on destruction.
With the above said, since I see that the thread is static and we exit the process with `TerminateProcess` of Windows (which doesn't call the destructors), then it's probably fine to ignore this problem in practice, but in my opinion, it still makes sense to solve this anyway

2023-11-10 12:16 UTC, ergo720 commented on src/core/hle/D3D8/Direct3D9/Shader.h
> +	volatile int shaderVersionOnDisk = 0;
Why is this `volatile`? Since I see it's being accessed from the `fsWatcherThread` object, I assume it's to ensure thread safety. In that case, `volatile` is not suitable for that purpose and you should use `std::atomic_int` instead

2023-11-10 12:23 UTC, NZJenkins commented
> Besides the code remarks, a question : would it be possible to move the shared HLSL code towards an include file? That'd avoid having to change anything in that separately for each shader.

Yes it's possible - for example FixedFunctionVertexShader is using #include to share code with Cxbxr already.

2023-11-10 16:32 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +			.append("hlsl/");
I did not see this style occur anywhere in our codebase. Can someone else confirm this?

Meaning if this style is not in our codebase, then basically we do not use this style here.

2023-11-10 18:10 UTC, RadWolfie requested changes
Even though two code remarks change requested are relocation but it's better to correct them as well.

2023-11-10 18:10 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderPassthrough.hlsl
> +    // Scale textures (TODO : or should we apply this to the input register values?)
No space between TODO and colon.

2023-11-10 18:10 UTC, RadWolfie commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	static IDirect3DVertexShader* fixedFunctionShader = nullptr; // TODO move to shader cache
Always add colon after TODO/NOTE, etc comments.

2023-11-10 18:10 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderPassthrough.hlsl
> +    // TODO deduplicate
Always add colon after TODO/NOTE, etc comments.

2023-11-10 22:12 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	g_ShaderSources.Update();
Nit: Consider to explicitly ignore return value here (for instance via a cast to void, of whatever other standard exists for this).

2023-11-10 22:17 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	g_ShaderSources.Update();
Then what do you reckon is wisest - centralise reused shader code towards an .hlsli include file now, or avoid any further risk and do that later?

2023-11-10 22:24 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +IDirect3DVertexShader* InitShader(void (*compileFunc)(ID3DBlob**), const char* label) {
Just ignore this remark, it was incorrect - the previous line contents declared a static global variable, now it's a function header that doesn't need a static marker.

2023-11-10 22:25 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	// TODO move d3d9 state to VertexShader.cpp
I agree it's best to avoid changing too much - it's already great what you've done here. Further work can come later, indeed.

2023-11-10 22:27 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +				g_ShaderHlsl.shaderVersionOnDisk += 1;
It's what's done mostly in this repository, so if you're editing this file anyway, best take it along

2023-11-10 22:31 UTC, PatrickvL commented
> > Besides the code remarks, a question : would it be possible to move the shared HLSL code towards an include file? That'd avoid having to change anything in that separately for each shader.
> 
> Yes it's possible - for example FixedFunctionVertexShader is using #include to share code with Cxbxr already.



> > Besides the code remarks, a question : would it be possible to move the shared HLSL code towards an include file? That'd avoid having to change anything in that separately for each shader.
> 
> Yes it's possible - for example FixedFunctionVertexShader is using #include to share code with Cxbxr already.

Then what do you reckon is wisest - centralise reused shader code towards an .hlsli include file now, or avoid any further risk and do that later?

2023-11-10 22:33 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.h
> +extern ShaderSources g_ShaderHlsl;
Resolved

2023-11-10 22:34 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +// End of vertex shader footer
Resolved

2023-11-10 22:35 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShader.cpp
> +	auto notionalSourceName = "CxbxVertexShaderTemplate.hlsl";
If most of this code base is specifying explicit types, and if you're going to touch up this pull request a little more anyway, then perhaps it's good to take this along as well?

2023-11-10 22:36 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.h
> +struct ShaderHlsl {
Resolved

2023-11-10 22:55 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +        EmuLog(LOG_LEVEL::DEBUG, "Using hard ware vertex processing");
Resolved

2023-11-10 22:55 UTC, PatrickvL commented on src/core/hle/D3D8/XbPixelShader.cpp
> +  // TODO hlsl hotloading support
Resolved

2023-11-10 22:56 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +		while (true) {
Acceptable.

2023-11-10 22:56 UTC, PatrickvL commented on projects/misc/batch.cmake
> +# Copy HLSL files to the output directory, which we will can load at runtime
Resolved

2023-11-10 22:57 UTC, PatrickvL commented on src/core/hle/D3D8/XbVertexShader.cpp
> +		if (passthroughShader) {
Acceptable

2023-11-11 08:17 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +	fsWatcherThread = std::thread([]{
I just want a fire and forget thread for this - sounds like that's `std::jthread`

2023-11-11 08:20 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +			.append("hlsl/");
I was answering your question. But it sounds like you meant "please change this"

2023-11-11 08:28 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.h
> +	volatile int shaderVersionOnDisk = 0;
I marked it `volatile` since my understanding is that calls out variables shared by multiple threads or can change unexpectedly - which I think has some implications in c++ compiler wise, but also makes it easy to see for a reader.

There isn't any synchronization happening as such, so I thought it was fine to ignore locks/atomics etc. here

I can remove volatile or synchronize the value if it makes more sense, I'm not sure.

2023-11-11 08:33 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/VertexShader.cpp
> +	auto notionalSourceName = "CxbxVertexShaderTemplate.hlsl";
ok. I was a bit confused because the explicit type would be `const char*`. can be explicit

2023-11-11 08:46 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderPassthrough.hlsl
> +    // Scale textures (TODO : or should we apply this to the input register values?)
there are 457 `TODO :` in the codebase, 395 `TODO:`, and 59 `TODO `

Not sure why TODO comments are worth commenting on, let alone doubling back to "fix"?

2023-11-11 08:48 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	g_ShaderSources.Update();
it seems to be `(void)`, though there is also `std::ignore`. `_ =` would be nice!

2023-11-11 09:20 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Shader.h
> +	volatile int shaderVersionOnDisk = 0;
made it atomic anyway

2023-11-11 09:31 UTC, NZJenkins commented
> > > Besides the code remarks, a question : would it be possible to move the shared HLSL code towards an include file? That'd avoid having to change anything in that separately for each shader.
> > 
> > 
> > Yes it's possible - for example FixedFunctionVertexShader is using #include to share code with Cxbxr already.
> 
> Then what do you reckon is wisest - centralise reused shader code towards an .hlsli include file now, or avoid any further risk and do that later?

Not something I want to look at now. But it should be easy for next time some common code has to be changed across multiple shader files.

2023-11-11 10:19 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderPassthrough.hlsl
> +    // Scale textures (TODO : or should we apply this to the input register values?)
Because `TODO:` is grammar correct. When I had read the documentations from past and present. Not once had I seen without colon nor has space between them. Also, if you had look up "todo" keyword in GitHub's search engine. You will find numerous of "todo:" results in various repositories. Some may have `TODO(something something): details here` which isn't correct way to do it when it should be `TODO: (something something) details here`. Some languages may do things differently except doesn't apply to C/C++ language.

For historically education, past Visual Studio IDEs does not list any TODOs doesn't have colon after it. And require no space in-between either.

Other than that, if clang-format is enforced. It will not check for those mistakes which is our responsibility to correct them manually.

The log file may can be different to align colons as a columns view for easier to read which is a different topic.

2023-11-11 10:55 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +				g_ShaderHlsl.shaderVersionOnDisk += 1;
confirmed resolved

2023-11-11 21:46 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	g_ShaderSources.Update();
Resolved

2023-11-11 21:51 UTC, PatrickvL commented on src/core/hle/D3D8/Direct3D9/VertexShader.cpp
> +	auto notionalSourceName = "CxbxVertexShaderTemplate.hlsl";
Resolved (partially, there's other auto's in these changes but those are all moved around, not new - but since there's no guidance in this repo on what to use when, it's fine for now)

2023-11-11 21:53 UTC, PatrickvL approved these changes

2023-11-11 22:11 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/Shader.cpp
> +			.append("hlsl/");
Turns out upstream's shader files are affected. Nowhere else used this code style. For now I'll dismiss this.

2023-11-11 22:15 UTC, RadWolfie commented on src/core/hle/D3D8/XbVertexShader.cpp
> +	static IDirect3DVertexShader* fixedFunctionShader = nullptr; // TODO move to shader cache
code was relocated, allowing to bypass request change.

2023-11-11 22:15 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderPassthrough.hlsl
> +    // TODO deduplicate
code was relocated, allowing to bypass request change.

2023-11-12 08:30 UTC, PatrickvL submitted a review, later dismissed

2023-11-14 20:25 UTC, medievil1 commented
the template isn't being built into the folder currently 
![image](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/assets/38597905/2aef522e-043a-42e1-b89c-c29424f64fc2)

2023-11-14 20:49 UTC, medievil1 commented
`./hlsl/backup contains backup copies so it's easy to revert changes if someone forgets to make backups or what changes they made etc.`
the above is not happening, no backup folder is created when you make changes to vertex or pixel shader

2023-11-16 14:08 UTC, RadWolfie commented on projects/cxbx/CMakeLists.txt
> +install(DIRECTORY $<TARGET_FILE_DIR:cxbx>/hlsl DESTINATION bin)
These should not be in here, cxbx is a GUI project, not an emulator project. Also, they need to remain in root directory as usual.

2023-11-16 14:09 UTC, RadWolfie commented on projects/misc/batch.cmake
> -file(COPY ${CXBXR_HLSL_FILES} DESTINATION ${HlslBackupOutputDir})
These files are triggered whenever the files has change on build process. Tbh, they should be remain here whenever file was edited.

2023-12-28 23:49 UTC, medievil1 commented
anyone every find any functional issues??...everything I tried works as it should, no outstanding issues...

2023-12-29 10:43 UTC, PatrickvL approved these changes

2023-12-29 10:43 UTC, merged