fog stuff
Cxbx-Reloaded/Cxbx-Reloaded pull request #2445
Opened 2024-01-18 06:36 UTC by medievil1

fix no fog issue which was incorrectly passing data into iFog instead of 1 when fog was disabled

testing a move to pixel shader

adjust passthrough template

for move to pixel shader

remove printf

2024-01-18 07:22 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/CxbxPixelShaderTemplate.hlsl
> +	  fogEnable = 1;
suggestion: i think this can be simplified a bit.
If fog is enabled, we look at the fog table mode and calculate the final fog factor from the fog depth value.
If the fog isn't enabled, we can probably skip all the table stuff and go straight to setting final fogFactor to 1.

In any case I don't think we need the fogEnable variable that gets assigned to fogDepth?

2024-01-18 07:22 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = {fogTableMode, fogDensity, fogStart, fogEnd};
question: was this cast to float killing a warning?

2024-01-18 07:22 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +#include "FixedFunctionVertexShaderState.hlsli"
question: not clear why this file changed. accidental changes?

2024-01-18 14:30 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxPixelShaderTemplate.hlsl
> +uniform const float4 FOGFACTOR : register(c28);
changed to FOGINFO

2024-01-18 14:31 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxPixelShaderTemplate.hlsl
> +	  fogEnable = 1;
yea I had debated that at the time...went ahead and changed it around and eliminated fogEnable

2024-01-18 14:32 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/Direct3D9.cpp
> +	float fogStuff[4] = {fogTableMode, fogDensity, fogStart, fogEnd};
ooops, meant to change the initializer to float so it was no longer needed, fixed...

2024-01-18 14:33 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +#include "FixedFunctionVertexShaderState.hlsli"
thought I had removed this (pretty sure I had, probably on the wrong copy..lol....
fixed now

2024-01-19 04:24 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/FixedFunctionVertexShader.hlsl
> +
nit: up to 2 newlines are permitted. However this become total of 3 newlines, and doesn't need 2-3 newlines before the return.

2024-01-19 04:26 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +
fogging calculation had been moved. Any reason to keep leftover comment here, including newline as well?

2024-01-19 04:27 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderPassthrough.hlsl
> +
nit: don't need newline here

2024-01-19 04:28 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/CxbxPixelShaderTemplate.hlsl
> +
nit: don't need newlines at beginning of the function.

2024-01-19 05:56 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxPixelShaderTemplate.hlsl
> +
fixed

2024-01-19 05:56 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderPassthrough.hlsl
> +
fixed

2024-01-19 05:56 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/CxbxVertexShaderTemplate.hlsl
> +
fixed

2024-01-19 05:57 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/FixedFunctionVertexShader.hlsl
> +
fixed

2024-01-19 05:57 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +
fixed

2024-01-20 07:51 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		ctx.CURRENT.rgb = lerp(state.FogColor.rgb, ctx.CURRENT.rgb, clamp(input.iFog, 0, 1));
After talked with @NZJenkins, saturate is basically a clamp between range of 0 to 1. I'm not sure if the [doc's implementation](https://developer.download.nvidia.com/cg/saturate.html) is the same or changed a bit.

2024-01-20 08:24 UTC, RadWolfie commented
Friendly reminder: Please post which titles gain this fog improvement.

2024-01-20 20:12 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		ctx.CURRENT.rgb = lerp(state.FogColor.rgb, ctx.CURRENT.rgb, clamp(input.iFog, 0, 1));
I Can change it back if you guys want, I changed it to clamp since Xemu uses clamp in this spot and saturate does it a bit different than simple clamp...

2024-01-20 20:20 UTC, medievil1 commented
Titles affected include
KOTOR
Nfl street
Dolphin sample
and basically any that use fog (pixel shader moves) or set fogenable to false, since previously that was not passed as 1 for fogDepth as it should have been.
![image](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/assets/38597905/65ac53f3-0a8b-4aba-bf27-b69b35851644)

previously KOTOR character was blacked out....as well as characters in NFL street and probably other titles... the nemu in burnout 3 for example had blacked out textures in the background... not they show the wrongly created (or possibly clipped) textures 
![image-1](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/assets/38597905/66a7e2cd-1a1a-4277-9276-d5e3ad6175f6)

2024-01-20 20:24 UTC, medievil1 commented
note that the above screenshot of Burnout 3 is from PB pr with fog fixes since currently master has depth texture reading issues (product of D3D ) and PB uses INTZ to get around those

2024-01-20 21:30 UTC, RadWolfie commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		ctx.CURRENT.rgb = lerp(state.FogColor.rgb, ctx.CURRENT.rgb, clamp(input.iFog, 0, 1));
xemu use clamp call mainly because saturate function doesn't exist for OpenGL driver. I'm not sure what other ways other than min/max "clamp" there is. I think they're basically the same except clamp has user input for low and high value vs saturate has fixed 0 (low) and 1 (high) values.

With that said, I did test before and after you made the change for kotor title difference and along with other titles has fog (which didn't have any difference from PR). They all return the same results for me.

Anyway, if there's a plan on making inline hybrid shader to support DirectX and OpenGL. Then for sure all the saturate calls will need to replace with clamp calls. I'll leave this up to whatever graphic experts are going for.

2024-01-21 01:56 UTC, medievil1 commented
last commit should fix template formatting mismatches
also the DOA reflections on ice world actually comes from PB branch pr, it does work fine in master so left it in the template

2024-01-23 06:25 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionPixelShader.hlsl
> +		TexCoords[i].xyzw = TexCoords[i].xyzw / TexCoords[i].w;
question: not related to fog right - is this included accidentally?

2024-01-23 06:25 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionVertexShader.hlsl
> +        //texCoord.xyzw = texCoord.xyzw / texCoord.w;
question: not related to fog right - is this included accidentally?

2024-01-23 06:25 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionVertexShader.hlsl
> +            texCoord.zw = float2(0, 1);
question: not related to fog right - is this included accidentally?

2024-01-23 06:25 UTC, NZJenkins commented on src/core/hle/D3D8/XbPixelShader.cpp
> +constexpr int PSH_XBOX_CONSTANT_MAX = PSH_XBOX_CONSTANT_FOGENABLE + 1; // = 28
nitpick: comment for register number is not quite right. Looks like `// = 28` should be on line 665, then `// = 29` on 666

2024-01-24 02:28 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/FixedFunctionVertexShader.hlsl
> +            texCoord.zw = float2(0, 1);
not exactly accidentally....  this one and the one above, they are just a few fixes from PB PR branch that work as well on master, i was working on the move on PB first and didn't realize when I moved it to master I just copied the templates and didn't realize that FF temp had other fixes, I have verified they are valid though, I just left them in since some games may benefit

2024-01-24 02:46 UTC, medievil1 commented on src/core/hle/D3D8/XbPixelShader.cpp
> +constexpr int PSH_XBOX_CONSTANT_MAX = PSH_XBOX_CONSTANT_FOGENABLE + 1; // = 28
ooops, changed it once, must have gotten reverted at some point. fixed now

2024-01-24 08:13 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionVertexShader.hlsl
> +            texCoord.zw = float2(0, 1);
I checked out DoA and reflections on the "Ice Cave" look good.
![image](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/assets/9897874/e84e514e-d3ff-4a1f-90f4-198acf02eefa)

ProjectedTexture is improved but not correct (though Jack had this working at some point, there is a screenshot in discord chat):
![image](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/assets/9897874/aace5dff-c9df-4abe-a1fe-0dbb547ddde9)

This code looks experimental: code is commented out, the old comments are still present explaining the disabled code, and there's no explanation of the new code.

Given the above I think there's more work to do on solving projected behaviour - I don't think it is ready to be merged.

2024-01-27 00:23 UTC, medievil1 commented on src/core/hle/D3D8/Direct3D9/FixedFunctionVertexShader.hlsl
> +            texCoord.zw = float2(0, 1);
projected texture may also need some of the other PB only fixes to completely work correctly.... and yea not removed the old code in this area yet in case it had to be reverted, just to make it easier...lol

2024-02-01 23:15 UTC, NZJenkins commented on src/core/hle/D3D8/Direct3D9/FixedFunctionVertexShader.hlsl
> +            texCoord.zw = float2(0, 1);
This also seems to break ModifyPixelShader and texture scrolling in jsrf. I think PB and master have incompatible matrix representations but didn't dig deep into it.
Anyways the non-fog stuff should be dropped out.

2024-02-01 23:16 UTC, NZJenkins requested changes
Please remove unrelated PB as mentioned otherwise LGTM

2024-02-03 17:09 UTC, medievil1 commented
> Please remove unrelated PB code as mentioned otherwise LGTM

should be fixed

2024-05-22 11:41 UTC, LukeUsher approved these changes
Looks like the requested changes were made, no point delaying this even further.

2024-05-22 11:42 UTC, merged